### DISCUSSION TITLE
Overwriting conf groups from CLI

### DISCUSSION THREAD

**Discussion by pietrolesci** [facebookresearch/hydra#2084] [Q&A] [answered]
Hi there,

I am trying to overwrite from the CLI a group of parameters and I am not sure how to do it. The structure of my conf is the following

```
conf
├── config.yaml
├── optimizer
│   ├── adamw.yaml
│   ├── adam.yaml
│   ├── default.yaml
│   └── sgd.yaml
├── task
│   ├── default.yaml
│   └── nlp
│       ├── default_seq2seq.yaml
│       ├── summarization.yaml
│       └── text_classification.yaml
```

My `task/default ` looks like this

```yaml
# @package task
defaults:
  - _self_
  - /optimizer/adam@cfg.optimizer

_target_: src.core.task.Task
_recursive_: false

cfg:
  prefix_sep: ${training.prefix_sep}
```

while the `optimiser/default` looks like this
```yaml
_target_: null
lr: ${training.lr}
weight_decay: 0.001
no_decay:
  - bias
  - LayerNorm.weight
```

and one specific optimiser, say adam.yaml, looks like this

```yaml
defaults:
  - default

_target_: torch.optim.Adam
```

In the end the config I'd like to be computed is like this

```yaml
task:
  _target_: src.task.nlp.nli_generation.task.NLIGenerationTask
  _recursive_: false
  cfg:
    prefix_sep: ${training.prefix_sep}
    optimizer:
      _target_: torch.optim.Adam
      lr: ${training.lr}
      weight_decay: 0.001
      no_decay:
      - bias
      - LayerNorm.weight
```

I would like to be able to modify the optimiser via the CLI (say, use sgd), but I am not sure how to achieve this. I tried, but I understand why it fails, this

```
python train.py task.cfg.optimizer=sgd # fails
python train.py task.cfg.optimizer=/optimizer/sgd #fails
```

Any tips on how to achieve this?

StackOverflow question [here](https://stackoverflow.com/questions/71438040/overwriting-hydra-configuration-groups-from-cli).
