### DISCUSSION TITLE
override this nested list

### DISCUSSION THREAD

**Discussion by dagap** [facebookresearch/hydra#2106] [Q&A] [answered]
I have a configuration which I am defining as follows:

**preprocessing**

```
_target_: make_pipeline

steps_config: 
  - ColumnMapper:
      _target_: ColumnMapper
      columns: null
  - SeriesMaker:
      _target_: SeriesMaker
      time_column: null
      value_cols: null
```

Now, I want to specify these null fields from the command line. So, I tried something like:

```
'preprocessing.steps_config.1.value_cols=[x, y]'
```
Now, this comes back with 
```
Could not override 'preprocessing.steps_config.1.value_cols'.
To append to your config use +preprocessing.steps_config.1.value_cols=[x,y]
`Key 'value_cols' is not in struct
    full_key: preprocessing.steps_config[1].value_cols
    object_type=dict`
```

I tried various combinations but it does not seem to see the final key in the dictionary.
