### DISCUSSION TITLE
Common variables?

### DISCUSSION THREAD

**Discussion by FeryET** [facebookresearch/hydra#2127] [Q&A] [answered]
Image I have two objects that depend on the same value, but I want to keep a good dependency injection pattern without too much of a manual coding.
```python
class A:
   def __init__(today: str):
        self.today = today

class B:
  def __init__(today: str):
       self.today = today
```

Both of these classes have their own config files. How can I keep today consistent between these two? Does hydra provide any solution? `jsonargparse` has a feature that you can link two variables together. It would be neat to see if hydra provides similar configurability.

**Comment by Jasha10** [comment, marked as answer]
See OmegaConf's [variable interpolation](https://omegaconf.readthedocs.io/en/latest/usage.html#variable-interpolation) feature.

Are you using Hydra's [instantiate](https://hydra.cc/docs/advanced/instantiate_objects/overview/) API? If so, something like this should work:

```yaml
# my_config.yaml
a_instance:
  _target_: my_module.A
  today: ${today}
b_instance:
  _target_: my_module.B
  today: ${today}
today: ...
```
The string `"${today}"` is a "variable interpolation". It essentially functions as a pointer to the top-level `"today"` key.

**Reply by aliutkus** [reply]
Would this thing work if I wanted `today` to be an object ?

I actually want:
```python
c_instance = my_module.C(params_c=3)
a_instance = my_module.A(params_a=1, c_instance=c_instance)
b_instance = my_module.B(params_b=1, c_instance=c_instance)
```
Is this doable with hydra, e.g. with something like:

```yaml
# my_config.yaml
a_instance:
  _target_: my_module.A
  params_a: 1
  c_instance: ${c_instance}
b_instance:
  _target_: my_module.B
  param_b: 2
  c_instance: ${c_instance}
c_instance:
  _target_: my_module.C
  param_c: 3
```

thanks
