### DISCUSSION TITLE
Top level config has to be OmegaConf DictConfig

### DISCUSSION THREAD

**Discussion by kuntiik** [facebookresearch/hydra#2137] [Q&A] [answered]
Hello,
I have this the following config

```yaml
foo:
  _target_ : src.transforms.transforms_composer.TransformsComposer
  cfg :
    image_size : 1024
    HorizontalFlip:
      apply : True
      transform :
        _target_ : albumentations.HorizontalFlip
        p : 0.5
```
When I call hydra.utils.instantiate(foo) I get the following error Top level config has to be OmegaConf DictConfig, plain dict, or a Structured Config class or instance. Can anyone please tell me, what I am doing wrong? The object TransformsComposer takes keyword argument cfg and I expect it to be some kind of dictionary...
Thank you for any suggestions
