### DISCUSSION TITLE
Cannot override value in instantiate

### DISCUSSION THREAD

**Discussion by fColangelo** [facebookresearch/hydra#2223] [Q&A]
Hi! I am having a problem overriding a value when instantiating an object and can't seem to find out why. Basically,  I am instantiating a Pytorch dataset object using hydra instantiate, passing the cfg object to the Dataset object being instantiated. To do this, the dataset cfg contains an empty cfg object:
```yaml
[...]    
training_dataset:
   _target_: src.datamodules.components.baseline_datasets.FSD50K
   cfg: omegaconf.dictconfig.DictConfig(content={})
   mode: "training"
[...]
```
And, at runtime, the cfg object should be overwritten by the instantiate call:

```python
class AudioTagDataModule(LightningDataModule):
    def __init__(self, cfg: DictConfig):
       super().__init__()
       self.cfg = cfg
       self.save_hyperparameters(logger=False)


    def setup(self, stage: Optional[str] = None):
       
       self.trainset  = instantiate(self.cfg.datamodule.training_dataset, cfg=self.cfg)
       [...]
```
However, when debugging I see that the empty cfg overwrite does not happen and the dataset is instantiated with the empty, default cfg. 
From what I understood of the documentation, specifying a value with the same name should override the default. Can someone help me understand what I am doing wrong? 
Thanks!
