### DISCUSSION TITLE
How to set hydra.job.chdir in the Defaults List of yaml file

### DISCUSSION THREAD

**Discussion by Khoa-NT** [facebookresearch/hydra#2232] [Q&A] [answered]
Hi,  
I saw from version 1.2, `hydra.job.chdir=False` by default.
How can I set this configuration `hydra.job.chdir=True` in the Defaults List in a `file.yaml` instead of typing `python my_app.py hydra.job.chdir=True`?

E.g:
```yaml
defaults:
  - override hydra.job.chdir: true
  - _self_
```
I tried the example above but it didn't work.
