### DISCUSSION TITLE
Is it possible to override parameters from a .yaml file via defaults list?

### DISCUSSION THREAD

**Discussion by YerePhy** [facebookresearch/hydra#2240] [Q&A] [answered]
Hi,

Is it possible to override parameters from the defaults list in a  .yaml file? I mean something like that:

<pre>
defaults:
  - _self_
  - datamodule/monai_holdout_datamodule
  - lightningmodule/unetlike
  <b>- override datamodule/monai_holdout_datamodule/batch_size: 2</b>
</pre>

I know its possible from the CLI with `python train.py -m datamodule.batch_size=2`, but I don't know if there is any option of doing this from the .yaml file itself.

**Comment by jieru-hu** [comment, marked as answer]
yes - since this is a config value you can override it in the yaml. note: defaults lists is used for config groups, not values.

```yaml
datamodule:
  monai_holdout_datamodule:
    batch_size: 2
```

**Reply by YerePhy** [reply]
Thanks for your help but your proposal doesn't work for me, do you see something wrong here? 

Folder structure:

```text
train/
├── config.yaml
├── datamodule
│   ├── monai_holdout_datamodule.yaml
│   ├── patch_func
│   │   └── label.yaml
│   ├── splitter
│   │   └── hold_out.yaml
│   ├── test_stage_transformations
│   │   └── dummy.yaml
│   └── train_stage_transformations
│       └── dummy.yaml
└── lightningmodule
    ├── architecture
    │   └── unet.yaml
    ├── loss
    │   └── generalized_dice.yaml
    ├── metrics
    │   └── dice.yaml
    ├── optimizer_configuration
    │   └── adam.yaml
    ├── scheduler_configuration
    │   └── step_lr.yaml
    └── unet_like.yaml
```

My `config.yaml`:

```yaml
defaults:
  - _self_
  - datamodule/monai_holdout_datamodule
  - lightningmodule/unet_like

datamodule_type: monai_hold_out
lightningmodule_type: unet_like
datamodule:
  monai_holdout_datamodule:
    batch_size: 2
```

My script:

```python
import hydra
from omegaconf import DictConfig, OmegaConf, OmegaConf
from utils import datamodule_factory, lightningmodule_factory

@hydra.main(config_path="./configs/train", config_name="config")
def main(cfg: DictConfig):
    """
    Perform training.
    """
    OmegaConf.register_new_resolver("get_method", hydra.utils.get_method)
    cfg = hydra.utils.instantiate(cfg, _recursive_=True)
    
    print(cfg["datamodule"]["batch_size"])

    return None

main()
```

Output: `1`.

**Reply by Jasha10** [reply]
What if you put `_self_` at the *end* of your defaults list in `config.yaml`?
```yaml
defaults:
  - datamodule/monai_holdout_datamodule
  - lightningmodule/unet_like
  - _self_

...
datamodule:
  monai_holdout_datamodule:
    batch_size: 2
```
The order of the defaults list controls the order in which the configs will be merged together.
