### DISCUSSION TITLE
a way to create some "unique" resolve ?

### DISCUSSION THREAD

**Discussion by aliutkus** [facebookresearch/hydra#2248] [Q&A]
Hi. Here's a minimal example of my usecase

For some reason, I want to create some configuration for the following:
```python
a = mymodule.A(foo=1)
b = mymodule.B(bar=2, a=a)
c = mymodule.C(baz=3, a=a)
```
I want to use hydra for this, and I found out I could try to use resolving in the following way:

```yaml
a:
  _target_: mymodule.A
  foo: 1
b:
  _target_: mymodule.B
  bar: 2
  a: ${a}
c:
  _target_: mymodule.C
  baz: 3
  a: ${a}
```
and then use `hydra.utils.instantiate`.

This would be great, but it doesn't work, since it's a _different instance_ of `a` that gets created when instantiating `b` and `c`.

Is there a way I can do that with hydra without first instantiating `a` and then using partials for `b` and `c` ? (my system is more complicated than this mimal example and it would be awesome to avoid all this partial manipulation...)

That could mean having the instantiate recursive thing trace it when things have already been instantiated and not create new objects.
It would also be able to actually access those objects _through the configuration_ when instantiated. Like I could just do `cfg = instantiate(cfg)` and simply access my objects through `cfg.a`, `cfg.b` `cfg.c`, etc
