### DISCUSSION TITLE
specializing configs (conditional statements)

### DISCUSSION THREAD

**Discussion by danbider** [facebookresearch/hydra#2264] [Q&A]
I've read the docs [here](https://hydra.cc/docs/patterns/specializing_config/).

Still trying to figure out how can I do something like

```
single_frame:
  train:
    sequence_length: 16 
    step: ${sequence_length} # step = sequence_length by default
    batch_size: 1 # default, can't be changed
    random_shuffle: True

```
this returns:
```
single_frame': {'train': {'sequence_length': 16, 'step': '${sequence_length}', 'batch_size': 1, 'random_shuffle': True}
```
but I want `step: 16`.
how should i go about it?
