### DISCUSSION TITLE
Same object classes get merged in a list

### DISCUSSION THREAD

**Discussion by pamparana34** [facebookresearch/hydra#2278] [Q&A]
In my project configuration, I have the options to use multiple optimisers and the optimisers config are specified as follows:

```
--config
     --model
            -> model.yaml
            - optimiser
               -> adam.yaml
               -> sgd.yaml
```

The optimisers are as follows:

```
adam:
  _target_: torch.optim.Adam
  lr: 1e-4
  weight_decay: 0.0
```

```
sgd:
  _target_: torch.optim.SGD
  lr: 1e-4
  momentum: 0.99
```

and the `model.yaml` uses them as follows:

```
defaults:
  - optimizer: adam
```

Now, with this setup I can specify multiple optimisers to the model. So, on the command line, I can specify: `model/optimizer='[adam, sgd]'` and I get this in my code:

```
{'adam': {'_target_': 'torch.optim.Adam', 'lr': 0.01, 'weight_decay': 0.0}, 'sgd': {'_target_': 'torch.optim.SGD', 'lr': 0.0001, 'momentum': 0.99}}
```

I can also override them on the command line as `model.optimizer.adam.lr-0.1`. 

The issue is now that I want to sometime pass the same object type in the list. So, I want to do something like:

```
model/optimizer='[adam, adam]'
```

and this gets merged due to dictionary. I am wondering what I can do to keep all the above behaviours but stop this from being merged?
