### DISCUSSION TITLE
hydra change job directory in config files

### DISCUSSION THREAD

**Discussion by dagap** [facebookresearch/hydra#2298] [Q&A] [answered]
Currently, I am setting `hydra.job.chdir=True` on the command line. Is it possible to specify this in the config file as a default?

**Comment by Jasha10** [comment, marked as answer]
Yes, you should be able to set this in your config file.
```yaml
# conf.yaml
hydra:
  job:
    chdir: true
...
```
