### DISCUSSION TITLE
Switch extended configs

### DISCUSSION THREAD

**Discussion by faroit** [facebookresearch/hydra#2317] [Q&A]
The documentation [states how to extend configs](https://hydra.cc/docs/patterns/extending_configs). I have a hard time understanding how to design a pattern so that one can change/override the defaults via CLI, though:

### Existing example

```yaml
# config.yaml
defaults:
  - base_mysql

user: omry
password: secret
port: 3307
encoding: utf8
```

```yaml
# db/mysql.yaml
defaults:
  - db: mysql 
```

```yaml
# db/base_mysql.yaml
host: localhost
port: 3306
user: ???
password: ???
```

### Problem

Now if I would now add two new files called

```yaml
# db/sqlite.yaml
defaults:
  - db: sqlite
```

```yaml
# db/base_sqlite.yaml
...
```

how can I change the default extension from the commandline to switch between `sqlite` and `mysql` without setting `db=sqlite`?

### Motivation/Use case

extending experiments with multiple levels: i have four files:

* `experiments/model1/commons.yaml`

```yaml
defaults:
  - override /xzy: abc
  - ...

# ...
# large number of baseline params
```

* `experiments/model1/fp16.yaml`

```yaml
defaults:
  - model1/commons

data:
  batch_size: 16

trainer:
  precision: 16 
```

* `experiments/model1/fp32.yaml`

```yaml
defaults:
  - model1/commons

data:
  batch_size: 8

trainer:
  precision: 32
```

* `experiments/run1.yaml`

```yaml
defaults:
  - model1/fp16

base:
  name: run1

# ...specific params
```

Now I want to switch between fp16 and fp32. How do I override this from cli?

I am sure, I missed important parts of hydra, so I would be happy if someone would point me to the right spot. My guess is that this is related to https://github.com/facebookresearch/hydra/issues/171 but please correct me!
