### DISCUSSION TITLE
How can I instantiate multiple objects?

### DISCUSSION THREAD

**Discussion by NadavQuris** [facebookresearch/hydra#2328] [Q&A] [answered]
Hi

I want to instantiate a varying number of objects. 
The use case is to instantiate multiple feature selectors to then use in sequence.
What I tried was:
```yaml 
defaults:
  - transforms:
    - normalize_and_standardize
  - feature_selectors:
      - correlation
      - tree_based
```

And with `feature_selectors/correlation`:
```yaml
_target_: data.data_loading.feature_selection.CorrelationBasedFeatureSelector
correlation_cutoff: 0.9
```

And `feature_selectors/tree_based`:
```yaml
_target_: data.data_loading.feature_selection.TreeBasedFeatureSelector
n_estimators: 100
```
This did not work, and it kind of mixed both configs into one DictConfig.
How am I supposed to use hydra in order to meet my needs?

Thanks :)

**Comment by NadavQuris** [comment, marked as answer]
Okay, it seems like the correct usage is:

`feature_selectors/correlation`:
```yaml
correlation:
    _target_: data.data_loading.feature_selection.CorrelationBasedFeatureSelector
    correlation_cutoff: 0.9
```

and `feature_selectors/tree_based`:
```yaml
tree_based:
    _target_: data.data_loading.feature_selection.TreeBasedFeatureSelector
    n_estimators: 100
```
