### DISCUSSION TITLE
How to override hydra config inside the config group?

### DISCUSSION THREAD

**Discussion by namespace-Pt** [facebookresearch/hydra#2410] [Q&A]
Here is my config structure:
```
- config
  - main
    - default.yaml
- script
  - run.py
```

In `run.py`:
```python
@hydra.main(version_base=None, config_path="../config", config_name="main/default")
def main(config: OmegaConf):
    print(config)

if __name__ == "__main__":
    main()
```
I want to **disable** the `output_subdir` and `logging` of hydra by writing the following in the `default.yaml`:
```yaml
defaults:
  - override hydra/hydra_logging: none
  - override hydra/job_logging: none

hydra:
  output_subdir: null
  run:
    dir: .
```

However the code didn't work:
```
hydra.errors.ConfigCompositionException: In 'main/_default': Could not override 'main/hydra/hydra_logging'. No match in the defaults list
```

What's the proper way to do that?

**Comment by Jasha10** [comment]
Try replacing `override hydra/hydra_logging: none` with `override /hydra/hydra_logging: none`, and similarly replace `override hydra/job_logging: none` with `override /hydra/job_logging: none`.

The error message indicates that you're trying to override `main/hydra/hydra_logging`. What you really need to override is `hydra/hydra_logging`, not `main/hydra/hydra_logging`. The entries in your defaults list are being interpreted as relative paths (relative to the `main` config group).

**Reply by namespace-Pt** [reply]
Replacing `override hydra/hydra_logging: none` with `override /hydra/hydra_logging: none` produces the following error:
```
hydra.errors.ConfigCompositionException: In 'main/_default': Could not override 'hydra/hydra_logging@main.hydra.hydra_logging'
```

I also tried the following:
```
defaults:
  - override /hydra/hydra_logging@_group_: none
  - override /hydra/job_logging@_group_: none
```
Then the logging is actually disabled.
However, the code to disable output subdir didn't work anyway:
```
hydra:
  output_subdir: null
  run:
    dir: .
```

The `outputs` directory persists.

**Reply by Jasha10** [reply]
Can you move the file `config/main/default.yaml` to `config/default.yaml`? The additional level of nesting is causing problems.

> However, the code to disable output subdir didn't work anyway

The issue here is that your composed config looks like this:
```python
$ python script/run.py
{'main': {'hydra': {'output_subdir': None, 'run': {'dir': '.'}}}}
  ^^^^ this extra nesting is causing the problem
```
The `hydra.output_subdir` setting you've specified in `default.yaml` appears nested underneath the `main` key. For the `hydra.output_subdir: null` setting to work properly, it needs to be at the top level.

**Reply by namespace-Pt** [reply]
Okay. Thank you.

**Reply by Jasha10** [reply]
Now that I think of it, there is another possibility: You can keep the nesting `config/main/default.yaml` and use an [`@package` directive](https://hydra.cc/docs/1.2/advanced/overriding_packages/#overriding-the-package-via-the-package-directive) to make sure that the `hydra` config is at the top level:

##### `config/main/default.yaml`:
```yaml
# @package _global_
# ^^^ this @package directive solves the nesting problem
defaults:
  - override /hydra/hydra_logging@_group_: none
  - override /hydra/job_logging@_group_: none

hydra:
  output_subdir: null
  run:
    dir: .
```
