### DISCUSSION TITLE
Interpolation issues when using the Compose API

### DISCUSSION THREAD

**Discussion by dagap** [facebookresearch/hydra#2466] [Q&A]
This has been mentioned before but I cannot find a solution that is working in my case. I am creating a hydra config object at the top level as:

```python
with initialize(version_base="1.2", config_path=config_dir, job_name=job_name):
    self.cfg = compose(
                config_name=config_name,
                return_hydra_config=True,
            )
```

Now, I am getting the following errors downstream:

```text
omegaconf.errors.InterpolationToMissingValueError: MissingMandatoryValue while resolving interpolation: Missing mandatory value: hydra.job.num
    full_key: hydra.sweep.subdir
    reference_type=SweepDir
    object_type=SweepDir
```

A minimum reproducible example:

```yaml
# configs/dev.yaml  i.e. top level config
hydra:
  run:
    dir: "logs/"
  sweep:
    dir: "sweeps/"
    subdir: ${hydra.job.num}
``` 

The driver code:

```python
from hydra import compose, initialize
from omegaconf import OmegaConf


def do_main():
    with initialize(version_base="1.2", config_path="../configs", job_name="dev"):
        cfg = compose(
            config_name="dev",
            return_hydra_config=True,
        )

        resolved = OmegaConf.to_container(cfg, resolve=True)  # This line causes the error


if __name__ == "__main__":
    do_main()
```
