### DISCUSSION TITLE
Overriding a value does not seem to inherit defaults

### DISCUSSION THREAD

**Discussion by mfoglio** [facebookresearch/hydra#2486] [Q&A]
I am using hydra to setup a pytorch lightning project to train a neural network.
By default, I'd like to:
- Train using a GPU
- Use a batch_size of 448
- Use 64 workers
I also want to create an optional file where I'd like to store settings that needs to be used when training locally: in fact, when running the project locally, I need to change the 3 parameters above: I want to try on the CPU using 1 worker and a batch_size=2. The idea is that by simply starting the script with the parameter `local=default`, the script will use all the proper settings needs to run the code locally.
So far, I achieved everything I wanted to, except using the CPU.
Here's a simplified structure of my hydra files:
File `config/train.yaml` (entrypoint):
```yaml
# @package _global_
defaults:
  - _self_
  - datamodule: vehicles
  - trainer: default
  - optional local: null  # default
```
File `config/datamodule/vehicles.yaml`:
```yaml
_target_: datamodules.vehicles_datamodule.VehiclesDataModule
batch_size: 448
num_workers: 64
```
File `config/trainer/default.yaml`:
```yaml
_target_: pytorch_lightning.Trainer
accelerator: gpu  # train using the GPU by default
precision: 16
```
File `config/trainer/cpu.yaml` (alternative to the default above):
```yaml
defaults:
  - default

accelerator: cpu
precision: 32
```
File `config/local/default.yaml`:
```yaml
# @package _global_

trainer: cpu  # without this line the training starts properly, however it would train on the GPU

datamodule:  # batch_size and num_workers are updated correctly when running the script with parameter `local=default`
  batch_size: 2
  num_workers: 1
```
If I add the line `trainer: cpu` to the `config/local/default.yaml` I get the following error when accessing `cfg.trainer._target_`:
```text
  File "/Users/matteo/Documents/Fusus/Coding/ai-models/src/train/train_hydra.py", line 66, in train
    log.info(f"Instantiating trainer <{cfg.trainer._target_}>")
AttributeError: 'str' object has no attribute '_target_'
```
Why would that be? I thought that the following two line in file `config/trainer/cpu.yaml` would load the `_target_` value from `config/local/default.yaml`:
```yaml
defaults:
  - default
 ```
However, if I remove the `trainer: cpu` from file `config/local/default.yaml` and I run the script with parameters `local=default trainer=cpu` everything works fine. What am I doing wrong?

**Comment by Jasha10** [comment]
Hi @mfoglio,

The file `config/local/default.yaml` file that you pasted above looks like this:
```yaml
# @package _global_

trainer: cpu

datamodule:
  batch_size: 2
  num_workers: 1
```
You'll need to change it to look something like this:
```yaml
# @package _global_

defaults:
  - override /trainer: cpu

datamodule:
  batch_size: 2
  num_workers: 1
```
