### DISCUSSION TITLE
How to configure optimizer that uses model parameters for further instantiation?

### DISCUSSION THREAD

**Discussion by chekhovana** [facebookresearch/hydra#2501] [Q&A]
I would like to instantiate both model and optimizer directly from config, but can't get how to pass model parameters to optimizer constructor. Below is my attempt that raises the error.
```yaml
model:
  _target_: timm.create_model
  model_name: resnet18
  pretrained: False
  num_classes: 1

optimizer:
  _target_: torch.optim.AdamW
  lr: 3e-4
  params:
    _target_: ${model}.parameters
```
Is it possible to achieve?

**Comment by Jasha10** [comment]
Hi @chekhovana,
I'm sorry to say that currently there is no clean way to do this with Hydra.
Doing this would require [singleton support](https://github.com/facebookresearch/hydra/issues/1393) to be implemented.

Without singleton support, referencing `${model}` inside of `optimizer` would likely result in two different instances of `model` being instantiated (instead of the same model instance being used in two places).

In the future, singleton support may be implemented. For future reference, I'll give some details on how this could be done if singleton support were available.

---

If singleton support _were_ available, passing in `parameters` to `optimizer` might look like this:
```yaml
model:
  _target_: timm.create_model
  model_name: resnet18
  pretrained: False
  num_classes: 1
  _singleton_: true  # requires https://github.com/facebookresearch/hydra/issues/1393

optimizer:
  _target_: torch.optim.AdamW
  lr: 3e-4
  params: ${getattr:${model},"parameters"}
```
In this example, `getattr` is a [custom resolver](https://omegaconf.readthedocs.io/en/2.3_branch/custom_resolvers.html#custom-resolvers) that looks up the `"parameters"` attribute on the `model` instance:
```python
OmegaConf.register_new_resolver("getattr", getattr)
```
