### DISCUSSION TITLE
Use yaml file instead of CLI overrides

### DISCUSSION THREAD

**Discussion by jonasteuwen** [facebookresearch/hydra#2529] [Q&A]
I am using hydra as follows:

```python
@hydra.main(
    config_path="../config",
    config_name="train.yaml",
    version_base="1.2",
)
def main(config: DictConfig):
    train(config)
```

Subsequently I overwrite (set) some of the parameters on the command line:

```shell
python train.py \
    datamodule.num_workers=16 \
    datamodule.batch_size=32 \
    data_description=brca_tissue_segmentation_more_classes \
    transforms=segmentation \
    losses=segmentation \
    lit_module=new_unet
```

Is there a way to do this with a config? For instance we could run
```shell
python train.py --config experiment_config.yaml
```

which would, in this case have as settings:
```yaml
datamodule:
    num_workers: 16
    batch_size: 32
data_description: brca_tissue_segmentation_more_classes
transforms: segmentation
losses: segmentation
lit_module: new_unet
```
