### DISCUSSION TITLE
Optuna with nested parameters

### DISCUSSION THREAD

**Discussion by thomashirtz** [facebookresearch/hydra#2533] [General]
I would like to use optuna with complex structure (agent, trainer, ...) However I don't seem to be able to override the values when they are nested. Is there a nice way to do that ? E.g.
```yaml
defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    sampler:
      seed: 123
    direction: minimize
    study_name: simple_objective
    storage: null
    n_trials: 20
    n_jobs: 1

    params:
      agent:
        x: range(-5.5, 5.5, 0.5)
        y: choice(-5, 0, 5)
        z: int(tag(log, interval(1, 32)))

agent:
  x: 1
  y: 1
  z: 1
```
```python
import os
import hydra
from omegaconf import DictConfig


os.environ["HYDRA_FULL_ERROR"] = "1"
config_name = 'optuna_agent'


@hydra.main(config_path='../config/', config_name=config_name, version_base='1.2')
def optimization(cfg: DictConfig) -> float:
    # x: float = cfg.x
    # y: float = cfg.y
    # z: int = cfg.z

    x: float = cfg.agent.x
    y: float = cfg.agent.y
    z: int = cfg.agent.z
    return x**2 + y**2 + z


if __name__ == "__main__":
    optimization()
```

Thank you !

**Comment by thomashirtz** [comment]
I ended up doing something like this, but I am wondering if there is not something cleaner :

```
defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    sampler:
      seed: 123
    direction: minimize
    study_name: simple_objective
    storage: sqlite:///starter.db
    n_trials: 20
    n_jobs: 1

    params:
      x: range(-5.5, 5.5, 0.5)
      y: choice(-5, 0, 5)
      z: int(tag(log, interval(1, 32)))

x: 1
y: 1
z: 1

agent:
  x: ${x}
  y: ${y}
  z: ${z}
```
