### DISCUSSION TITLE
Working directory stopped being managed by @hydra.main() decorator

### DISCUSSION THREAD

**Discussion by CytoShimon** [facebookresearch/hydra#2580] [Q&A] [answered]
Not sure what I did, but cwd() does not change to output/...

<img width="733" alt="image" src="https://user-images.githubusercontent.com/117347078/217285945-443dfda0-81cc-4b82-93e3-239045bea594.png">

**main_config.yaml:**
```
defaults:
    - files: disease_model # set which disease model folder to extract datasets
    - _self_
paths:
    log: ./runs
    data: ${hydra:runtime.cwd}/data
params:
```

Any suggestion appreciated, thanks.
