### DISCUSSION TITLE
How to change setting for object which is inside another obejct?

### DISCUSSION THREAD

**Discussion by dvstter** [facebookresearch/hydra#2658] [Q&A] [answered]
I have solved this problem in another not so quite beautiful method. So my question is that is there any more formal method?

my directory is like this:
```
--config
    |-cfg.yaml
    --encoder
        |-resnet50.yaml
        |-resnet151.yaml
```

Any resnet50/151.yaml just like this:
```
_target_: xxx.Resnet
parameter1: 10
```

 And in my cfg.yaml, I have this:
```
defaults：
    - encoder: resnet50
agent:
    _target_: xxx.xxxAgent
    encoder: ${encoder}
```

Yeah, I defined the encoder object in the global vision, then I quoted this object in agent object's field. In fact I only need that appears in the agent object's field. So is there any better or more formal method to resolve this?
