### DISCUSSION TITLE
variable interpolation failing on diffrerent structure

### DISCUSSION THREAD

**Discussion by sebastian-bearing** [facebookresearch/hydra#2732] [Q&A] [answered]
good morning, i was wondering some help if posible on understanding why these is not working,  i have the following project structure
```raw
 ├── config/
 │   ├── parsers/
 │   │   ├── parser_1.yaml
 │   │   └── ....
 │   ├── config_1.yaml
 │   └── ....
 ├── common_steps.py
 ├── main.py
 └──  utils.py
```

some snip of the code:

`config_1`
```yaml
---
defaults:
    - _self_
    - /parsers/parser_1
parameters:
    algo: 7
```

`parser_1`
```yaml
---
_target_: utils.make_pipeline
_recursive_: False
steps_config:
  - load:
      _target_: common_steps.F1
  - transform:
      _target_: common_steps.F2
      algo: ${parameters.algo}
```
`main`
```py
@hydra.main(version_base="1.1", config_path="config", config_name=end_settings)
def my_app(cfg: DictConfig) -> None:
    print(OmegaConf.to_yaml(cfg))
my_app()
```

the end result of `outputs/../../.hydra/config.yaml` is:
```yaml
parameters:
  algo: 7
parsers:
  _target_: utils.make_pipeline
  _recursive_: false
  steps_config:
  - load:
      _target_: common_steps.F1
  - transform:
      _target_: common_steps.F2
      algo: ${parameters.algo}
```
i don't get why the `${parameters.algo}` is not overriding mi desire output is:

```yaml
parameters:
  algo: 7
parsers:
  _target_: utils.make_pipeline
  _recursive_: false
  steps_config:
  - load:
      _target_: common_steps.F1
  - transform:
      _target_: common_steps.F2
      algo: 7
```

thanks in advance and i really appreciate any help
