### DISCUSSION TITLE
What is the best Practice for Structured Configurations with Shared Callbacks in Nested Structure

### DISCUSSION THREAD

**Discussion by icedpanda** [facebookresearch/hydra#2736] [Q&A] [answered]
I am trying to set up a configuration structure using Hydra that has shared callbacks for different tasks, while still maintaining a nested structure for each task. The goal is to reduce redundancy in the configuration while preserving the hierarchical structure (`pretrain` and `finetuning` in this case).

Given the structure:
- `pretrain` and `finetuning` are two tasks
- Both tasks share common callbacks configuration like `model_summary`, `rich_progress_bar`, etc.
- There are also task-specific override for `early_stopping` and `model_checkpoint`
- Due to the complexity of the training process, I'm using multiple trainer.fit() calls. For the sake of this issue, let's assume we have two stages: pre-training and fine-tuning.

However, I've been unable to combine the usage of defaults with _self_ to achieve my desired structure. The configurations end up being outside the pretrain and finetuning namespaces. From this [tutorial](https://hydra.cc/docs/patterns/select_multiple_configs_from_config_group/), I can manage to have the nest callbacks without using defaults and `_self_` like:
```yaml
callbacks:
   pretrain:
       # some callbacks here
   fine-tuning:
      # some callbacks here
```

Ideally, I would like to have

```yaml
# callbacks/common.yaml
defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  monitor: "val/epoch_loss"
  save_last: False
  auto_insert_metric_name: False

model_summary:
  max_depth: -1

lr_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: step
```

```yaml
# callbacks/PF
defaults:
  - tasks/pretrain
  - tasks/fine-tuning
```
```yaml
#callbacks/tasks/pretrain
defaults:
 - common
 - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  monitor: "val/pretrain/epoch_loss"
  mode: "min"
  save_last: False
  auto_insert_metric_name: False
```

```yaml
#callbacks/tasks/fine_tuning
defaults:
 - common
 - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  monitor: "val/fine_tuning/acc"
  mode: "max"
  save_last: False
  auto_insert_metric_name: False
```

Given the above, how can I best structure my configurations using Hydra to achieve the desired nested structure while utilizing the power of defaults and `_self_`? Is there a recommended way or best practice for such use cases?
