### DISCUSSION TITLE
How to share configurations that are one level above the configuration using it?

### DISCUSSION THREAD

**Discussion by akkiokun** [facebookresearch/hydra#2739] [Q&A]
Hello everyone,

I have the following directory structure:

```
d-- data_loader_config
f---- dl_config.yaml
d-- pretrain_config
f---- pt_config.yaml
d-- finetune_config
f---- ft_config.yaml
main_config.yaml
```

```
# pt_config.yaml
_target_: custom.PtConfig
defaults:
  - ../data_loader_config: dl_config
```

```
# ft_config.yaml
_target_: custom.FtConfig
defaults:
  - ../data_loader_config: dl_config
```

```
# main_config.yaml
_target_: custom.MainConfig
defaults:
  - pretrain_config: pt_config
  - finetune_config: ft_config
```

What is the best way to use a shared configuration that is located outside the configuration directory where it is used? What would be a better approach for this case without any kind of duplication?

Thank you very much in advance.
