### DISCUSSION TITLE
Datetime object in hydra config

### DISCUSSION THREAD

**Discussion by nilsleh** [facebookresearch/hydra#2746] [Q&A] [answered]
I have a class that takes an argument which is a tuple of datetime objects:

```
from datetime import datetime

class MyClass():
    def __init__(self, time_range: tuple[datetime]):
        self.time_range = time_range
```

And was wondering if something like this is possible:
```
my_class:
    _target_: myApp.MyClass
   time_range:
      - _target_: datetime.datetime.strptime
        - "2020-01-01"
        - "%Y-%m-%d"
      - _target_: datetime.datetime.strptime
        - "2020-05-01"
        - "%Y-%m-%d"
```
To then run
```
from hydra.utils import instantiate
from omegaconf import OmegaConf

conf = OmegaConf.load(config_path)
my_class = instantiate(conf.my_class)
```

So far I cannot get it to work, but would appreciate any pointers how one could go about this. Thanks!

**Comment by Jasha10** [comment, marked as answer]
@nilsleh yes, this is possible using `_args_` to pass positional arguments to `datetime.datetime.strptime`:
```yaml
my_class:
  _target_: myApp.MyClass
  time_range:
    - _target_: datetime.datetime.strptime
      _args_:
      - "2020-01-01"
      - "%Y-%m-%d"
    - _target_: datetime.datetime.strptime
      _args_:
        - "2020-05-01"
        - "%Y-%m-%d"
```

Docs on `_args_`: https://hydra.cc/docs/advanced/instantiate_objects/overview/
