### DISCUSSION TITLE
Multiple default entries from the same folder

### DISCUSSION THREAD

**Discussion by ClementPinard** [facebookresearch/hydra#2753] [Q&A] [answered]
Hi sorry for the potentially silly question, I just discovered the tool (which seems to be great !)

I have a process which uses two detections. The detection itself has a set of presets

```
config.yaml
detection
 ├── easy.yaml
 └── hard.yaml
```

detection/easy.yaml
```yaml
box_threshold: 0.2
```

detection/hard.yaml
```yaml
box_threshold: 0.5
```

If I only have one detection happening, I can have have the following config.yaml :

```yaml
defaults:
- detection: easy
- _self_
```

But what if I want two detections in my process that could use a different set of defaults ? Would be possible to have something like

```yaml
defaults:
- first_detection: detection/easy  # just a pseudo syntaxe to show what I want to do
- second_detection: detection/hard
- _self_
```

The idea would be to have a redirection so that first_detection does not look into "first_detection" folder but in "detection", same for "second_detection"

For now I managed to have the desired effect by simply having a `first_detection` and a `second_detection` folders, but since the configs share the exact same structure, I feel like it would be optimal to have everything in the same folder.

**Comment by odelalleau** [comment, marked as answer]
Yes, use something like
```yaml
defaults:
- detection@first_detection: easy
- detection@second_detection: hard
- _self_
```

Relevant doc: https://hydra.cc/docs/advanced/overriding_packages/#using-a-config-group-more-than-once
