### DISCUSSION TITLE
how to properly override configs?

### DISCUSSION THREAD

**Discussion by labombatomba** [facebookresearch/hydra#2796] [Q&A]
Hi everyone!

I think my question is quite a newbie issue but it seems I struggle to understand the fundamental concept. I'm sorry for that.

Suppose I have the following config tree, where I try to run the code below given the configuration defined in configs/inference.yaml

- configs/inference.yaml
- configs/dataset/default.yaml
- configs/model/default.yaml
- configs/paths/default.yaml

```
_target_: src.datasets.SimpleDataset
_partial_: true
data_root: ${paths.data_root}
split: train
``` 

```
# @package _global_
defaults:
  - _self_
  - dataset: default.yaml
  - model: default.yaml
  - paths: default.yaml


checkpoint_path: ${paths.result_dir}/ckpt

dataset:
  split: test
``` 

```python

@hydra.main(config_path="configs", config_name="inference.yaml")
def main(cfg: DictConfig) -> None:
    
    model = hydra.utils.instantiate(cfg.model)
    dataset_constructor = hydra.utils.instantiate(cfg.dataset)
    ...

if __name__ == "__main__":
    os.environ["PROJECT_ROOT"] = Path(__file__).parent.as_posix()
    main()


``` 

The problem is, that the split key in dataset is not changed to "test". I tried the `override` keyword as well but it seems that doesn't make any difference. Hence, I curious if anyone could explain my fundamental error in thinking to me.

I'm using hydra 1.3.2.

Thanks!
