### DISCUSSION TITLE
filemode: w in in logging.FileHandler (documentation issue)

### DISCUSSION THREAD

**Discussion by pytlv** [facebookresearch/hydra#2806] [Ideas]
Hi all,
Had an issue defining a custom logger with "write mode" (clearing log file before appending).
I think that documentation should be enhanced with the following example:
```yaml
handlers:
  file_handler:
    class: logging.FileHandler
    formatter: simple
    filename: ${hydra.run.dir}/${hydra.job.name}.log
    mode: w
```

Current example:
https://github.com/facebookresearch/hydra/blob/1.3_branch/examples/configure_hydra/logging/my_app.py

From Python Official Doc:
```
logging.basicConfig(filename='example.log', filemode='w', level=logging.DEBUG))
```

I found previous issue:
https://github.com/facebookresearch/hydra/issues/1149

Let me know how it's best to request such a doc enhancement.
Many thanks from Tel Aviv!
