### DISCUSSION TITLE
Overriding a default for config group from the command line, when the value is also defined in the config file.

### DISCUSSION THREAD

**Discussion by ysavtchouk-pf** [facebookresearch/hydra#2812] [Q&A]
Hi all!

We have the following structure

config.yaml file - our root file
Contents:

```
defaults:
  - _self_
  - experiment: null

```

Experiment files:
configs/experiment/stage-one.yaml

Contents:

```
defaults:
  - /configuration_source: base

configuration_source:
  vmec_file_path: starfinder/inputs/input.nfp2_QA
```

Configuration source file:
configs/configuration_source/configuration1.yaml:

```
vmec_file_path: starfinder/inputs/input.nfp2_QA
```
I am trying to override the configuration_source with the command line

`my-binary experiment=stage-one  configuration_source=configuration1`

However, this does not work, since  vmec_file_path: starfinder/inputs/input.nfp2_QA has a priority.

If I instead define in configs/experiment/stage-one.yaml
```
defaults:
  - _self_
  - /configuration_source: base

configuration_source:
  vmec_file_path: starfinder/inputs/input.nfp2_QA
```
Then vmec_file_path: starfinder/inputs/input.nfp2_QA will always be overridden. E.g. running `my-binary experiment=stage-one` will take values from base.

 I feel like I am missing something here. Is there a proper way to achieve that the user input takes precedence, still using config groups?

thank you in advance!

**Comment by odelalleau** [comment]
If I understand correctly, what you're trying to do is somewhat unusual, since the `configuration_source=configuration1` that you want to provide on the command line should not behave the same as the `configuration_source: ...` in your config (because the latter is supposed to get overridden by the content of `stage-one.yaml`)

I'm not sure if there's a better way, but one workaround is to treat them as different config groups (since they are behaving differently). Something like this (not tested with your specific configs):
```yaml
defaults:
  - /configuration_source: base
  - _self_
  - optional /configuration_source_override@configuration_source: null

configuration_source:
  vmec_file_path: starfinder/inputs/input.nfp2_QA
```
and then use on the command line `configuration_source_override=configuration1`.

You can do a `ln -s configuration_source configuration_source_override` to be able to re-use the exact same configs.
