### DISCUSSION TITLE
Multiple configs from a config group with required fields

### DISCUSSION THREAD

**Discussion by tillwenke** [facebookresearch/hydra#2821] [General]
Imagine the following setting. We want to create a config like this:
```
server:
  site:
    fb:
      domain: facebook.com
      x: 10
    google:
      domain: google.com
      x: 10
  host: localhost
  port: 443
```
with .yaml files similar to here https://hydra.cc/docs/patterns/select_multiple_configs_from_config_group/.

How can I tell the configs (fb and google) from the site config group to always have the field `x` with the default value `10`. So it even appears in the config if I do not explicitly mention it in the respective yamls. I should as well be able to set it explicitly in the yaml.

Currently we are setting this kind of required fields in our python script which works but I thought there might be a hydra-way to do it.

Cheers
