### DISCUSSION TITLE
How to validate my yaml file using hydra shema?

### DISCUSSION THREAD

**Discussion by HydrogenSulfate** [facebookresearch/hydra#2827] [Q&A] [answered]
I prefer to use hydra with omegaconf cuz it's convenient to run multiple experiments. And I now want to validate the arguments in given yaml file by checking them and raise error if not correct or of wrong type.
For certain reason there are some arguments, except fixed args, not need to be checked(called "free args"), because name and number of "free args" may varies in different yaml file.

So how can I validate the fixed args and do not validate the free args using hydra + omegaconf with dataclass as schema? Suppose my yaml file is below:

``` yaml
mode: train # fixed arg, need to be validate
seed: 42  # fixed arg, need to be validate

scope:
   a: 1 # free arg, no need to be validate
   b: 2 # fixed arg, need to be validate
```

If this can not be achieved, is there any other method better than writting check function for each fixed arg?
Can anyone give an example code? Thanks a lot.
