### DISCUSSION TITLE
Composition question

### DISCUSSION THREAD

**Discussion by alexcoca** [facebookresearch/hydra#2866] [Q&A]
I was wondering if someone could help me understand some weird behaviour I am observing.

I have a trainer configured by `hydra` as follows:

```
├── finetuning
│   ├── data_preparation
│   ├── trainer
│   │   ├── callbacks
│   │   │   └── temp.yaml
│   │   ├── constraints
│   │   │   └── model.yaml
│   │   ├── data_colator
│   │   │   └── seq2seq.yaml
│   │   ├── model_config
│   │   │   ├── config
│   │   │   │   └── model_config.yaml
│   │   │   ├── model
│   │   │   │   └── model.yaml
│   │   │   ├── tokenizer
│   │   │   │   └── tokenizer.yaml
│   │   │   └── model.yaml
│   │   ├── optimizer
│   │   │   └── adam.yaml
│   │   ├── preprocessor
│   │   │   └── standard.yaml
│   │   ├── scheduler
│   │   │   └── learning_rate.yaml
│   │   ├── trainer_args
│   │   │   ├── inference.yaml
│   │   │   └── training.yaml
├── train.yaml
└── inference.yaml
```

NB: names in the yaml below may not match the tree above as that's ChatGPT generated to give the rough structure, not the full tree.

```yaml
# inference.yaml
defaults:
  - trainer/trainer_args@trainer_args: inference
  - trainer/model_config@_here_: model
  - trainer/preprocessor@preprocessor: default
  - trainer/data_collator@data_collator: seq2seq
  - trainer/callbacks@callbacks: temp
  - project/toolbox@data_preparation.text2text_conversion.intent_fmt.config.toolbox: default
  - data_preparation: online_multiline
  - trainer/constraints@constraints: model
  - _self_


#  set to abs path to checkpoint dir (ending in
# `checkpoint-*`) of the checkpoint to be decoded
model_name_or_path: ???
output_dir: ${model_name_or_path}
# nb: this is not used if `predicted_history_inference = true`, for now.
# path to the test.parquet file (for next action prediction)
test_file: ???
checkpoint: ???

config:
  pretrained_model_name_or_path: ${model_name_or_path}
# this config group can be used to override any argument
# to the huggingface `Trainer`
trainer_args:
  output_dir: ${output_dir}
  test_file: ${make_absolute:${test_file}}
  hyps_dir: ${root:hyps}
  metrics_dir: ${root:metrics}

predicted_history_inference: false
split: 'test'
# inference data version. Used to load
# the dialogue history files that are used
# for transcript generationq
version: ???
data_preparation:
  data_path: ${root:data/finetuning/sgd/${version}/${split}}
  dataset_builder:
    split: ${split}

log_prefix: "predict_${checkpoint}"
hydra:
  run:
    dir: ${output_dir}
  job_logging:
    handlers:
      file:
        filename: ${log_prefix}_${trainer_args.data_variant}_${hydra.job.name}.log
  # allows us to compose the project interpreter
  # toolbox config in `defaults`
  searchpath:
    - file://${root:src/project/configs}
```

Inside `constraints/model.yaml` I have:

```yaml
_recursive_: false
model: ${model}
tokenizer:
  _target_: ${tokenizer._target_}
  pretrained_model_name_or_path: ${model.pretrained_model_name_or_path}
  cache_dir: ${tokenizer.cache_dir}
  revision: ${tokenizer.revision}

preprocessor: ${preprocessor}
```

When I print my config I get, as expected, something like:

```constraints:
  _recursive_: false
  model:
    _target_: transformers.AutoModelForSeq2SeqLM.from_pretrained
    pretrained_model_name_or_path: ...
    cache_dir: /Users/alexandrucoca/work/dev/pytod/cache
    revision: main
  tokenizer:
    _target_: transformers.AutoTokenizer.from_pretrained
    pretrained_model_name_or_path: /Users/alexandrucoca/work/dev/....
    cache_dir: /Users/alexandrucoca/work/dev/pytod/cache
    revision: main
  preprocessor:
    _target_: pytod.preprocessor.Preprocessor
    tokenizer:
      _target_: transformers.AutoTokenizer.from_pretrained
      pretrained_model_name_or_path: /Users/alexandrucoca/work/dev/...
      revision: main
      cache_dir: /Users/alexandrucoca/work/dev/pytod/cache
    max_source_length: 4096
    max_target_length: 128
    padding: false
    ignore_pad_token_for_loss: true
    num_proc: 8
    load_from_cache_file: true
    input_prefix: ''
    debug: true
```

However, if I pass `constraints.model.pretrained_model_name_or_path=google/flant5 in the CLI I get

```bash
hydra.errors.ConfigCompositionException: Could not override 'constraints.model.pretrained_model_name_or_path'.
To append to your config use +constraints.model.pretrained_model_name_or_path=google/flant5
```

This is unexpected. If I do as told, I get:

```hydra.errors.ConfigCompositionException: Could not append to config. An item is already at 'constraints.model.pretrained_model_name_or_path'.
Either remove + prefix: 'constraints.model.pretrained_model_name_or_path=google/flant5'
Or add a second + to add or override 'constraints.model.pretrained_model_name_or_path': '++constraints.model.pretrained_model_name_or_path=google/flant5'
```

Adding the second + is not what we want:

```yaml
constraints:
  _recursive_: false
  model:
    pretrained_model_name_or_path: google/flant5
```

I think that this is happening because I am trying to override a pretrained_model_name_or_path twice: once by attempting to change it inside constraints.model.pretrained_model_name_or_path and once by specifying the pretrained_model_name_or_path for the actual model (which the constraints config group references via interpolation) itself.

My intention ideal solution would be to compose `model` , `tokenizer` and `preprocessor` as defaults and be able to override them as appropriate, but I could not figure out how to specify the defaults list correctly inside `constraints/model.yaml`. My best go was:

```yaml
defaults:
  - finetuning/trainer/model@model: model
```
 
 but this lead to 
 
 ```
 hydra.errors.MissingConfigException: In 'trainer/constraints/model': Could not find 'trainer/constraints/finetuning/trainer/model/model'
Config search path:
	provider=hydra, path=pkg://hydra.conf
	provider=main, path=file:///Users/alexandrucoca/work/dev/?/src/?/configs/finetuning
	provider=hydra.searchpath in main, path=file:///Users/alexandrucoca/work/dev/?/src/?/configs
	provider=schema, path=structured://
```

It seems like the config specified is sought only in the folder where the config is? Is there a way to get around this @Jasha10 ?
