### DISCUSSION TITLE
Add a _scope_ keyword for instantiation to specify a root module

### DISCUSSION THREAD

**Discussion by ryan-minato** [facebookresearch/hydra#2882] [Ideas]
Perhaps a scope keyword could be added to specify a common root module for a dictionary and its sub-dictionaries, similar to what is [done in mmengine](https://mmengine.readthedocs.io/en/latest/advanced_tutorials/cross_library.html#use-detector-across-libraries:~:text=To%20prevent%20adding%20prefix%20to%20all%20of%20the%20submodules%20manually%2C%20the%20_scope_%20keyword%20is%20introduced.%20When%20the%20_scope_%20keyword%20is%20added%20to%20the%20config%20of%20a%20module%2C%20all%20submodules%E2%80%99%20scope%20will%20be%20changed%20by%20the%20_scope_%20keyword.%20Here%20is%20an%20example%20config%3A).

One quick (but maybe ugly) implementation I can think of is to search for all `_scope_ `when reading the configuration and then prepend it to the target of the same level and sub-level.

## e.g.
the following two configurations would be equivalent:

**conf1:**
``` yaml
model:
_target_: pkg.model.llama.LlamaModel
attn_module:
    _target_: pkg.model.llama.MyAttention
    hidden_size: 32
position_embeddings:
    _target_: pkg.model.llama.MyRotaryEmbedding
    max_position_embeddings: 2048
num_hidden_layers: 32
...
```

**conf2:**
``` yaml
model:
_scope_: pkg.model.llama
_target_: LlamaModel
attn_module:
    _target_: MyAttention
    hidden_size: 32
position_embeddings:
    _target_: MyRotaryEmbedding
    max_position_embeddings: 2048
num_hidden_layers: 32
...
```
