### DISCUSSION TITLE
Including a config file next to the current one as field value

### DISCUSSION THREAD

**Discussion by mainrs** [facebookresearch/hydra#2896] [Q&A]
I have a class called `DataProvider` that requires two arguments `first` and `second`. I have the following structure:

```
|
|-- config.yaml
|--some/
		|
		|-- folder
				 |-- data_provider1.yaml
				 |-- data_provider2.yaml
```

with 

```yaml
# data_provider1.yaml
_target_: my.python.package.LocalDataProvider
first: first-value
second: second-value

# data_provider2.yaml
_target_: my.python.package.DelegatingDataProvider
data_provider: <include the values from data_provider1.yaml here>
```

I do not know how to accomplish this. Is this possible at all? I do not want to have to copy-paste the config content into the other file; it's rather large and hard to maintain.

The final config should look like this:

```yaml
_target_: my.python.package.DelegatingDataProvider
data_provider:
    _target_: my.python.package.LocalDataProvider
    first: first-value
    second: second-value
```
