### DISCUSSION TITLE
override default config to create multiple instances with different arguments

### DISCUSSION THREAD

**Discussion by jayleicn** [facebookresearch/hydra#2912] [General]
Hi Hydra experts! 

I have a config that set arguments for a dataloader
```
dataloader:
   load_image: true
   load_text: true
   other_arguments ...
```
In my final config, I would have two dataloaders share very similar arguments except the value of `load_image`, one is true and another is false, i.e.,
```
dataloader_1:
   load_image: false
   load_text: true
   other_arguments ...

dataloader_2:
   load_image: true
   load_text: true
   other_arguments ...
```
I can directly create dataloader_1 and _2 by coping the shared parts, but since the dataloader config is quite lengthy (40+lines), this results in a lot of duplications. Is there a way to create a shared config `dataloader`, and have `_1` and `_2` inherit it and only override the value `load_image`?
