### DISCUSSION TITLE
How to support nested list with config from sub-directories

### DISCUSSION THREAD

**Discussion by maheshkelkar** [facebookresearch/hydra#2937] [General]
I want to add config, with nested lists. Outer list is called pods. Each pod has list called containers (i.e. inner list). Instead of duplicating pods and containers config, I want to use it from their individual files in the sub-directories. I am not able to make it work. 

I am using: hydra-core==1.3.2.

This blog post [here](https://hydra.cc/docs/patterns/select_multiple_configs_from_config_group/) uses dict to make lists work. 

I couldn't find any recommendations or ways to make this work. Thank you in advance for ideas/thoughts/comments. 

The directory structure for `example/conf`
```
├── config.yaml
└── pods
    ├── basic.yaml
    ├── plusone.yaml
    └── containers
        ├── foo.yaml
        ├── bar.yaml
        └── baz.yaml
```
config.yaml
```
defaults:
  - pods:
    - basic
    - plusone
```
pods/basic.yaml. I need to define "basic" here as mentioned in the blog post; or the config for plusone overwrites it
```
defaults:
  - containers:
    - foo
    - bar
basic:
  animal: cat
  containers: ${containers}
```
pods/plusone.yaml. This doesn't work. It simply adds config for "baz" to the overall "site" list (or dict). 
```
defaults:
  - containers:
    - baz
plusone:
  animal: dog
  containers: ${containers}
```
pods/containers/foo.yaml
```
foo:
    color: brown
```
In the end I want to be able to override these pods and containers from the command line
E.g.
```
python -m example "pods=[plustwo]" "pods/basic/containers=[bar]"
