### DISCUSSION TITLE
Scoped defaults

### DISCUSSION THREAD

**Discussion by Divelix** [facebookresearch/hydra#2994] [Q&A]
I want to reuse augmentations/transforms configs for multiple datasets in torch ConcatDataset. For single dataset it would look the following:
```yaml
defaults:
  - transforms: my_aug
_target_: src.datasets.MyDataset
```
But for ConcatDataset I would need list of datasets:
```yaml
defaults:
  - transforms@tf1: my_aug1
  - transforms@tf2: my_aug2
_target_: torch.utils.data.ConcatDataset
datasets:
  - _target_: src.datasets.MyDataset
    transforms: ${...tf1}
  - _target_: src.datasets.MyDataset
    transforms: ${...tf2}
```
This implementation for ConcatDataset forks fine in itself, but it breaks when used in recursive instantiation, because it returns not just "_target_", but ["tf1", "tf2", "_target_"] instead.

Intuitive solution to that problem would be scoped defaults that syntactically could be defined by underscore so my config looked like:
```yaml
defaults:
  - transforms@_tf1: my_aug1
  - transforms@_tf2: my_aug2
_target_: torch.utils.data.ConcatDataset
datasets:
  - _target_: src.datasets.MyDataset
    transforms: ${_tf1}
  - _target_: src.datasets.MyDataset
    transforms: ${_tf2}
```

May be I missed smth in docs and this behaviour is already achievable with current hydra functionality, point me to the right place then, please.
