### DISCUSSION TITLE
Can Hydra support referencing and merging values with overrides within a single config file?

### DISCUSSION THREAD

**Discussion by taillandierv** [facebookresearch/hydra#2997] [Q&A]
Hello Hydra Team,

I am working with Hydra and would like to ask if it's possible to reference a key within the same config file and then override or extend its values. Specifically, I'm trying to reference one section of a configuration and then extend or modify it in the same file.

**Desired Behavior**
Consider the following use case where I want to:

- Define a key key2.
- Reference key2 and assign it to another key (key3).
- Modify a specific field inside key3, overriding it as needed.

Here is my example configuration in a single config file:
```yaml
key2:
  subkey1: subvalue1
  subkey2:
    subsubkey1: subsubvalue1
    subsubkey2: subsubvalue2
    
key3: 
  ${key2}
  subkey2:
    subsubkey2: a_different_value
```

I have tried using yaml vanilla features like:
```yaml
key2: &key2
  subkey1: subvalue1
  subkey2:
    subsubkey1: subsubvalue1
    subsubkey2: subsubvalue2

key3: 
  <<: *key2
  subkey2:
    subsubkey2: a_different_value
  
```

But it wont deep merge dictionaries as Hydra does for nested configurations.
In this example I will loose `subsubkey1`

The current solution I have is something like:
```yaml
key2: &key2
  subkey1: subvalue1
  subkey2: &subkey2
    subsubkey1: subsubvalue1
    subsubkey2: subsubvalue2

key3: 
  <<: *key2
  subkey2:
    <<: *subkey2
    subsubkey2: a_different_value
  
```
Which become difficult when nested dictionaries are deep.

Is there any solution for that ?
Thank you a lot!
Valentin
