### ISSUE TITLE
default overrides in config.yaml

### ISSUE THREAD

**Issue by ferrine** [facebookresearch/hydra#1009]
# default overrides in config.yaml

Support more precise defaults in configuration. Like this

```yaml
optimizer:
    lr: 1e-3
defaults:
    - dataset: imagenet
    - model: alexnet
      optional: true
    - optimizer: nesterov
```

## Motivation
I find it problematic to track which configs I came upon after several runs. And the way I thought to put my results together was to add a couple of overrides in default config like that

```yaml
optimizer:
    lr: 1e-3
defaults:
    - dataset: imagenet
    - model: alexnet
      optional: true
    - optimizer: nesterov
```
I expected this config will load the defaults and the override the learning rate by 1e-3. 
Eventually, I found that the implementation of the default config loader [does not support that](https://github.com/facebookresearch/hydra/blob/7e23ab9aac159c70cfef850307eca34807a1080c/hydra/_internal/config_loader_impl.py#L841-L888). It only reads the defaults key and that's it.

## Pitch

I'd like to be able to add config overrides in yaml file, instead of command line. I got used to the command line, it't cool, but hard to keep track of. Is it an anti-pattern for hydra and I can do it with ease persistently in a different way? Anyway, amazing config manager, willing to make it even better.

I can open a pull request, but it will require some guidance, I have not implemented the solution yet.

**Comment by omry** [comment]
This is a duplicate of #326 which is planned for Hydra 1.1.
For now you can add a second config file to do that:
config.yaml:
```yaml
defaults:
    - dataset: imagenet
    - model: alexnet
      optional: true
    - optimizer: nesterov
    - my_overrides
```

my_overrides.yaml:
```yaml
# @pacakge _global_
optimizer:
    lr: 1e-3
```
