### ISSUE TITLE
Value interpolation breaks in defaults when indices change

### ISSUE THREAD

**Issue by tholiao** [facebookresearch/hydra#104]
```yaml
defaults:
- hydra/hydra_logging: default
- hydra/job_logging: default
- hydra/launcher: basic
- hydra/sweeper: basic
- env: cartpole
- dynamics_model: p
- env/: ${defaults.0.env}/dynamics_model/${defaults.1.dynamics_model}
- optimizer: random
- env/: ${defaults.0.env}/optimizer/${defaults.3.optimizer}
- traj: simple
```
