### ISSUE TITLE
Using fairtask with a config in the same file

### ISSUE THREAD

**Issue by bamos** [facebookresearch/hydra#106]
I'd like to keep all of my config in a single file instead of separate files and I'm having an issue using fairtask. I've slightly modified the sweep example to this:

```python
#!/usr/bin/env python3

import logging

import hydra

log = logging.getLogger(__name__)

import sys
from IPython.core import ultratb
sys.excepthook = ultratb.FormattedTB(mode='Verbose',
    color_scheme='Linux', call_pdb=1)

@hydra.main(config_path="config.yaml")
def experiment(cfg):
    log.info(cfg.pretty())


if __name__ == "__main__":
    experiment()
```

```yaml
hydra:
  launcher:
    class: hydra_plugins.fairtask.FAIRTaskLauncher
    params:
      # debug launching issues, set to true to run workers in the same process.
      no_workers: false
      queue: slurm
      queues:
        local:
          class: fairtask.local.LocalQueueConfig
          params:
            num_workers: 2
        slurm:
          class: fairtask_slurm.slurm.SLURMQueueConfig
          params:
            num_jobs: ${hydra.job.num_jobs}
            num_nodes_per_job: 1
            num_workers_per_node: 1
            name: ${hydra.job.name}
            maxtime_mins: 4320
            partition: learnfair
            cpus_per_worker: 10
            mem_gb_per_worker: 64
            gres: 'gpu:1'
            log_directory: ${hydra.sweep.dir}/.slurm
            output: slurm-%j.out
            error: slurm-%j.err
```

However when I run this I get the error:

```python
TypeError: __init__() got an unexpected keyword argument 'no_workers'
> /private/home/bda/repos/hydra/hydra/utils.py(48)instantiate()
     46         merged_params = OmegaConf.merge(params, OmegaConf.create(kwargs))
     47         merged_params.__dict__['parent'] = params.__dict__['parent']
---> 48         return clazz(*args, **merged_params)
     49     except Exception as e:
     50         log.error("Error instantiating {} : {}".format(config["class"], e))
```

And I think this issue is coming from somewhere overwriting the fairtask class I put in for `hydra.launcher.class` with the `BasicLauncher`:

```python
TypeError: __init__() got an unexpected keyword argument 'no_workers'
> /private/home/bda/repos/hydra/hydra/utils.py(48)instantiate()
     46         merged_params = OmegaConf.merge(params, OmegaConf.create(kwargs))
     47         merged_params.__dict__['parent'] = params.__dict__['parent']
---> 48         return clazz(*args, **merged_params)
     49     except Exception as e:
     50         log.error("Error instantiating {} : {}".format(config["class"], e))

ipdb> args
config = {'class': 'hydra._internal.core_plugins.basic_launcher.BasicLauncher', 'params': {'no_workers': False, 'queue': 'slurm', 'queues': {'local': {'class': 'fairtask.local.LocalQueueConfig', 'params': {'num_workers': 2}}, 'slurm': {'class': 'fairtask_slurm.slurm.SLURMQueueConfig', 'params': {'num_jobs': '${hydra.job.num_jobs}', 'num_nodes_per_job': 1, 'num_workers_per_node': 1, 'name': '${hydra.job.name}', 'maxtime_mins': 4320, 'partition': 'learnfair', 'cpus_per_worker': 10, 'mem_gb_per_worker': 64, 'gres': 'gpu:1', 'log_directory': '${hydra.sweep.dir}/.slurm', 'output': 'slurm-%j.out', 'error': 'slurm-%j.err'}}}}}
args = ()
kwargs = {}
```
