### ISSUE TITLE
Inheriting defaults from a base config

### ISSUE THREAD

**Issue by myleott** [facebookresearch/hydra#1168]
# ❓ Questions/Help

**In Hydra 1.0.x**, is it possible to have a config that inherits defaults from a base config?

This does now seem possible in 1.1.x, using the following structure:

```yaml
# base_config.yaml
defaults:
  - db: mysql
```
```yaml
# my_config.yaml
defaults:
  - base_config
  - _self_
db:
  user: myleott
```

```
$ python my_app.py --config-name my_config
db:
  driver: mysql
  user: myleott
  pass: secret
```

I'm just wondering if it's possible to achieve similar behavior in the stable release (1.0.x)?

**Comment by omry** [comment]
You can emulate to some extent it in 1.0 by splitting your config into two files:
```yaml
# my_config.yaml
defaults:
  - base_config
  - _self_
db:
  user: myleott
```

becomes:
```yaml
# my_defaults.yaml
defaults:
  - base_config
  - my_config
```

```yaml
# my_config.yaml
db:
  user: myleott
```

By the way, I am still working the defaults list in 1.1 very actively. I do not recommend it for anything but exploration of what is to come at this stage.
