### ISSUE TITLE
[Question] Composition order of the content of the primary config in Hydra 1.0

### ISSUE THREAD

**Issue by greeneggsandyaml** [facebookresearch/hydra#1185]
Hello, thank you for this great config library! I had a question about it and I wasn't sure where to post it, so I am asking here. I am sure that this sort of thing has been addressed, but I haven't found it in the docs. 

I am confused about the following behavior. I have two config files, one of which is a default for the other. However, I cannot seem to override the default config in the main config. For example:

```
####### base/base.yaml #######
# @package _global_
x: 4

####### main.yaml #######
# @package _global_
defaults:
  - base: base
x: 5

####### app.py #######
import hydra
from omegaconf import OmegaConf

@hydra.main(config_name='main')
def main(cfg):
    print(OmegaConf.to_yaml(cfg))
```

Here if I run `python app.py`, I get: 
```
x: 4
```
I would expect to get `x: 5` because of the line in `main.yaml`, but it doesn't seem to override the imported default (???). Is this expected behavior? If so, why? This seems just incredibly confusing.

**Comment by omry** [comment]
Hi @greeneggsandyaml.
There are two different use cases someone might want here:
1. defaults override this file (bottom up construction)
2. this file overrides defaults (fine tuning of the result of the defaults).

In Hydra 1.0, the behavior is 1.
First of all, to see this you can run your app with --info and see the composition trace.
you will notice that your main config is in between hydra configs and configs you are adding in the defaults.

(Allowing your config to override Hydra configs, but allowing your defaults to override your config).

To be able to override things from your defaults list in Hydra 1.0, you can append another file to the list.
for example:
```yaml
####### base/base.yaml #######
# @package _global_
x: 4

####### overrides.yaml #######
x: 5

####### main.yaml #######
# @package _global_
defaults:
  - base: base
  - overrides
```

Hydra 1.1 will support specifying the composition order of "this" config relative to the defaults list with a new `_self_` keyword.
You can actually try it in master now.
```yaml
####### base/base.yaml #######
# @package _global_
x: 4

####### main.yaml #######
# @package _global_
defaults:
  - base: base
  - _self_
x: 5
```
Work on the defaults list is still going on in Hydra 1.1 (see #1170), but that feature should be stable.
I am going to evaluate a transition from the current default behavior:
```yaml
defaults:
  - _self_ # added implicitly if not present
  - foo
```
to
```yaml
defaults:
  - foo
  - _self_ # added implicitly if not present
```
This will take some serious consideration because changing it is a breaking change and there ARE use cases where bottom up construction makes sense.
Because the default list choices can be overridden from the outside (base=base2 in the command line), you may not actually know enough about the structure of the base choice when you are writing your main config file (e.g: what if base2 does not have an x parameter?)

Hope this helps.
