### ISSUE TITLE
[Bug] Running a python exec as module doesn't support overriding config with flags.

### ISSUE THREAD

**Issue by kwanUm** [facebookresearch/hydra#1194]
# 🐛 Bug
## Description
Running a python exec as module doesn't support overriding config with flags.

python -m deployment.server_appio.server_webrtc rtc_server.port=9090 --> Doesn't override rtc_server.port param
python  deployment/server_appio/server_webrtc.py rtc_server.port=9092  --> Overides rtc_server.port param successfully

## Checklist
- [ ] I checked on the latest version of Hydra - 1.0.4

**Comment by omry** [comment]
This works for me in on built-in examples:
```
omry@Coronadev:~/dev/hydra/examples/tutorials/basic/your_first_hydra_app/5_defaults$ python -m my_app db.driver=foo
db:
  driver: foo
  user: omry
  pass: secret
```

Please provide a minimal repro.
