### ISSUE TITLE
[Feature Request] Access relative attributes

### ISSUE THREAD

**Issue by yartem** [facebookresearch/hydra#1220]
# 🚀 Feature Request

Hey! I'm using hydra as a configuration for my MLOps project, and I usually need to address some elements that are deeply nested but close to current element. For example, consider the following config:
```
job:
  volumes:
    ...
    results:
      ...
      paths:
        config_path: path/to/config
        config_name: ${job.volumes.results.paths.config_path}/run.yaml
```
Here, the element `job.volumes.results.paths.config_name` wants to access the relative element `config_path`, and we need to define the whole path `${job.volumes.results.paths.config_path}` whereas it would be shorter (and more readable) to define it as a relative element, for example: `${.config_path}`.

I realize there are some problems with this notation:
1. it might be not obvious what it means,
2. if we follow python packaging analogy, then `${..element}` should mean "level-up element", or `${...element}` - "2 times level-up element", which perhaps is even less obvious. Or not? :thinking: 

Let's discuss if this feature is an over-complication or a handy thing.
