### ISSUE TITLE
[Feature Request] Support for computed fields based on other fields

### ISSUE THREAD

**Issue by monney** [facebookresearch/hydra#1286]
# 🚀 Feature Request
First off. Thank you for creating Hydra, it is much cleaner and more maintainable than either argparse or configuring things directly as function parameters. It has saved me a lot of time during my research.

I would like the ability to set the value of one config value to that of another, potentially in an unrelated file. Perhaps even a simple expression based on that value. 

## Motivation
Here's a specific situation I deal with. I have configuration structure which looks something like this:

```
conf
├── config.yaml
├── data
│   └── image_classification_data.yaml
├── model
│   ├── resnet.yaml
│   └── scheduler
│       └── cosine.yaml
└── trainer
    ├── distributed.yaml
    └── single_gpu.yaml
```

The cosine scheduler depends on the number of training steps to be taken in a variable called `T_max`. I define the epochs and number of gpus in the trainer. I define batch size in the data_loader config.  The value of `T_max` can be determined completely statically from these other values, and I would like them to vary together, if epochs or distributed mode is used for example.

## Pitch

**Describe the solution you'd like**
Within the cosine scheduler I would ideally like to be able to write something like this:
`T_max: ${parent.parent.trainer.epochs}`

Alternatively something like this:
`T_max: ${global.trainer.epochs}`

as a stretch goal, something computed in a simple expression:
`T_max: ${global.trainer.epochs/(global.trainer.n_gpus * global.data.batch_size)}`

**Describe alternatives you've considered**
- Specializing a config doesn't seem like it would work in any non-cumbersome way
- I've thought about writing a custom OmegaConf resolver but I'm not sure how I would access global config scope
- Currently what I do is I leave `T_max` as a missing value and then either pass it in as a command line arg or I write a custom wrapper to be the `__target__` of each scheduler (or other object which requires this) and compute it at runtime there.

Things would be much cleaner with this feature because adding a new scheduler, for example, reduces to just creating a single new file with no code changes needed, and you can just call `instantiate` to directly create the scheduler since all config is self-contained. Otherwise you need a new wrapper function for each object which requires these kinds of dependencies.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
yes

**Comment by omry** [comment]
Hi, thanks for the kind words.
What you are asking for is called interpolation.

[OmegaConf](https://github.com/omry/omegaconf), the underlying configuration library for Hydra supports what you are asking for already.
I strongly suggest that you go over the [OmegaConf docs](https://omegaconf.readthedocs.io/en/2.0_branch/) or or [slides](https://docs.google.com/presentation/d/e/2PACX-1vT_UIV7hCnquIbLUm4NnkUpXvPEh33IKiUEvPRF850WKA8opOlZOszjKdZ3tPmf8u7hGNP6HpqS-NT5/pub?start=false&loop=false&delayms=3000&slide=id.p) to learn about it (It's well worth your time).

Interpolations are also covered briefly in the [Basic tutorial](https://hydra.cc/docs/tutorials/basic/your_first_app/using_config).

As for arithmetic expressions:
There is a [feature request](https://github.com/omry/omegaconf/issues/91) to support it and hopefully it will eventually be supported in some form.

**Comment by monney** [comment]
This is awesome. I didn’t realize interpolations were as robust as they are. In my testing programs I was printing out the objects, hence not access the properties, so didn’t realize it would work.

**Comment by monney** [comment]
Closing due to request for existing feature

**Comment by omry** [comment]
Yup, this is often confusing people.
When you print the object it shows the interpolation without resolving it (resolving by default would mean that you could not print an object with an a bad interpolation (that points to an invalid path).

You can convert it to a yaml and resolve it with `OmegaConf.to_yaml(cfg, resolve=True)`.

By the way:
Interpolations can also point to nodes, not just values:

```yaml
a:
  b: 10
  c :20

z: ${a}
```

**Comment by monney** [comment]
Thanks again. I’ll  be sure to go through the OmegaConf docs

**Comment by Waerden001** [comment]
> Hi, thanks for the kind words.
> What you are asking for is called interpolation.
> 
> [OmegaConf](https://github.com/omry/omegaconf), the underlying configuration library for Hydra supports what you are asking for already.
> I strongly suggest that you go over the [OmegaConf docs](https://omegaconf.readthedocs.io/en/2.0_branch/) or or [slides](https://docs.google.com/presentation/d/e/2PACX-1vT_UIV7hCnquIbLUm4NnkUpXvPEh33IKiUEvPRF850WKA8opOlZOszjKdZ3tPmf8u7hGNP6HpqS-NT5/pub?start=false&loop=false&delayms=3000&slide=id.p) to learn about it (It's well worth your time).
> 
> Interpolations are also covered briefly in the [Basic tutorial](https://hydra.cc/docs/tutorials/basic/your_first_app/using_config).
> 
> The syntax for interpolation is as follows:
> 
> ```yaml
> foo: 10
> bar: ${foo}
> zoo: ${a.b}
> a:
>   b: 20
>   c : ${foo}
> ```
> 
> Interpolation is evaluated lazily (on access, so it cleanly supports interpolating across different config files (unlike yaml anchors).
> As of Hydra 1.0 (which uses OmegaConf 2.0), interpolations are absolute. You always have to specify the full node path.
> OmegaConf 2.1 (which will be released with Hydra 1.1) adds relative interpolation:
> 
> ```yaml
> x: 20
> foo:
>   a: 10
>   b: ${.a}
>   c: ${..x}
> ```
> 
> As for arithmetic expressions:
> There is a [feature request](https://github.com/omry/omegaconf/issues/91) to support it and hopefully it will eventually be supported in some form.

Can you explain more how to use interpolation across different files?  As mentioned in the original question, to achieve something like ```T_max: ${parent.parent.trainer.epochs}```, it seems the suggested syntax ```{..trainer.epochs}``` (or something similar) doesn't get the content of the trainer.yaml file. I must misunderstand something here, would you be so nice to clarify a little bit more? Thanks!

**Comment by omry** [comment]
Interpolations are operating on the config object, not on files.
Read the docs of OmegaConf to learn about them.

**Comment by Waerden001** [comment]
I've read the docs and have been experimenting a bit. Specifically, you mentioned in the previous answer that
> Interpolation is evaluated lazily (on access, **so it cleanly supports interpolating across different config files** (unlike yaml anchors).

After some experiments, I can reference to certain values in ```config.yaml``` file from ```trainer.single_gpu.yaml``` (as in the original problem of this page). Is there a way to "import" certain content in one config file to another? e.g. interpolating in ```distributed.yaml``` content of   ```single_gpu.yaml```?

**Comment by omry** [comment]
you can use interpolation of nodes.
file1.yaml:
```yaml
a: 
  b: 1
  c: 2
```

file2.yaml:
```yaml
thing:
  a: ${a}
```

Assuming the config object looks like this, accessing `thing.a` will be the same as accessing a.
```yaml
a: 
  b: 1
  c: 2
thing:
  a: ${a}
```

Another mechanism is to use the Defaults List.
This is too wide of a subject to cover in a comment.
Hydra 1.1 is much more powerful in that regard can probably support what you need (and more).
You can learn about it in those links:
- https://hydra.cc/docs/next/advanced/defaults_list/
- https://hydra.cc/docs/next/advanced/overriding_packages/

**Comment by alexcoca** [comment]
@omry First, thanks for your brilliant work. I think it helps us think a bit more clearly about how to write machine learning code.

I was trying to use the interpolation feature as well and stumbled into something I could not figure out and thought of putting it here so that others can benefit too.

I am hoping to use hydra to instantiate a list of functions from a library I am developing. My config file looks a bit like this:

```yaml
filter_package: my_package.decoder_filters
rules:
  - _target_ : "${..filter_package}.has_english_language"
  - _target_: "${..filter_package}.obeys_len_constraints"
    max_len_ratio_difference: 0.4
```

I was thinking to use the `filter_package` key to make the target functions name shorter but for some reason I get the following error:

```bash
omegaconf.errors.InterpolationKeyError: Interpolation key 'filter_package' not found
```

Any idea why this is the case? Is there a syntax insight I am missing or is interpolation not allowed in this case?

Thank you in advance.

**Comment by Jasha10** [comment]
@alexcoca You have three levels of nesting (a dict nested inside of a list nested inside of a dict). Thus, you need three dots:
```yaml
filter_package: my_package.decoder_filters
rules:
  - _target_ : "${...filter_package}.has_english_language"
  - _target_: "${...filter_package}.obeys_len_constraints"
    max_len_ratio_difference: 0.4
```

**Comment by alexcoca** [comment]
@Jasha10, thanks so much! Did not realise the list counts as one!

**Comment by alexcoca** [comment]
@Jasha10 Related to the above but slightly different. I am trying to partially instantiate the rules (which are just functions), using `_partial_` to achieve this, as per the docs:

```yaml
filter_package: gpt2_paraphrases.decoder_filters
rules:
    - _partial_: true
      _target_: "${filters.filter_package}.has_english_words"
    - _partial_: true
      _target_: "${filters.filter_package}.obeys_len_constraints"
      max_len_ratio_difference: 0.4
```

However, this results in ` has_english_words() got an unexpected keyword argument '_partial_'` error. Why is `_partial_` being passed as a kwarg, it is a special argument of the config, I was not expecting that.

**Comment by Jasha10** [comment]
You've been reading the "next" version of the docs :)

The `_partial_` keyword is not available in Hydra 1.1 (it is a planned feature for Hydra 1.2). You'll need to install Hydra from the `main` branch here on github if you want `_partial_` to work.
```text
pip install --upgrade https://github.com/facebookresearch/hydra/archive/main.zip
```

**Comment by alexcoca** [comment]
@Jasha10, that worked as expected, thank you so much for your help! :)

**Comment by alexcoca** [comment]
> Yup, this is often confusing people. When you print the object it shows the interpolation without resolving it (resolving by default would mean that you could not print an object with an a bad interpolation (that points to an invalid path).
> 
> You can convert it to a yaml and resolve it with `OmegaConf.to_yaml(cfg, resolve=True)`.
> 
> By the way: Interpolations can also point to nodes, not just values:
> 
> ```yaml
> a:
>   b: 10
>   c: 20
> 
> z: ${a}
> ```

@omry I was wondering if hydra supports the following. Suppose I have something like a language model and I have different parameter groups that can initialise it. Concretely, we have a yaml like this

```yaml
lm: 
  _target_: llm_lib.LLM
  temperature: 1.0
  best_of_n: 1  
```

ideally I want something like this
```yaml
lm: 
  _target_: llm_lib.LLM
  params: '{$..default}'

default:
  temperature: 1.0
  best_of_n: 1
  
worked_yesterday:
   temperature: 0.5
   best_of_n: 5
```



Is it possible to replace, params with the values of default.  So the composed config is:

```yaml
lm: 
  _target_: llm_lib.LLM
  temperature: 1.0
  best_of_n: 1  
```

ideally I want something like this
```yaml
lm: 
  _target_: llm_lib.LLM
  params: '{$..default}'

default:
  temperature: 1.0
  best_of_n: 1
  
worked_yesterday:
   temperature: 0.5
   best_of_n: 5
```

That is, the composed config would be 
```yaml
lm: 
  _target_: llm_lib.LLM
   temperature: 1.0
   best_of_n: 1

default:
  temperature: 1.0
  best_of_n: 1
  
worked_yesterday:
   temperature: 0.5
   best_of_n: 5
```

I feel I have seen this before in the docs, but the first google brought me here so thought I'd ask.

**Comment by odelalleau** [comment]
> @omry I was wondering if hydra supports the following. (...)

The standard way to do this with Hydra would be using the defaults list (https://hydra.cc/docs/advanced/defaults_list/):

`config.yaml`:
```yaml
defaults:
  lm: default

lm:
  _target_: llm_lib.LLM
```

`lm/default.yaml`:
```yaml
temperature: 1.0
best_of_n: 1
```

`lm/worked_yesterday.yaml`:
```yaml
temperature: 0.5
best_of_n: 5
```

Then you can use `lm=worked_yesterday` on the command line to switch to the settings from this file.
