### ISSUE TITLE
[Feature Request] Accessing hydra's resolver from hydra

### ISSUE THREAD

**Issue by YannDubs** [facebookresearch/hydra#1301]
# 🚀 Feature Request

It would be nice to be able to access `hydra` custom resolver from inside hydra's config. I.e. I would like the following to be correct:

```
my_path: ${hydra:runtime.cwd}/something/${hydra:job.id}

hydra:
  run:
    dir: ${my_path}

  sweep:
    dir: ${my_path}/
    subdir: ${hydra.job.num}
```

Currently, it raises `ValueError: HydraConfig was not set` because presumingly `hydra`'s resolver is only accessible after setting the directories.

## Motivation

I have a group of config's that essentially set the server I'm working on (think `learnfair`,`local`,`aws` ...). For each of those server's I have different `my_path` which I would like to modify once. This is then used to modify my `hydra.sweep.dir`, `hydra.run.dir`, checkpointing paths... 

Currently, I have to set/modify all the paths that are used by hydra and the paths that use in the rest of my config separately because I cannot use  `${my_path}` from inside hydra's config as it requires  `hydra` custom resolver to already be accessible. 

## Pitch

**Describe the solution you'd like**
Either have `hydra:` resover be accessible in hydra's config or have `hydra.something` (e.g. `hydra.runtime.cwd`) accessible from the rest of the config. 

**Describe alternatives you've considered**

Have the following :
```
my_path: ${hydra:my_path}

hydra:
  my_path: ${hydra.runtime.cwd}/something/${hydra.job.id}

  run:
    dir: ${my_path}

  sweep:
    dir: ${my_path}/
    subdir: ${hydra.job.num}
```

I actually was surprised that this alternative didn't work, it seems that I cannot set additional fields to hydra's config. That would also be fine for me (if it worked) although I think this alternative is slightly less clean (hydra's config should probably not be modified too much by the user)

**Comment by omry** [comment]
Will take a look, not sure it's possible.

**Comment by shubham-goel** [comment]
@YannDubs I'm using hydra 1.1.0dev1 and  this already works. I don't get any error with your config, the hydra resolver is accessible inside hydra's config.

**Comment by omry** [comment]
```yaml
my_path: ${hydra:runtime.cwd}/something/${hydra:job.name}

hydra:
  run:
    dir: ${my_path}

  sweep:
    dir: ${my_path}
    subdir: ${hydra:job.num}
```

I changed the config to use hydra:job.name (which is always initialized) and it works fine both in master and in 1.0.
(I was not able to see the error you reported).

hydra.job.id is weird because it's becoming available later.
In fact, it doesn't make sense at all to use it in normal runs because it is not initialized there (job id is set by the Launcher, and currently the Launcher is only used in --multirun.

Closing, free free to repopen if are able to provide more exact repro instructions.
