### ISSUE TITLE
[Bug] `hydra.job.id` cannot be used in `hydra.sweep.dir`

### ISSUE THREAD

**Issue by YannDubs** [facebookresearch/hydra#1302]
# 🐛 Bug

`hydra.job.id` cannot be used in `hydra.sweep.dir` but it can be used in `hydra.sweep.subdir`. The same holds for `hydra.job.num`.

## To reproduce

`config.yaml`:

```
hydra:
  sweep:
    dir: ${hydra.runtime.cwd}/${hydra.job.id}
    subdir: ${hydra.job.num}
```

`test.py`:

```python
import hydra
@hydra.main(config_name='config')
def main(cfg):
        pass
main()
```

Command `python test.py  -m`

** Stack trace/error message **
```
omegaconf.errors.MissingMandatoryValue: Missing mandatory value : hydra.job.id
	full_key: hydra.sweep.dir
	reference_type=SweepDir
	object_type=SweepDir
```

## System information
- **Hydra Version** :  I tested both on *1.0.5* (stabel) and *hydra-core-1.1.0.dev2* (pre)
- **Python version** : 3.8.5
- **Operating system** : Ubuntu
