### ISSUE TITLE
[Bug] Nested dictionary overwrite only keeps last k:v

### ISSUE THREAD

**Issue by bimtauer** [facebookresearch/hydra#1307]
# 🐛 Bug
## Description
I tried to use dictionary overrides from command line as shown [here](https://hydra.cc/docs/next/advanced/override_grammar/basic/#dictionaries), but cannot get the expected output.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] All code needed to reproduce is below:

## To reproduce

app.py
```python
import hydra
from omegaconf import DictConfig, OmegaConf

@hydra.main(config_name='config')
def my_app(cfg: DictConfig) -> None:
    print(OmegaConf.to_yaml(cfg))

if __name__ == "__main__":
    my_app()
```
config.yaml
```yaml
db:
  driver: mysql
  user: omry
  password: secret
```
Run:
`python app.py db={user:root,pass:1234}
`

### The buggy output:
`db: pass:1234`

### Expected output:
```
db:
  driver: mysql
  user: root
  pass: 1234
```

## System information
- **Hydra Version** :  1.0.5 
- **Python version** :  3.7.6
- **Virtual environment type and version** :  conda 4.8.3
- **Operating system** :  Ubuntu 20.04
