### ISSUE TITLE
[Bug] Multirun startup tends to become quite slow for large sweeps.

### ISSUE THREAD

**Issue by TommasoBendinelli** [facebookresearch/hydra#1324]
# 🐛 Bug
## Checklist
- [ X] I checked on the latest version of Hydra
- [ X] I created a minimal repro (See [this](https:// .com/help/minimal-reproducible-example) for tips).

## To reproduce
I have create the following basic yaml file 
```
defaults:
  - parameters: case1
  - parameters/additional: subvalues1

hydra:
  overrides:
      task:
      - parameters=case1,case2,case3
      - +num=range(0,2)
```

associated with this python script:
```
import hydra
import json


@hydra.main(config_path="conf", config_name="config")
def main(cfg):
    print(cfg)


if __name__ == "__main__":
    main()


```
When I change num from range(0,2) to range(0,100), takes much more time start (i.e. from less than one second to about one minute)

## Expected Behavior
I would expect a much less slow down.

## System information
- Hydra 1 :  
- Python 3.8* : 
- VirtualEnv: virtualenv : 
- Operating System: Ubuntu 20.04 :
