### ISSUE TITLE
[AxPlugin-Bug] Ax optimization does not return the optimal value

### ISSUE THREAD

**Issue by alexeib** [facebookresearch/hydra#1352]
ax optimization doesnt actually select the lowest target value for recommendation

i run a job locally with the following ax config ("ax_local.yaml"):

```
hydra:
  sweeper:
    max_batch_size: 1
    ax_config:
      max_trials: 64
      params:
        p1:
          value_type: float
          type: range
          bounds: [0.0,8.0]
        p2:
          value_type: float
          type: range
          bounds: [0.0,5.0]
```

the job is launched like so:

```
python my_script.py -m --config-dir ~/configs --config-name my_config hydra/sweeper=ax +sweep_config=ax_local
```

my main method returns a value (which is what is presumably optimized) and also prints this score (along with params)

after the optimization is finished i get "best parameters" method. If i cross reference the parameters to the actual scores printed out during the optimization, i see that these there are several scores that are much lower that are available.

additionally, when "new best params" message is printed out occasionally, the score that it lists is not the actual score that was returned by the main method (but something reasonably close), for example:

New best value: 8.640574264487782, best parameters: ...

but when I find my own print out for these parameters i see that the score is actually 11.79782511729088

**Comment by omry** [comment]
I suspect this is due to Ax modeling versus function output. (Ax is modeling your function and is trying to predict it's output. So it can claim to find a new best value based on what it THINKS the value will be as opposed to actually running the function (your training) and seeing the result.
I remember having some discussions about it with the Ax team.

@shagunsodhani, can you take a look?

By the way: Can you provide a proper title to your bug report?

**Comment by shagunsodhani** [comment]
Hi @alexeib. As @omry rightly pointed out, the issue is that Ax is building a model for predicting the output. [Here](https://ax.dev/api/service.html#ax.service.ax_client.AxClient.get_best_parameters
) is the relevant API. Copy pasting the doc for easy reference:

```
get_best_parameters() → ...

...

First attempts according to do so with models used in optimization and its corresponding predictions if available. Falls back to the best raw objective based on the data fetched from the experiment.

...

Returns
Tuple of parameterization and model predictions for it.
```

**Comment by alexeib** [comment]
sorry about the title, mustve missed it!

re: modeling - i am a bit confused. why should i trust the parameters ax is recommending if in fact they are not optimal parameters?

**Comment by alexeib** [comment]
i tried the same thing with nevergrad with a config like this:

```
# @package _global_

hydra:
  sweeper:
    optim:
      optimizer: NGOpt
      budget: 64
      num_workers: 1
    parametrization:
      p1:
        init: 0.0
        lower: 0.0
        upper: 8.0
      p2:
        init: 0.0
        lower: 0.0
        upper: 5.0
```

and the params it recommends correspond to the run that achieved the lowest score. so must be either ax, or ax plugin to hydra
