### ISSUE TITLE
[Feature Request] Recursively instantiate interpolated targets

### ISSUE THREAD

**Issue by mantaco1** [facebookresearch/hydra#1420]
# 🚀 Feature Request
I would like Hydra to instantiate a nested ` _target_` which comes from interpolation. Here's an example:

##### config_test.yaml
```yaml
child:
    _target_: config_test.Child
parent:
    _target_: config_test.Parent
    child: ${child}
```

##### config_test.py
```python
import hydra
from hydra.utils import instantiate


class Child:
    pass

class Parent:
    def __init__(self, child):
        self.child = child

@hydra.main(config_name="config_test")
def run(cfg):
    parent = instantiate(cfg.parent)
    print(parent.child)


if __name__ == "__main__":
    run()
```
In this example Hydra does not currently instantiate `parent.child` but I would like it to. It is still a dict-like object when accessed here.

## Motivation
The most common use case is instantiating the same object in multiple parts of your code, where you want the config of that object to be linked.

## Pitch
Instantiate the object
