### ISSUE TITLE
[Feature Request] Subconfig selection via config_name

### ISSUE THREAD

**Issue by SolomidHero** [facebookresearch/hydra#1436]
# 🚀 Feature Request

Hi! I'd to have feature of accessing only a part of all-in-one config (when it generates)

## Motivation

1. I have tests of some modules in my project and want to perform them with hyperparameters defined in config. Of course for each test I need only part of parameters.
For example of simple test, assume files:

**`config.yaml`**: (some number of params)
```yaml
opt:
  lr: 3e-4
  betas: [0.8, 0.99]
  lr_decay: 0.995
model:
  features_dim: 768
  n_classes: 10
  generator:
    hidden_dim: 768
    n_blocks: 7
  discriminator:
    lrelu_slope: 0.2
```
**`tests/test_generator.yaml`** :
```python
def test_with_initialize() -> None:
  with initialize(config_path="../"):
    cfg = compose(config_name="config")

  assert cfg.model.generator.hidden_dim == 768
```

2. For some utils that uses config I can directly specify using subconfig
```python
# current use

@hydra.main(config_name="config")
def some_func(cfg):
  cfg = cfg.key1.key2.key3
  pass
```

## Pitch

**Describe the solution you'd like**: Routing to subconf via dots, or slashes (like conf directories, because there are anyway append to one big config). So the solution view:

1. Simply:

**`tests/test_generator.yaml`** :
```python
def test_with_initialize() -> None:
  with initialize(config_path="../"):
    cfg = compose(config_name="config.model.generator")

  assert cfg.hidden_dim == 768
```
and use `cfg` instead of `cfg.model.generator`

2. I can use 
```python
@hydra.main(config_name="config.key1.key2.key3")
def some_func(cfg):
  # some ops
  pass
```

OR: use additional parameter (for example `subtree`) to specify route to subconf

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md)) **NoT ReAlLy** (but I think there must be already some features like this)
