### ISSUE TITLE
possible to print `$CONFIG` in hydra help with interpolation resolved?

### ISSUE THREAD

**Issue by hwijeen** [facebookresearch/hydra#1482]
Hi, thank you for the brilliant library once again!

I am using `--help` functionality following the [docs](https://hydra.cc/docs/configure_hydra/app_help), and wondering if the values printed with `$CONFIG` can be 'resolved.
For example, what I get right now is
```yaml
...
load_dataset:
  _target_: datasets.load_dataset
  path: ${hydra:runtime.cwd}/loading_script.py
...
```
Is there a way to get `hydra:runtime.cwd` resolved to an actual path?

Thanks!

p.s. Is there a functional equivalence of python argparse's variable-wise `help`?
```python
parser.add_argument('foo', help='can hydra have something like this to explain each variable?')
```
