### ISSUE TITLE
[Bug] Cannot use experiment pattern when using overrides in main config file

### ISSUE THREAD

**Issue by ashleve** [facebookresearch/hydra#1548]
# 🐛 Bug
When using any override in main config, e.g. for color logging or sweeper:
```yaml
defaults:
    - override hydra/hydra_logging: colorlog
    - override hydra/job_logging: colorlog
```

Then the experiment configs can't be loaded:
```bash
python main.py +experiment=experiment_name
```
Stack trace:
```
In config.yaml: Override 'hydra/job_logging : colorlog' is defined before 'experiment: experiment_name'.
Overrides must be at the end of the defaults list
```

## System information
- **Hydra Version** :  1.1.0.dev5
- **Python version** : 3.8
- **Virtual environment type and version** : conda
- **Operating system** : Ubuntu20.04

## Additional context
I believe this issue didn't exist on 1.1.0.dev4.
