### ISSUE TITLE
Default fields not merged when using [--config-name|-cn] flag

### ISSUE THREAD

**Issue by ramonemiliani93** [facebookresearch/hydra#1617]
# 🐛 Bug
## Description
When changing the configuration file from the command line the fields that have a default value on the structured configs used as schemas are not merged.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro.

## To reproduce
I have attached a zipped project with the code to reproduce the bug. It is similar to the example given for the [static schema with many config](https://hydra.cc/docs/tutorials/structured_config/static_schema). I have added a field to the `DBConfig` dataclass with a default value i.e. `default_field: str = "default"` and duplicated the `config.yaml` with a differente name `other.yaml` when running `python main.py` I get:

```
db:
  driver: mysql
  host: mysql001.staging
  user: root
  password: root
  default_field: default
```

which is the correct output. On the other side, when changing the config with  `python main.py -cn other`, I get:

```
db:
  driver: mysql
  host: mysql001.staging
  user: root
  password: root
```

which is missing `default_field`.

** Minimal Code/Config snippet to reproduce **
[hydra-bug.zip](https://github.com/facebookresearch/hydra/files/6466883/hydra-bug.zip)

## Expected Behavior
Both configurations printed should be the same.

## System information
- **Hydra Version** :  1.0.6
- **Python version** : 3.7.10
- **Virtual environment type and version** : conda 4.9.2
- **Operating system** :  macOS Catalina 10.15.6
