### ISSUE TITLE
Updates to callback doc

### ISSUE THREAD

**Issue by jieru-hu** [facebookresearch/hydra#1636]
see comments in https://github.com/facebookresearch/hydra/pull/1630

**Comment by omry** [comment]
A few additional comments:
In the following config, there is no need to use `_global_` package:
![image](https://user-images.githubusercontent.com/376455/121249434-71b0f880-c859-11eb-99e4-aaa5a5ee0e63.png)

This should work too:

conf/hydra/callbacks/my_callback.yaml:
```yaml
my_callback:
  _target_: my_app.MyCallback
  bucket: my_s3_bucket
  file_path: ./test.pt
```

There is a horizontal scroll bar here:
![image](https://user-images.githubusercontent.com/376455/121249652-ad4bc280-c859-11eb-9e51-44c1375c83dd.png)
