### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by dsantiago** [facebookresearch/hydra#1672]
# 🚀 Feature Request (Or just understand better...)

Hello, i am trying to omit the logs file and .hydra dir, even though i can the way is not intuitive. i have the following:

```yaml
hydra:
  run:
    dir: . 
  
  output_subdir: null
  # job_logging: null

defaults:
  - tables: ???

  # - override hydra/output_subdir: null
  - override hydra/job_logging: disabled
```

I first tried both `output_subdir` and `job_logging` under the `hydra` entry. But it do no work, then both in the `defaults` with override, it do not work either. The only way it worked was the `output_subdir` under `hydra` and the `job_logging` via overriding.

Is that supposed to be like that? Is the `job_logging` already loaded, so i need to override and `output_subdir` is not pre-loaded so i can change/add it under hydra options?

I am just trying to understand, and if it fits, we can find an intuitive solution.

## Motivation

Understand it make the configuration more intuitive
