### ISSUE TITLE
[Bug] Add param to defaults from child configs

### ISSUE THREAD

**Issue by singhay** [facebookresearch/hydra#1690]
# 🐛 Bug
## Description
I'm am migrating from 0.11 and not able to resolve this one issue.

## Checklist
- [*] I checked on the latest version of Hydra
- [*] I created a minimal repro

## To reproduce

** Minimal Code/Config snippet to reproduce **
`config.yaml`
```
defaults:
  - model: classification/cnn1d_dilation_rnn_sm
  - data: classification
  - optimizer: adam
  - lr_scheduler: reduce_lr_on_plateau
  - training: gpu

aml:
  experiment_name: 'test'
  experiment_folder: 'experiment_src'

  docker:
    base_image: 'mcr.microsoft.com/azureml/openmpi3.1.2-cuda10.2-cudnn8-ubuntu18.04'
```
Now in `0.11` for the `aml` part, I had some extra params that were present in `gpu.yaml` that got added. here's `gpu.yaml`
```
aml:
    cluster_name: 'gpu-cluster-nc6'
    docker:
        shm_size: '50g'
```

** Stack trace/error message **
However, after migrating I only see the `aml` params mentioned in `config.yaml` instead of combined aml config from both `gpu.yaml` and `config.yaml`. 
Can anyone point to me what I might be missing here?

## Expected Behavior
`0.11` gives the final output that combines aml from both config.yaml and gpu.yaml
```
aml:
    experiment_name: 'test'
    experiment_folder: 'experiment_src'
    cluster_name: 'gpu-cluster-nc6'
    docker:
        base_image: 'mcr.microsoft.com/azureml/openmpi3.1.2-cuda10.2-cudnn8-ubuntu18.04'
        shm_size: '50g' 
```

## System information
- **Hydra Version** :  1.1.0
- **Python version** : 3.7.9
- **Virtual environment type and version** :  Conda 4.10.1
- **Operating system** : mac
