### ISSUE TITLE
Recursive defaults support

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#171]
Hydra does not currently support a recursive defaults list. the defaults are only specified at the primary config file.
There is some special support for Hydra itself, but this can be ignored for the purpose of this issue.

Recursive defaults list are tricky, it's important to ensure intuitive and consistent order of merging.

### Proposed logic

if the defaults in the primary file are in that order:
main.yaml
```yaml
defaults:
  - aa: x1
  - bb: x2
```

The relative order should be preserved. it is however possible for other files to be injected in between aa and bb, for example if aa/x1 had it's own defaults:

aa/x1.yaml
```yaml
defaults:
  - cc: x3
  - dd: x4
```

the resulting defaults list might looks like:
```yaml
  - aa: x1
  - cc: x3  # from aa/x1 
  - dd: x4  # from aa/x1 
  - bb: x2
```

Let's look at a more complicated case:

main.yaml
```yaml
defaults:
  - aa: x1
  - bb: x2
  - cc: must_win
```
aa/x1.yaml
```yaml
defaults:
  - cc: x3
  - dd: x4
```
In this case, the result should be:
the resulting intermediate list will looks like:
```yaml
  - aa: x1
  - cc: x3
  - dd: x4
  - bb: x2
  - cc: must_win
```
but the final result will be:
```yaml
  - aa: x1
  - cc: must_win
  - dd: x4
  - bb: x2
```

Note how cc retains it's order in the list, but got the last value.

The rule here is:
1. Composition order determined by the first time a configuration group is introduced (the `db` in `db=mysql`).
2. Composition choice (the `mysql` in `db=mysql`) is determined by the last mention of the group).
