### ISSUE TITLE
[Question] override an non-mandatory field to be mandatory

### ISSUE THREAD

**Issue by chris-tkinter** [facebookresearch/hydra#1729]
Hi, I am wondering how should we override an non-mandatory field to be mandatory, for example, I have a config group called `dataset` which defines which dataset I am going to use. And I would like to create [an experiment like this](https://hydra.cc/docs/next/patterns/configuring_experiments/#example).

here in experiment *exp.yaml*
```yaml
# @package _global_

defaults:
  # default.yaml define data_path as null
  - override /dataset: default

dataset:
 # must provide a data_path
  data_path: ???
```
However even if I leave `data_path` as empty by using cmd `main.py +exp=exp` the data_path still remains `None` instead of missing.

I am wondering how should I change the `data_path` to be mandatory? Thanks!

**Comment by Jasha10** [comment]
Hi @chris-tkinter,

The following is working for me:

Here is `main.py`:
```python
import hydra
from omegaconf import OmegaConf

@hydra.main(config_path="conf", config_name="config")
def my_app(cfg):
    print(OmegaConf.to_yaml(cfg))

my_app()
```

Here is `conf/config.yaml`:
```yaml
defaults:
  - dataset: ???
```

Here is `conf/dataset/default.yaml`:
```yaml
a: 123
```

Here is `conf/exp/exp.yaml`:
```yaml
# @package _global_
defaults:
  - override /dataset: default
dataset:
  data_path: ???
```

And here is the output from the python program:
```text
$ python main.py +exp=exp
dataset:
  a: 123
  data_path: ???
```

**Comment by Jasha10** [comment]
When I replace the contents of `default.yaml` with the following
```yaml
a: 123
data_path: foo
```
then I am actually getting the same problem:
```text
$ python main.py +exp=exp
dataset:
  a: 123
  data_path: bla
```

I will follow up shortly with a workaround to make sure that `data_path` is missing in the output config.

**Comment by Jasha10** [comment]
The root cause of this behavior is the `OmegaConf.merge` method used by Hydra to combine input configs. `OmegaConf.merge` treats missing values specially; it does not overwrite non-missing values with missing values. For example,
```python
from omegaconf import OmegaConf
# "bar" overwrites "foo", as expected:
assert OmegaConf.merge({"data_path": "foo"}, {"data_path": "bar"}) == {"data_path": "bar"}
# "???" does not overwrite "foo":
assert OmegaConf.merge({"data_path": "foo"}, {"data_path": "???"}) == {"data_path": "foo"}
```

My recommended workaround is to use an interpolation-to-missing value; replace the contents of `conf/exp/exp.yaml` with the following:
```yaml
# @package _global_
defaults:
  - override /dataset: default
explicit_missing: ???
dataset:
  data_path: ${..explicit_missing}
```

Here's the output:
```text
$ python main.py +exp=exp
dataset:
  a: 123
  data_path: ${..explicit_missing}
explicit_missing: ???
```

If you want the `${..explicit_missing}` interpolation to be resolved to a literal missing value, you can call `OmegaConf.resolve(cfg)`:
```python
@hydra.main(config_path="conf", config_name="config")
def my_app(cfg):
    OmegaConf.resolve(cfg)
    print(OmegaConf.to_yaml(cfg))
```
This results in the following output:
```text
$ python main.py +exp=exp
dataset:
  a: 123
  data_path: ???
explicit_missing: ???
```

Using an interpolation-to-missing value (instead of a literal missing value `"???"`) results in `OmegaConf.merge` overwriting `data_path` when the `exp` config is merged into the global config package. See the OmegaConf docs on [interpolation](https://omegaconf.readthedocs.io/en/2.1_branch/usage.html#variable-interpolation) for more info on how to use variable interpolations in your Hydra configs.
