### ISSUE TITLE
[Question] How to replace value in list of dict from experiment config?

### ISSUE THREAD

**Issue by igorgad** [facebookresearch/hydra#1738]
Say I have a config file like
```
rootvalue: [value]
dict:
    - A_value_1: [value]
      A_value_2: [value]
    - B_value_1: [value]
      B_value_2: [value]
```
and want to replace `A_value_2` from an experiment config file like
```
# @package _global_
rootvalue: 10
dict.0.A_value_2: 20       <-  This does not work
```
Other attempts like
```
# @package _global_
rootvalue: 10
dict:
    - A_value_2: 20         <- This replaces the whole list entry
```
Is there any way to achieve this?
Thanks,.
