### ISSUE TITLE
[Feature Request] Defaults List interpolation in Groups

### ISSUE THREAD

**Issue by nachovizzo** [facebookresearch/hydra#1763]
# 🚀 Feature Request

Use object from main config default list in group configs.

## Motivation

So, first of all, thanks for such a great tool, and sorry if my terminology it's not correct.

This is the problem I'm trying to solve:

### Conf files

```sh
├── config.yaml
└── db
    ├── mod_db.yaml
    ├── mysql.yaml
    └── postgresql.yaml
```

#### `config.yaml`
```yaml
defaults:
  - db: mysql
  - db@mod: mod_db
```

### Rest of the config files

`mod_db.yaml:`
```yaml
defaults:
  - mysql

attribute: something
```
`mysql.yaml:`
```yaml
driver: mysql
user: omry
pass: secret
```

`postgresql.yaml:`
```yaml
driver: postgresql
user: omry
pass: secret
```

### outputs

`$ python my_app.py db=mysql`

```yaml
db:
  driver: mysql
  user: omry
  pass: secret
mod:
  driver: mysql
  user: omry
  pass: secret
  attribute: something
```

`$ python my_app.py db=postgresql`
```yaml
db:
  driver: postgresql
  user: omry
  pass: secret
mod:
  driver: mysql # <------------------------- this is the problem! 
  user: omry
  pass: secret
  attribute: something
```

## Pitch

**Describe the solution you'd like**
What I would like to write on the `mod_db.yaml` is something like:

`mod_db.yaml:`
```yaml
defaults:
  - ${db}

attribute: something
```

Where `$[db]` is any of `(mysql, postgresql)`. This `mod_db.yaml` just need to extend one of these two. But I get the following error `In 'db/mod_db': Defaults List interpolation is only supported in the primary config`

**Describe alternatives you've considered**
So far what I do is to manually change the `mod_db.yaml` file by changing the defaults list, although this is not convenient at all.

**Are you willing to open a pull request?**

Sure thing! But I have no clue where to start!

## Additional context
According to the [documentation](https://hydra.cc/docs/advanced/defaults_list/#interpolation-in-the-defaults-list)

> Interpolation keys in the Defaults List cannot reference values in the Final Config Object (it does not yet exist).

**Comment by omry** [comment]
Defaults list interpolation in configs other than the primary one is not supported and will not be supported.
The error is telling this to you very clearly: "Defaults List interpolation is only supported in the primary config".

I suggest you try to model your config differently. There are good reasons for why this is not supported.

One idea is to use interpolation in your mod_db:
```yaml
defaults:
  - mysql

driver: ${db.driver}
attribute: something
```

**Comment by nachovizzo** [comment]
Thanks for the fast reply!

I see I could do what you suggest, the problem I have is with the real application I have much more attributes, and at the end, I would need to repeat all of them in the `mod_db`, something like:

```yaml
driver: ${db.driver}
user: ${db.user}
pass: ${db.pass}
attribute: something
```

I guess I won't find the solution I'm looking for, but If I find some other way to do this I will post it on this issue.

Thanks again!

**Comment by omry** [comment]
Another feature you can use is to merge into an interpolated node.
When OmegaConf merged into an interpolation to a node, the node is copied and the merge is happening into the new node.
```python
from omegaconf import *

cfg1 = OmegaConf.create(
    {
        "db": {
            "user": "root",
            "hostname": "localhost",
            "password": "12345",
        },
        "expanded": "${db}",
    }
)
cfg2 = OmegaConf.merge(cfg1, {"expanded": {"user": "omry"}})
print(OmegaConf.to_yaml(cfg2))

# output:
# db:
#   user: root
#   hostname: localhost
#   password: '12345'
# expanded:
#   user: omry
#   hostname: localhost
#   password: '12345'
```
You can model something like this with Hydra as well. (I will leave it as an exercise to the reader ;) ).

**Comment by nachovizzo** [comment]
Nice exercise :)

The other solution I also evaluated was to use [extension](https://hydra.cc/docs/next/patterns/extending_configs/)

```sh
conf
├── config.yaml
└── db
    ├── mysql_gt.yaml
    ├── mysql.yaml
    ├── postgresql_gt.yaml
    └── postgresql.yaml
```

and then
mysql_gt.yaml:
```yaml
defaults:
  - mysql

user: tu_vieja_gt
```

postgresgql.yaml:
```yaml
defaults:
  - postgresql

user: tu_vieja_gt
attribute: something
```

And on the main config:
```yaml
defaults:
  - db: mysql
  - optional db@mod: ${db}_gt
```

Example runs:

`$ python my_app.py db=postgresql`:
```yaml
db:
  driver: postgresql
  user: omry
  pass: secret
mod:
  driver: postgresql
  user: tu_vieja_gt
  pass: secret
  attribute: something
```

`$ python my_app.py db=mysql`:
```yaml
db:
  driver: mysql
  user: omry
  pass: secret
mod:
  driver: mysql
  user: tu_vieja_gt
  pass: secret
```


Although this requires duplicating the `xxx_gt.yaml` for all the necessary extended configurations. I guess this is the solution I like the "most"
