### ISSUE TITLE
[Feature Request] how to customizing the working dir?

### ISSUE THREAD

**Issue by marsggbo** [facebookresearch/hydra#1771]
# 🚀 Feature Request

## Motivation

> https://hydra.cc/docs/configure_hydra/workdir

In the tutorial, the pattern only supports time, like `%d,%H`. However, a time-based directory can not help us quickly recognize which task it belongs to, so I wonder if hydra support specifying a task name. If so, what should we do?

## Pitch

**Describe the solution you'd like**

- `hydra.yaml`
```yaml
run:
dir: logs/runs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
    
```

- run the code
```python
python main.py hydra.job.name=my_task_name
```

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by Jasha10** [comment]
@marsggbo 你好!

Please try the following:
Here is `main.py`:
```python
import os

import hydra
from omegaconf import DictConfig

@hydra.main(config_path=".", config_name="config")
def my_app(_cfg: DictConfig) -> None:
    print(f"Working dir {os.getcwd()}")

if __name__ == "__main__":
    my_app()
```
Here is `config.yaml`:
```yaml
hydra:
  run:
    dir: logs/runs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
```
Here is the output:
```text
$ python3 main.py
Working dir /home/.../logs/runs/main/2021-08-15_10-50-40
$ python3 main.py hydra.job.name=my_task_name
Working dir /home/.../logs/runs/my_task_name/2021-08-15_10-50-47
```

For more ideas, take a look at the examples in https://github.com/facebookresearch/hydra/tree/master/examples/configure_hydra

**Comment by Ereebay** [comment]
@Jasha10  Hello, I met a strange problem when I modify the working directory.
Modifying the working directory in config.yaml is working for me. But I can not modify the directory in separate config file. 
This is my main code
`@hydra.main(config_path='conf/', config_name='train')
def main(config):
    print(os.getcwd())
    working_dir = str(Path.cwd().relative_to(hydra.utils.get_original_cwd()))
`
Here is `config.yaml` file
```yaml
defaults:
  - _self_
  - data: mnist_train
  - model: mnist_lenet
  - hparams: lenet_baseline

  - status: train
  - override hydra/job_logging : custom
  - override hydra/output: job_timestamp
```

And this is my folder structure

```
conf
|-hydra
  |-job_logging
    |-custom.yaml
  |-output
    |-job_timestamp.yaml
config.yaml
```

and this my `job_timestamp.yaml`
```yaml
run:
  dir: ./outputs/${status}/${now:%Y-%m-%d}/${now:%H-%M-%S}
```

And this is the outputs:
```
../dl-template/None
```
But if I modify the hydra.run.dir in the config file, the output is working
```
../dl-template/outputs/train/2021-09-28/10-03-37
```
