### ISSUE TITLE
[Feature Request] Access variables printed out from --cfg flag

### ISSUE THREAD

**Issue by victkid** [facebookresearch/hydra#1780]
# 🚀 Feature Request

Are there any ways to access the information printed out from --cfg command line flag (https://hydra.cc/docs/next/advanced/hydra-command-line-flags/)?  

For example, `python my_app.py --cfg all` will print out following information
```
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.
    ...
  job:
    name: my_app
    override_dirname: ''
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.1.0
    cwd: /home/ubuntu/projects/notebooks
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/ubuntu/projects/notebooks/configs
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
```
How to access those information inside main() function? Would it be possible to access config path by using somethine like `hydra.runtime.config_sources.path` ?

## Motivation

There are variables that I want to set based on the augments that I pass to hydra in the command line. When I using argparse. I can access my arguments using 
```
ags = parser.parse_args()
config_args = vars(args)
```
