### ISSUE TITLE
Cannot  access HydraConfig in sweep using Hydra resolver

### ISSUE THREAD

**Issue by cnut1648** [facebookresearch/hydra#1786]
# 🚀 Feature Request
Hi I am wondering if it is possible to use `hydra:` namespace in the sweep.

## Motivation
I would like to customize the sweep dir, but however it seems that when I need to do a value interpolation I got the following error message
```
omegaconf.errors.InterpolationResolutionError: ValueError raised while resolving interpolation: HydraConfig was not set
    full_key: hydra.sweep.dir
    reference_type=SweepDir
    object_type=SweepDir
```
My config is (created from [this example](https://github.com/facebookresearch/hydra/blob/master/examples/configure_hydra/workdir/conf/config.yaml))
```yaml
# @package _global_
hydra:
  run:
    dir: run_dir
  sweep:
    dir: ${log_dir}
    subdir: ${hydra.job.num}

a: a1
work_dir: ${hydra:runtime.cwd}
log_dir: "${work_dir}/../my_long_logs"
```
It seems that the `hydra:` namespace can't be accessed during the sweep. and my current workaround is making `log_dir` to be
```
log_dir: "../my_long_logs"
```
## Additional context
The python version is python 3.6. and the hydra version is 1.1.1 (the latest)

**Comment by jieru-hu** [comment]
Hi @cnut1648  could you share how are you running the sweep? We do not support sweeping over Hydra configs.

**Comment by cnut1648** [comment]
Hi @jieru-hu in this case I just use something like
```
python main.py -m a=1,2,3
```
The actual command I think does not matter here since I only would like to make `hydra.sweep.dir` interpolate with `work_dir`. So the sweep dir would be created to `<work_dir>/../my_long_logs` instead of the default dir.

**Comment by jieru-hu** [comment]
hey @cnut1648 
sorry for getting back to you late - as you can see from the stacktrace, HydraConfig is not initialized at that time so OmegaConf could not run the `hydra` custom resolver. if you update your config to be `work_dir: ${hydra.runtime.cwd}` it should work as expected.

**Comment by cnut1648** [comment]
Thank you @jieru-hu! I think this works and I can create an another field that is interpolated with the `hydra.runtime.cwd`. But I have yet another question, now I changed my config to be

```yaml
work_dir: ${hydra.runtime.cwd}
log_dir: "${work_dir}/../my_long_logs"
```
I noticed that I cannot access either `cfg.work_dir` or `cfg.log_dir` in the runtime. I got the following error

```
omegaconf.errors.InterpolationKeyError: Interpolation key 'hydra.runtime.cwd' not found
    full_key: log_dir
    object_type=dict
```
I am not sure why there would be this error since the `log_dir` is created correctly. Would you mind helping me out? Thank you again.

**Comment by Chianugoogidi** [comment]
> I noticed that I could not access either `cfg.work_dir` or `cfg.log_dir` in the runtime. I got the following error when I do something like `cfg.log_dir`
> 
> ```
> omegaconf.errors.InterpolationKeyError: Interpolation key 'hydra.runtime.cwd' not found
>     full_key: log_dir
>     object_type=dict
> ```
> 
> Accessing `cfg.work_dir` raise the same error.
>

I also have a similar problem.  In my case I'm doing `working_dir: ${hydra:runtime.cwd}`. When using hydra in a jupypter notebook, I can get around the problem as follows:

```python
import hydra
from omegaconf import OmegaConf
from hydra.core.global_hydra import GlobalHydra
from hydra.core.hydra_config import HydraConfig

GlobalHydra.instance().clear()

hydra.initialize(config_path="configs")
cfg = hydra.compose(config_name="config", return_hydra_config=True)
HydraConfig().cfg = cfg
OmegaConf.resolve(cfg)

```
However, the hydra config seems to be deleted during initialization, so when I go to do the same thing in a regular python script, I get the following error:
```
InterpolationResolutionError: ConfigAttributeError raised while resolving interpolation: Key 'hydra' is not in struct
    full_key: hydra
    object_type=dict
```

**Comment by jieru-hu** [comment]
@cnut1648 

when you configure Hydra, you will need to use interpolations, something like `${hydra.runtime.cwd}`

for your application's configuration, you will need the Hydra resolver. https://hydra.cc/docs/configure_hydra/intro#resolvers-provided-by-hydra

so in your case, consider something like the following

```
# @package _global_
hydra:
  run:
    dir: run_dir
  sweep:
    dir:  ${hydra.runtime.cwd}
    subdir: ${hydra.job.num}

a: a1
work_dir: ${hydra:runtime.cwd}
log_dir: "${work_dir}/../my_long_logs"
```

**Comment by jieru-hu** [comment]
@Chianugoogidi I'm not sure you are running into the same issue as this one, do you mind creating a new issue with a minimal repro? Thanks.

**Comment by jgbos** [comment]
I recently ran into this error using this config:

```yaml
hydra:
  run:
    dir: outputs/${name}

  sweep:
    dir: outputs/${name}

defaults:
  - _self_
  - experiment: ???

name: ${hydra:choices.experiment}
```

If I do `python run.py experiment=anything` it works fine, but if I add `-m` for multirun I get the `InterpolationResolutionError` above.

**Comment by jieru-hu** [comment]
> I recently ran into this error using this config:
> 
> ```yaml
> hydra:
>   run:
>     dir: outputs/${name}
> 
>   sweep:
>     dir: outputs/${name}
> 
> defaults:
>   - _self_
>   - experiment: ???
> 
> name: ${hydra:choices.experiment}
> ```
> 
> If I do `python run.py experiment=anything` it works fine, but if I add `-m` for multirun I get the `InterpolationResolutionError` above.



Thanks for the reports @jgbos 

> name: ${hydra:choices.experiment}

this should be  `${hydra:runtime.choices.experiment}`

> If I do `python run.py experiment=anything` it works fine, but if I add `-m` for multirun I get the `InterpolationResolutionError` above.

I can reproduce this on Hydra 1.1.1 but both RUN and MULTIRUN fails for Hydra main branch. Looking now...

**Comment by jieru-hu** [comment]
@jgbos  @cnut1648 @Chianugoogidi

is there any particular reason you want to create `sweep.dir` based on interpolation instead of `sweep.subdir`? 

for example, using @jgbos's example, i think the same output dir could be achieved in the following config
```
hydra:
  run:
    dir: outputs/${name}

  sweep:
    dir: .
    subdir: outputs/${name}/${hydra.job.num}
```

a bit more details on the error: we try to create `sweep.dir` before finishing composing configs so at the time of sweep.dir creation, we don't have the final config in place, but the story is different for `sweep.subdir` since that is created for each job so the configs are finalized.
