### ISSUE TITLE
Change tab completion from argparse to standard overrides

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#179]
```yaml
hydra:
   shell_completion:
      install: ???
      uninstall: ???
      query: ???
```
