### ISSUE TITLE
[Feature Request] Include config files into variables of other config files. (Question)

### ISSUE THREAD

**Issue by paudom** [facebookresearch/hydra#1796]
# 🚀 Feature Request

Hi! I was wondering if with Hydra 1.1 it's possible to include certain config files into variables of another config file. I've looked at the documentation [Extending Configs](https://hydra.cc/docs/patterns/extending_configs) but I can't figure out how to make it work for my use case. 

## Pitch

Giving more context, given the following folder structure:
```bash
├── conf
│   ├── foo
│   │   ├── foo1.yaml
│   │   └── foo2.yaml
│   ├── bar
│   │   └── bar1.yaml
│   └── config.yaml
└── test.py
```
And the following content on these files:
```yaml
# conf/config.yaml
defaults:
 - _self_
 - foo: foo2
 - bar: bar1

# conf/foo/foo1.yaml
a: 4
b: 5
c: 6

# conf/foo/foo2.yaml
f: 7
g: 3
h: 1
```

Is there any way (using extensions or interpolations), that in the `conf/bar/bar1.yaml` I could have a variable named `foo` under where I could 'copy' the same content as `conf/foo/foo1.yaml` like this:
```yaml
# conf/bar/bar1.yaml
foo:
 a: 4
 b: 5
 c: 6
```

I know that in the case of using `foo1` instead of `foo2` in the defaults list from the `config.yaml` file I could interpolate the values using:
```yaml
# conf/bar/bar1.yaml
foo: ${foo}
```
But in my use case, I want `foo` to be `foo2` by default while in `conf/bar/bar1.yaml` I would want a variable that is the same (including/copying) content as in `conf/foo/foo1.yaml`.

Thanks in advance!!

## Additional context
Using Hydra 1.1, OmegaConf 2.1, and Python 3.8

**Comment by Yevgnen** [comment]
@Jasha10 Hi, can I include it as a list item? e.g.

```yaml
---
foo:
  f: 7
  g: 3
  h: 1
bar:
  - a: 4
    b: 5
    c: 6
```

**Comment by Jasha10** [comment]
Hi @Yevgnen,
Hydra has first-class support for merging dicts together, but not for adding to lists.

There are some ways to achieve what you want (using [interpolation](https://omegaconf.readthedocs.io/en/2.1_branch/usage.html#variable-interpolation), e.g. `bar: ["${..my_temporary_variable}"]`), but these methods are difficult to work with. I'd recommend working with dictionaries if possible (instead of lists).

If you change `bar1.yaml` to look like this:
```yaml
# conf/bar/bar1.yaml
defaults:
  - /foo@0: foo1
```
Then you can get the following as output:
```text
$ python test.py
foo:
  f: 7
  g: 3
  h: 1
bar:
  '0':
    a: 4
    b: 5
    c: 6
```
This is using the string `"0"` so that the dictionary will be more similar to a list. Would something like that work for you?

**Comment by Yevgnen** [comment]
@Jasha10 My orignal X problem is trying to instantiate recursive objects like this [example](https://github.com/facebookresearch/hydra//blob/main/examples/instantiate/object_recursive/config.yaml) 

```yaml
car:
  _target_: my_app.Car
  driver:
    _target_: my_app.Driver
    name: James Bond
    age: 7
  wheels:
    - _target_: my_app.Wheel
      radius: 20
      width: 1
    - _target_: my_app.Wheel
      radius: 20
      width: 1
    - _target_: my_app.Wheel
      radius: 20
      width: 1
    - _target_: my_app.Wheel
      radius: 20
      width: 1
```

but my `wheels` are in other config group so I want to include them in `car`.

The real world example is [here](https://github.com/ashleve/lightning-hydra-template/blob/ab02996fd475dfdb882d64e77405e9a63bc03a73/src/train.py#L61). Since the logger [configs](https://github.com/ashleve/lightning-hydra-template/tree/ab02996fd475dfdb882d64e77405e9a63bc03a73/configs/logger) are [not included](https://github.com/ashleve/lightning-hydra-template/blob/ab02996fd475dfdb882d64e77405e9a63bc03a73/configs/trainer/default.yaml) in trainer, so one has to first instantiate the loggers then the trainer. I'm trying to find a way to get it work but not sure if it's idiomatic.

**Comment by Jasha10** [comment]
Aah, thanks for the context :)

I think you are confused about the lightning-hydra template -- you do not need a list of loggers, you need a dict of loggers. Take a look at line 54 from the link you gave:
`for _, lg_conf in config.logger.items(): ...`

The for loop is iterating over `config.logger.items()`. This means that `config.logger` should be a mapping, not a sequence.

Take a look also at the lightning-hydra [`many_loggers`](https://github.com/ashleve/lightning-hydra-template/blob/ab02996fd475dfdb882d64e77405e9a63bc03a73/configs/logger/many_loggers.yaml) config, as it is relevant to your use-case.
You can run the lightning-hydra template with many loggers like this:
```text
$ python run.py logger=many_loggers
```

---

For future reference, there is an idiomatic way to get a list of values from a mapping: you can use OmegaConf's [`oc.dict.values` resolver](https://omegaconf.readthedocs.io/en/latest/custom_resolvers.html#oc-dict-keys-value).

In `yaml`, that would look like this:
```yaml
# config.yaml
car:
  _target_: my_app.Car
  driver:
    _target_: my_app.Driver
    name: James Bond
    age: 7
  wheels: "${oc.dict.values: _wheel_dict}"  # gets values from _wheel_dict
_wheel_dict:
  wheel0:
    _target_: my_app.Wheel
    radius: 20
    width: 1
  wheel1:
    _target_: my_app.Wheel
    radius: 20
    width: 1
  wheel2:
    _target_: my_app.Wheel
    radius: 20
    width: 1
  wheel3:
    _target_: my_app.Wheel
    radius: 20
    width: 1
```
```python
# run_app.py
from omegaconf import OmegaConf, ListConfig

cfg = OmegaConf.load("config.yaml")
assert isinstance(cfg.car.wheels, ListConfig)
assert len(cfg.car.wheels) == 4
assert cfg.car.wheels[0].radius == 20
```
