### ISSUE TITLE
Run directory with Compose API

### ISSUE THREAD

**Issue by Valahaar** [facebookresearch/hydra#1810]
Hi!

Using the Compose API, how should I let Hydra change (and create) the run directory as if I called `@hydra.main()`?

In my config I have:
```yml
hydra:
  run:
    dir: ./experiments/${exp_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
```
In the code, I do 
```python
hydra.initialize(config_path="path/to/configurations")
conf = hydra.compose(config_name=config_name, overrides=overrides, return_hydra_config=True)
```

How to have `os.getcwd()` return `path/to/project/experiments/.../` instead of only `path/to/project`? (aside from creating & changing it manually using the loaded `conf.hydra.run.dir` attribute)

I did look through the issues and the docs but I'm afraid I missed it.

Thanks!
