### ISSUE TITLE
[Bug] delete field when using optuna sweeper would throw error

### ISSUE THREAD

**Issue by chris-tkinter** [facebookresearch/hydra#1811]
# 🐛 Bug
## Description

I was using optuna sweeper but I noticed that if i delete a field by `~field` it would throw an error.

## To reproduce
Let's [start with this](https://github.com/facebookresearch/hydra/tree/main/examples/advanced/defaults_list_interpolation). Let's modify `conf/db/sqlite.yaml` to be this
```yaml
name: sqlite

model:
  name: boring
```
then create a directory called `exp`, and create a file `exp/exp.yaml`
```yaml
# @package _global_

defaults:
  - override /hydra/sweeper: optuna
  - override /db: sqlite
```
Now run the command `python my_app.py -m +exp=exp ~db.model` it would have the error
> Could not delete from config. The value of 'db.model' is {'name': 'boring'} and not None.

However if I did `python my_app.py +exp=exp ~db.model` (not activating sweeper), then the code would run correctly, making the db to be sqlite (the default is mysql) and the `model.name` part deleted. 

## System information
- **Hydra Version** :  1.0.0.rc1
- **Python version** : 3.7.10
- **Operating system** : Ubuntu 18.04.2 LTS
