### ISSUE TITLE
How to use the defaults list to add/override an element in a ListConfig with a config group?

### ISSUE THREAD

**Issue by Chianugoogidi** [facebookresearch/hydra#1813]
I am trying to override an element of a list with a config group inside a config file. Here is an example to illustrate the issue:

**dataset/transform/train_preset.yaml**
```yaml
- name: RandomResizedCrop
  size: 224
- name: Normlize
  mean: [0, 0, 0]
  std: [1, 1, 1]
- name: ToTensor
```
**dataset/transform/eval_preset.yaml**
```yaml
- name: CenterCrop
  size: 224
- name: Normlize
  mean: [0, 0, 0]
  std: [1, 1, 1]
- name: ToTensor
```

**dataset/imagenet.yaml**
```yaml
defaults:
  - _self_
  - transform@split.0.transform: train_preset
  - transform@split.1.transform: eval_preset

name: imagenet
root: data/imagenet
split:
  - name: train
  - name: val
```

**config.yaml**
```yaml
defaults:
  - dataset: imagenet
```
**Code**
```python
import hydra
from omegaconf import OmegaConf, DictConfig

@hydra.main(config_path=".", config_name="config")
def main(cfg: DictConfig):
    print(OmegaConf.to_yaml(cfg))

if __name__ == "__main__":
    main()
```
**Current output**
```
Cannot merge DictConfig with ListConfig
    full_key: 
    object_type=dict

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
**Expected Output**
```
dataset:
  name: imagenet
  root: data/imagenet
  split:
    - name: train
      transform:
        - name: RandomResizedCrop
          size: 224
        - name: Normlize
          mean: [0, 0, 0]
          std: [1, 1, 1]
        - name: ToTensor
    - name: val
      transform:
        - name: CenterCrop
          size: 224
        - name: Normlize
          mean: [0, 0, 0]
          std: [1, 1, 1]
        - name: ToTensor
```
I'm likely not properly understanding how composition works. Some help would be appreciated. Thanks!

**Comment by omry** [comment]
I don't think this will work:
```yaml
defaults:
  - _self_
  - transform@split.0.transform: train_preset
  - transform@split.1.transform: eval_preset
```

Hydra is crating the missing nodes as dictionaries, which is likely why this fails for you (ListConfig and DictConfig cannot be merged).

Maybe using Structured Config for your primary config, you can describe dataset.split as `List[Something]`.
However, in general I recommend that you avoid lists when composing and opt to using dictionaries when possible.

Maybe trying to compose this will be easier:
```yaml
dataset:
  name: imagenet
  root: data/imagenet
  split:
    train:
      name: train
      transform:
        - name: RandomResizedCrop
          size: 224
        - name: Normlize
          mean: [0, 0, 0]
          std: [1, 1, 1]
        - name: ToTensor
    val:  
      name: val
      transform:
        - name: CenterCrop
          size: 224
        - name: Normlize
          mean: [0, 0, 0]
          std: [1, 1, 1]
        - name: ToTensor
```

**Comment by omry** [comment]
An alternative idea is to have config.yaml:
```yaml
defaults:
  - _self_
  - dataset: imagenet

dataset:
  split: [] # empty list
```
