### ISSUE TITLE
Support optuna.samplers.GridSampler

### ISSUE THREAD

**Issue by GillianGrayson** [facebookresearch/hydra#1815]
Hi!

I tried to use `optuna.samplers.GridSampler` for some model with this example:

```yaml
defaults:
  - override /hydra/sweeper: optuna

hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    storage: null
    study_name: null
    n_jobs: 1

    sampler:
      _target_: optuna.samplers.GridSampler
      search_space: {"model.n_d": [ 4, 8, 16 ]}
```
but I got this error:

```
Key 'search_space' not in 'TPESamplerConfig'
    full_key: hydra.sweeper.sampler.search_space
    reference_type=SamplerConfig
    object_type=TPESamplerConfig
```

It is strange, because I create GridSampler, not TPESampler.

## System information
- **Hydra Version** : 
hydra-core==1.1.0
hydra-optuna-sweeper==1.1.0 
- **Python version** : 3.8 
- **Operating system** : Windows 10
