### ISSUE TITLE
[Bug] ValueError: Config must be a Dictionary, got ConfigResult

### ISSUE THREAD

**Issue by robogast** [facebookresearch/hydra#1819]
# 🐛 Bug
## Description
I'm trying to extend the `submitit` plugin, which has a property called `setup`.  
Following this, I've created the following folder structure and config files (simplified for reproducibility purposes)
```
conf
|-hydra
  |-launcher
    |-custom_submitit.yaml
    |-setup
      |-custom_setup.yaml 
```
`custom_submitit.yaml`:
```yaml
defaults:
  - submitit_slurm
  - setup: custom_setup
```
`custom_setup.yaml`
```
- foo
- bar
```
Running `python <script.py> --cfg hydra` I would expect the resulting config to have:
```
hydra:
  launcher:
    <submitit_defaults>
    setup:
      - foo
      - bar
```

However, I get:
```python
ValueError: Config hydra/launcher/setup/custom_setup must be a Dictionary, got ConfigResult
```
## Circumventing the error
I can circumvent the error by changing the two configs as follows:
`custom_submitit.yaml`:
```yaml
defaults:
  - submitit_slurm
  - setup@_here_: custom_setup
```
`custom_setup.yaml`:
```yaml
setup:
  - foo
  - bar
```

## Considerations
Circumventing the error, from the config level, it now seems that `custom_setup` is an element of the `hydra/launcher`group, instead of `hydra/launcher/setup` group, which is not so nice.

To me this seems like an error on the `YAML` parse level, configs should be able to have only a root level list as content.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## System information
- **Hydra Version** :  1.1.1
- **Python version** :  3.8
- **Virtual environment type and version** :  conda/pip
- **Operating system** : Unix
