### ISSUE TITLE
[Bug] Unable to use OptunaSweeperConf using the Python API

### ISSUE THREAD

**Issue by mayeroa** [facebookresearch/hydra#1830]
# 🐛 Bug
## Description

Hi,

First of all, many thanks for that wonderful tool you've made. It is, for sure, extremely helpful to have it when production environment is necessary.
I have met an error/bug when I wanted to use the **OptunaSweeperConf** using the Python API (instead of using the traditional YAML files). 

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **

```python
# Standard libraries
from dataclasses import dataclass

# Third-party libraries
import hydra
from hydra.conf import HydraConf
from hydra.core.config_store import ConfigStore
from hydra_plugins.hydra_optuna_sweeper.config import OptunaSweeperConf
from omegaconf import DictConfig


@dataclass
class ExampleConfig():
    hydra: HydraConf = HydraConf(sweeper=OptunaSweeperConf())


ConfigStore.instance().store(name='config', node=ExampleConfig)


@hydra.main(config_path=None, config_name='config')
def main(config: DictConfig) -> None:
    """Main function."""
    print(config)


if __name__ == '__main__':
    main()

```

And the stack trace with the returned error:

** Stack trace/error message **
```
In 'config': Validation error while composing config:
Merge error: OptunaSweeperConf is not a subclass of BasicSweeperConf. value: {'_target_': 'hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper', 'defaults': [{'sampler': 'tpe'}], 'sampler': '???', 'direction': <Direction.minimize: 1>, 'storage': None, 'study_name': None, 'n_trials': 20, 'n_jobs': 2, 'search_space': {}}
    full_key: 
    object_type=dict

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

## Expected Behavior

I would like to override the hydra config group, directly into the structure config. To do so, I import the **HydraConf** from hydra and install the **hydra-optuna-sweeper** plugin.
The error seems to indicate that the **OptunaSweeperConf** must inherit from the **BasicSweeperConf** structured config (current implementation: https://github.com/facebookresearch/hydra/blob/v1.1.1/plugins/hydra_optuna_sweeper/hydra_plugins/hydra_optuna_sweeper/config.py#L133).
The idea is to be able to override hydra config group directly from a python script. Does that make sense?

## System information
- **Hydra Version** :  1.1.1
- **Hydra Optuna Sweeper Version** :  1.1.1
- **Python version** : 3.8.11
- **Virtual environment type and version** : MiniConda environment
- **Operating system** : LinuxMint

**Comment by jieru-hu** [comment]
hi @mayeroa  pls try using the defaults list instead. something like the following should work
```
@dataclass
class ExampleConfig():
    defaults: List[Any] = field(
        default_factory=lambda: [
            {"override hydra/sweeper": "optuna"},
        ]
    )

```

Run the application, you should see optuna's config
```
$python my_app.py --cfg hydra -p hydra.sweeper
# @package hydra.sweeper
sampler:
  _target_: optuna.samplers.TPESampler
  seed: null
  consider_prior: true
  prior_weight: 1.0
  consider_magic_clip: true
  consider_endpoints: false
  n_startup_trials: 10
  n_ei_candidates: 24
  multivariate: false
  warn_independent_sampling: true
_target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
direction: minimize
storage: null
study_name: null
n_trials: 20
n_jobs: 2
search_space: {}
```


Also the `cfg` object you get via `hydra.main` does not contain Hydra's config, to access the configs, try something like the following
```
@hydra.main(config_path=None, config_name='config')
def main(config: DictConfig) -> None:
    """Main function."""
    print(HydraConfig.get().sweeper)
```

**Comment by mayeroa** [comment]
Thank you for your answer @jieru-hu, it helps.
And if I want to override some parameters of the `OptunaSweeper` directly into the `ExampleConfig`, how should I proceed?

For example : 

```python
@dataclass
class ExampleConfig():
    defaults: List[Any] = field(
        default_factory=lambda: [
            {"override hydra/sweeper": "optuna"},
        ]
    )
# How to override n_trials?
# How to define search space?
```

**Comment by jieru-hu** [comment]
hi @mayeroa 

> And if I want to override some parameters of the OptunaSweeper directly into the ExampleConfig, how should I proceed?

We do have in detailed documentation on how you'd configure a plugin, pls check here https://hydra.cc/docs/patterns/configuring_plugins

> I think, it would be of great value to support such sweeper instantiation directly in python code. What do you think?

Essentially you want to override Hydra configuration here right? You can configure Hydra just like how you'd configure your application configuration. For example, you can write it in your config files, or override it from the commandline. 

```
# in your primary config
hydra:
  run:
     dir:
          ./my_dir

```
or from the commandline
```
hydra.run.dir=./my_dir
```

Hydra takes care of the config composition for you so you do not need to manage them yourself. I'd suggest go through our basic tutorial and the configure Hydra section of the doc if you have not already
https://hydra.cc/docs/next/tutorials/intro/
https://hydra.cc/docs/next/configure_hydra/intro
