### ISSUE TITLE
Composite multiple  config options from a group without using a explicit nested structure.

### ISSUE THREAD

**Issue by angshine** [facebookresearch/hydra#1833]
Hi, thanks for the great project! The Hydra document has already introduced a pattern for [Selecting multiple configs from a Config Group](https://hydra.cc/docs/patterns/select_multiple_configs_from_config_group/). However, this pattern requires users to manually build the explicit nesting level inside each config to prevent them from stepping over one another.

For example, the already proposed pattern organizes configs in a group like:
```yaml
# site/google.yaml
google:
  domain: google.com
``` 

```yaml
# site/fb.yaml
fb:
  domain: facebook.com
```

```yaml
# the default list for selecting multiple configs
defaults:
  - site:
    - fb
    - google
```

My question is, Is there a pattern to select multiple configs without explicitly organizing configs in a nested structure? 
For example:
```yaml
# site/google.yaml
_target_: google
domain: google.com
``` 

```yaml
# site/fb.yaml
_target_: fb
domain: facebook.com
```
I want to composite multiple configs into a list or a dict:
```yaml
# e.g., into a dict (which is not a proper syntax for now)
defaults:
  - site:
    - fb: fb
    - google: google
```
Is there a recommended pattern to achieve the objective mentioned above?

**Comment by omry** [comment]
You either need to add a nesting level:
```yaml
fb:
  _target_: fb
  domain: facebook.com
```

Or use the package header to specify the full package:
```
# @package site.fb
_target_: fb
domain: facebook.com
```

**Comment by Jasha10** [comment]
This works too:
```yaml
defaults:
  - site@fb: fb
  - site@google: google
```
