### ISSUE TITLE
[Bug] Recursive Instantiation with Tensorflow doesn't seem to take all the _args_ parameters

### ISSUE THREAD

**Issue by MathKlim** [facebookresearch/hydra#1845]
# 🐛 Bug
## Description

I've used Hydra for quite some time now with Tensorflow and it works great. Now I've tried to use the recursive instantiation property of hydra to create classifier heads for my models, I've followed [this tutorial](https://www.sscardapane.it/tutorials/hydra-tutorial/#variable-interpolation) and tried to adapt it to Tensorflow.

Basically I've tried to create as a toy example a classifier with 2 Dense layers (the  equivalent of a Linear layer in PyTorch) but it doesn't seem to work as my instantiated model only have one Dense layer instead of two (plus the input_layer). 

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

Here's a [GitHub repo](https://github.com/MathKlim/hydra_bug) for reproducibility. 

** Stack trace/error message **

The problem appears when I try to instantiate with hydra, see the result of the script `python src/classifier_bug.py` in the provided repo.

Here's the hydra config file for my instantiation.

```yaml
_target_: tensorflow.keras.models.Sequential
_args_:
  - _target_: tensorflow.keras.layers.Dense
    input_shape: [12]
    name: Dense1
    units: 32

  - _target_: tensorflow.keras.layers.Dense
    name: Dense2
    units: 32
```

## Expected Behavior

The expected behavior should be the one from `python src/classifier_right.py` in the provided repo, that is a neural network with two Dense layers.

## System information
- **Hydra Version** :  1.1.0
- **Tensorflow Version** :  2.5
- **Python version** :  3.8
- **Virtual environment type and version** :  miniconda 4.9.2
- **Operating system** :  Ubuntu 20.04 LTS

## Additional context

Compared to the PyTorch one, the `Sequential` version in TensorFlow takes **a list**, meaning that you have to write 

```python
classifier = tensorflow.keras.models.Sequential(
        [
            Dense_layer1,
            Dense_layer2,
        ]
    ) 
```

instead of 

```python
classifier =torch.nn.Sequential(
            Linear_layer1,
            Linear_layer2,
    ) 
```

So I'm wondering if this problem comes from that difference or not.

**Comment by omry** [comment]
In your example code, tensorflow is taking a list of layers as the first positional argument and torch is taking two position arguments.

Those two things are not the same.
If you want to pass a list through a positional argument try something like:
```yaml
_target_: tensorflow.keras.models.Sequential
_args_:
  -
    - _target_: tensorflow.keras.layers.Dense
      input_shape: [12]
      name: Dense1
      units: 32
    - _target_: tensorflow.keras.layers.Dense
      name: Dense2
      units: 32
```

Looking at https://www.tensorflow.org/api_docs/python/tf/keras/Sequential, it appears the the layers argument can also be passed as a named argument, so this might work as well:
```yaml
_target_: tensorflow.keras.models.Sequential
layers:
  - _target_: tensorflow.keras.layers.Dense
    input_shape: [12]
    name: Dense1
    units: 32

  - _target_: tensorflow.keras.layers.Dense
    name: Dense2
    units: 32
```

I did not test any of it with tf.

**Comment by MathKlim** [comment]
> In your example code, tensorflow is taking a list of layers as the first positional argument and torch is taking two position arguments.
> Those two things are not the same.

Yes, I agree, also I wasn't really sure if it wasn't a bug or not, since Hydra wasn't originally designed for tf.

I tried the two proposed synthaxes, and it ends with a tf error. Anyway, I was still able to do what I want, it's a bit rough, but it works.

To instantiate a TF Sequential model with Hydra, you can first define the layers with hydra.

```yaml
layers:
- _target_ : tensorflow.keras.layers.InputLayer
  input_shape: [12]
  name: input_layer

- _target_: tensorflow.keras.layers.Dense
  name: Dense1
  units: 32

- _target_: tensorflow.keras.layers.Dense
  name: Dense2
  units: 32
```
Now in your script, you define an empty Sequential model, and loop over the instantiated list of layers to add them, then you compile your model with the `Model` class.

```python
import hydra
from hydra.utils import instantiate
from omegaconf import DictConfig
from tensorflow.keras.models import Model, Sequential

@hydra.main(config_path="../configs/", config_name="params.yaml")
def main(config: DictConfig):
    model = Sequential()

    classifier = instantiate(config.test_)

    for layer in classifier.layers:
        model.add(layer)

    model = Model(
        inputs=model.input,
        outputs=model.output,
        name="classifier",
    )

    model.summary()

if __name__ == "__main__":
    main()
```
Still need to do some tests with layers like convolutional ones or pooling, but looks good.

Thanx for the answer.
