### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by kpoeppel** [facebookresearch/hydra#1846]
# 🚀 Feature Request

Add an \_unpack\_ keyword (like _target_), that unpacks a (potentially cited/interpolated) config into the current object.

## Motivation

Sometimes a configuration is copied for a specific number of instances. E.g. in machine learning the configuration for train, validation and test dataset will be mostly the same but might be different for a few things. This reduces copying around configurations.

## Pitch

Example:
```yaml
dataset_defaults:
  preprocessing: True
  format: 64

datasets:
  train:
    path: ${oc.env:TRAIN_DIR}
    _unpack_: ${...dataset_defaults}
  val:
    path: ${oc.env:VAL_DIR}
    _unpack_: ${...dataset_defaults}
```

that leads to an interpolated version:
datasets.train: {path: "$TRAIN_DIR", preprocessing: true, format: 64}
datasets.val: {path: "$VAL_DIR", preprocessing: true, format: 64} 

**Describe alternatives you've considered**
This might be possible via structuring of the configuration, but means also that the python code needs to be adapted as instantiations are not as easy anymore as the classes don't fit. 

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
I can try to adapt towards a PR.

**Comment by Jasha10** [comment]
Here is another version that unpacks a list and merges it's elements:
```python
# my_app.py
import hydra
from omegaconf import DictConfig, OmegaConf, open_dict, ListConfig

def unpack_merge(cfg: ListConfig):
    """Return the result of merging the elements of `cfg`."""
    assert isinstance(cfg, ListConfig) and len(cfg) >= 1, "cfg must be a non-emtpy ListConfig"
    with open_dict(cfg[0]):
        return OmegaConf.merge(*cfg)

OmegaConf.register_new_resolver("unpack_merge", unpack_merge)

@hydra.main(config_path=".", config_name="config")
def my_app(cfg: DictConfig) -> None:
    print(f"{cfg.datasets.train=}")
    print(f"{cfg.datasets.val=}")

if __name__ == "__main__":
    my_app()
```
```yaml
# config.yaml
dataset_defaults:
  preprocessing: True
  format: 64

datasets:
  train: ${oc.unpack_merge:${._train}}
  _train:
    - path: ${oc.env:TRAIN_DIR}
    - ${...dataset_defaults}

  val: ${oc.unpack_merge:${._val}}
  _val:
    - path: ${oc.env:VAL_DIR}
    - ${...dataset_defaults}
```

I am going to close this issue now as adding more specialized keywords to Hydra is a big commitment and there are ways to achieve the desired result using OmegaConf's resolvers.
