### ISSUE TITLE
SLURM sweep with hydra

### ISSUE THREAD

**Issue by slerman12** [facebookresearch/hydra#1859]
I try to sweep a set of hyperparams using the slurm submitit plugin.

I run:

`python run.py --multirun --config-name atari-slurm seed=1,2,3,4,5`

And my config file looks something like this:

```
defaults:
  - _self_
  - task@_global_: atari/breakout
  - override hydra/launcher: submitit_slurm

seed: 1

hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 4
    gpus_per_node: 4
    tasks_per_node: 4
    mem_gb: 160
    nodes: 2
    partition: gpu
#    gres: gpu:4
    cpus_per_gpu: 16
    gpus_per_task: 1
    constraint: K80
#    mem_per_gpu: null
#    mem_per_cpu: null
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm
```

However, I get this error:

```
raise InterpolationKeyError(f"Interpolation key '{inter_key}' not found")
omegaconf.errors.InterpolationKeyError: Interpolation key 'agent_cfg.experiment' not found
```

*I'm running this on a slurm cluster where we ordinarily use sbatch to submit jobs such as a multi-gpu job like the one defined in the config above.

**Comment by omry** [comment]
Take a look at your generated config to see that you have a node `agent_cfg.experiment`. Something like:
```
$ python run.py --cfg job --config-name atari-slurm
```

**Comment by slerman12** [comment]
Here is the output. I'm not seeing `agent_cfg.experiment`, but that config works with a `submitit_local` request.

```
atari                                                                           
frame_stack: 4                                                                  
action_repeat: 4                                                                
discount: 0.99                                                                  
num_train_frames: 100001                        
num_seed_frames: 1600
max_episode_frames: 27000
truncate_episode_frames: 400
eval_every_frames: 20000
num_eval_episodes: 10
save_snapshot: false
replay_buffer_size: ${num_train_frames}
replay_buffer_num_workers: 4
prioritized_replay: false
prioritized_replay_alpha: 0.6
nstep: 10
batch_size: 32
seed: 1
device: cuda
save_video: true
save_train_video: false
use_tb: true
experiment: exp
lr: 0.0001
adam_eps: 0.00015
max_grad_norm: 10.0
feature_dim: 50
agent:
  _target_: agents.Agent
  obs_shape: ???
  action_shape: ???
  discrete: ???
  device: ${device}
  lr: ${lr}
  adam_eps: ${adam_eps}
  max_grad_norm: ${max_grad_norm}
  critic_target_tau: 0.01
  min_eps: 0.1
  num_seed_frames: ${num_seed_frames}
  intensity_scale: 0.05
  double_q: true
  dueling: true
  use_tb: ${use_tb}
  num_expl_steps: 5000
  hidden_dim: 512
  feature_dim: ${feature_dim}
  prioritized_replay_beta0: 0.4
  prioritized_replay_beta_steps: ${num_train_frames}
stddev_schedule: linear(1.0,0.1,500000)
task_name: Breakout
```
