### ISSUE TITLE
[Feature Request] Interpolate cmd options before passing to override_dirname for sweep

### ISSUE THREAD

**Issue by thoth291** [facebookresearch/hydra#1872]
# 🚀 Feature Request

Hello, Team!

I can't figure out how to override current directory with jointly distributed sweeps. Here is what I'm trying to do:
```bash
simple_hydra_app '+sweep={name:rnd44,path:files},{name:rnd1230,path:files}' \
                                        files.submit.nmachines=6,10 \
                                        'case.name=${sweep.name}' \
                                        'case.path=${sweep.path}' \
                                        app.verbose=True -m
```

Here is what I have in my config.yaml:
```yaml
case:
  id: RUN
  name: rnd44
  path: files
files:
  submit:
    nmachines: 1

app:
  verbose: false

hydra:
  run:
    dir: ${hydra.job.name}/single/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${hydra.job.name} #_${hydra.job.id}
    subdir: ${hydra.job.num}_${hydra.job.override_dirname}
  job:
    name: ${case.id}
    override_dirname: ???
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: [sweep,app,app.verbose]
```
The problem with override dirname.
Instead of being interpreted it's taken literally (as you can see here - override dir is not properly interpreted.
```bash
#3 : +sweep={name:rnd1230,path:files} files.submit.nmachines=10 case.name=$\{sweep.name\} case.path=$\{sweep.path\} app.verbose=True
case:
  id: RUN
  name: rnd1230
  path: files

files:
  submit:
    nmachines: 10

app:
  verbose: true

sweep:
  name: rnd1230
  path: files

Current working directory  : /bla/bla/bla/RUN/3_case.name=$\{sweep.name\},case.path=$\{sweep.path\},files.submit.nmachines=10
Original working directory : /bla/bla/bla
to_absolute_path('foo')    : /bla/bla/bla/foo
to_absolute_path('/foo')   : /foo
```

So, really it boils down to one question:
- why `${sweep.name}` are not interpreted before pushing to `override_dirname` and how to make it happen?

Any advise would be very helpful!
Any pointers to examples or docs would be much appreciated.

## Motivation

Anyone who takes command line seriously - should benefit from this feature.
It will also synchronize behavior between config files and command-line options.

## Pitch

**Describe the solution you'd like**
It wold be great to make it interpret it as such in the given example:
```bash
#given that `case.name=rnd1230` and `case.path=files` below line
/bla/bla/bla/RUN/3_case.name=$\{sweep.name\},case.path=$\{sweep.path\},files.submit.nmachines=10
#should be interpolated into
/bla/bla/bla/RUN/3_case.name=rnd1230,case.path=files,files.submit.nmachines=10
#by override_dirname
```

**Describe alternatives you've considered**
Using configuration files is an option. And I'm already using it when I need to.
But that doesn't change behavior of `override_dirname` and for some simple cases as illustrated in here - configuration file is overkill.

**Are you willing to open a pull request?**
I contributed to this project in the past - but I it was too long time ago - so I'm not familiar with the project - and I was not particularly efficient.
So I would say, no.

## Additional context
I can take workaround as long as that won't require me to change more than one central config.yaml file or custom python hook which would correct this behavior.
What I mean is that - user should experiment as much as he/she wants from command line - and I don't want limit their experience by asking to create another set of configfiles to facilitate their needs.

Thank you for your understanding!
And thanks in advance!

**Comment by Jasha10** [comment]
I think this behavior is intentional.
The motivation is that having `"case.name=${sweep.name}"` in the override directory name (instead of e.g. `"case.name=rnd44"`) is less ambiguous:
  - if `"case.name=${sweep.name}"` appears in the dir name, it is clear that `case.name=${sweep.name}` was passed at the command line.
  - if instead the interpolation were resolved before calculating the directory name, e.g. if `"case.name=rnd44"` were to appear in the dir name, then it would not clear (by looking at the directory name) what override had been passed at the command line (it might have been `case.name=rnd44`, or `case.name=${sweep.name}`, or possibly some other interpolation).

The current behavior makes it easier to precisely reconstruct the command that was passed at the command line.

**Comment by Jasha10** [comment]
You can always tweak `hydra.sweep.subdir` to achieve more specific behavior:
```yaml
hydra:
  sweep:
    subdir: ${hydra.job.num}_${hydra.job.override_dirname}_case.name=${case.name}_case.path=${case.path}
  job:
    config:
      override_dirname:
        exclude_keys: [sweep,app,app.verbose,case.name,case.path]
```
This tweaking could potentially be automated using custom resolvers.

**Comment by thoth291** [comment]
@Jasha10, thank you for your help!
I would say that above would solve this instance of the problem and not the root issue (un-interpreted override_dirname).
The thing is that I can decide to sweep over some other parameters - and overriding subdir each time to customize behavior is extra work which should be automated by override_dirname being interpolated before used.
Does it makes sense? Or I'm missing some other context?

**Comment by Jasha10** [comment]
Yes, this makes sense...

After doing some digging, I found a small change that will make a big difference.
Using your original example, instead of this:
```text
simple_hydra_app '+sweep={name:rnd44,path:files},{name:rnd1230,path:files}' \
                                        files.submit.nmachines=6,10 \
                                        'case.name=${sweep.name}' \
                                        'case.path=${sweep.path}' \
                                        app.verbose=True -m
```
try this:
```text
simple_hydra_app '+sweep={name:rnd44,path:files},{name:rnd1230,path:files}' \
                                        files.submit.nmachines=6,10 \
                                        'case.name="${sweep.name}"' \
                                        'case.path="${sweep.path}"' \
                                        app.verbose=True -m
```
The quotes around the `"${sweep.name}"` and `"${sweep.path}"` strings prevent mean that the brackets will not be backslash-escaped, so `override_dirname` will contain the resolved values.

**Comment by thoth291** [comment]
So I did my test and now I get my directory in much more pleasant way:
- for this - `simple_hydra_app '+sweep={name:rnd44,path:files,nmach=20},{name:rnd1230,path:files,nmach=30}' files.submit.nmachines="${sweep.nmach}" 'case.name="${sweep.name}"'  'case.path="${sweep.path}"'  -m`
- I get this - `'/bla/bla/1_case.name="rnd",case.path="files",files.submit.nmachines="20"'`

Wile this is definitely works - I'm a bit confused by `"` around the values after resolving.
Is there any way to avoid it?

Thank you, again, @Jasha10 , for looking into my issues - I really appreciate for your help!

**Comment by Jasha10** [comment]
The default behavior here is to create an output directory name by minimally processing the inputs that were passed at the command line; the quotes are showing up in the output directory name for this reason.

Please give this a try:
```yaml
# in config.yaml
hydra:
  sweep:
    subdir: ${hydra.job.num}_${remove_quotes:${hydra.job.override_dirname}}
```
```python
# in simple_hydra_app.py
def remove_quotes_impl(string: str) -> str:
    return string.replace('"', "")
OmegaConf.register_new_resolver("remove_quotes", remove_quotes_impl)
```

**Comment by omry** [comment]
Sorry for the long delay in resolving this.

This is now fixed by [PR #3241](https://github.com/facebookresearch/hydra/pull/3241), which introduced the lazy `hydra_override_dirname` resolver. You can use it directly in the sweep directory pattern:

```yaml
hydra:
  sweep:
    subdir: '${hydra.job.num}_${hydra_override_dirname:}'
```

With an override such as `case.name=${sweep.name}`, the resolver now evaluates the interpolation against the composed job config. The resulting directory name contains the resolved value, such as `case.name=rnd1230`, without requiring the quoting and custom resolver workaround discussed above.

`hydra.job.override_dirname` is deprecated in Hydra 1.4, so new configurations should use `${hydra_override_dirname:}` directly. See the [working directory documentation](https://hydra.cc/docs/next/configure_hydra/workdir/#using-hydra_override_dirname) for customization options.

Closing as fixed for Hydra 1.4.
