### ISSUE TITLE
Change config of other file

### ISSUE THREAD

**Issue by shim94kr** [facebookresearch/hydra#1879]
Hello. Thank you for a great repository.
I wonder if it is possible to change the config of another file as below.
(The implementation below does not work currently, though.)

I am building a data loader with separate transformation modules.
Since data statistics depend on a dataset, not a transform module itself, I need the feature of specifying the statistics outside the transformation configs.
Can you provide a workaround for my use case or a reference related to my issue? 

```
_target_: src.datamodules.mnist.MNIST
defaults:
  - transforms: normalize.yaml
transforms/mean: 0.1307
transforms/std: 0.3081
```

Thank you!!

**Comment by Jasha10** [comment]
Hi @shim94kr,

Does this work for you?
```yaml
_target_: src.datamodules.mnist.MNIST
defaults:
  - transforms: normalize.yaml
transforms:
  mean: 0.1307
  std: 0.3081
```
