### ISSUE TITLE
about indirect interpolation

### ISSUE THREAD

**Issue by shim94kr** [facebookresearch/hydra#1883]
Hello! 

Can multiple variables be interpolated in single pass through indirect connection on other variable?

The code below is my first trial on this where A1 and A2 of Avar are expected to be 1 1.
But the results are 0 0 as of default values.

**base.yaml**
```
# @package _global_
A:
    B: 0
    A1: ${A.B}
    A2: ${A.B}
A.B: 1
```

**config.py**
```
from omegaconf import DictConfig, OmegaConf

import hydra
from hydra.utils import instantiate

@hydra.main(config_path="./config", config_name="base")
def my_app(cfg: DictConfig) -> None:
    A = instantiate(cfg.A)
    print(OmegaConf.to_yaml(cfg))
    print(A.A1, A.A2)


if __name__ == "__main__":
    my_app()

```

Is there any way to interpolate the values in indirect way?

Thank you !

**Comment by Jasha10** [comment]
Hi,
I think this may be related to the use of a period '.' in your key names. The following config gives the expected result 1 1:
```
A:
    B: 0
    A1: ${A_B}
    A2: ${A_B}
A_B: 1
```

**Comment by shim94kr** [comment]
Thank you for the response.
But I think the question was oversimplified and misled you. Sorry for the confusion.

What of my original intention is to copy A to its variations (Avar1, Avar2..) but with different attributes (op1 and op2) of it, where these are controlled by the representative attribute (B).
Since the attributes are many (op1, op2 ...), I want to change them with just the representative (B).

Is there a way to achieve this?
**What is suggested gives an error,**
# @package _global_
A:
    B: 0
    op1: ${A_B}
    op2: ${A_B}

Avar1: ${A}
Avar1_B: 1 or A_B: 1

Avar2: ${A}
Avar2_B: 2 or A_B: 2

**and its modification outputs 0 0 for Avar1.op1 and Avar1.op2 as before whose expected outputs are 1 1.**
# @package _global_
A:
    B: 0
    op1: ${.B}
    op2: ${.B}

Avar1: ${A}
Avar1_B: 1

Avar2: ${A}
Avar2_B: 2

**Comment by shim94kr** [comment]
I found an answer!

After creating a template folder,
|---- base.yaml
|---- A
       |---- A_template.yaml

I wrote down the code as below.
**A_template.yaml**
```
B: 0
op1: ${.B}
op2: ${.B}
```

**base.yaml**
```
# @package _global_

defaults:
  - A@Avar1: A_template
  - A@Avar2: A_template

Avar1:
    B: 1

Avar2:
    B: 2
```

Then it works! This uses the functionality of extension from other config group (https://hydra.cc/docs/next/patterns/extending_configs/)
Closing this issue : )
