### ISSUE TITLE
Issue on interpolating functools.partial method

### ISSUE THREAD

**Issue by shim94kr** [facebookresearch/hydra#1895]
Hello. Thank you for providing a useful functionality like calling partial method based on [#1283](https://github.com/facebookresearch/hydra/issues/1283)

But I found the interpolation does not work for this one raising an error "omegaconf.errors.UnsupportedInterpolationType: Unsupported interpolation type get_method".

```
opt:
  _target_: functools.partial
  _args_: ["${get_method:get_method:torch.optim.SGD}"]
  
opt2: ${.opt}
```

```
from omegaconf import DictConfig, OmegaConf

import hydra
from hydra.utils import instantiate

@hydra.main(config_path="./config", config_name="base")
def my_app(cfg: DictConfig) -> None:
    opt2 = instantiate(cfg.opt2)
    print(OmegaConf.to_yaml(cfg))
    print(opt2)


if __name__ == "__main__":
    my_app()
```
In my case, it is needed when multiple datasets have their own optimizers and a model takes them one-by-one.
I checked only the file defining the optimizer can be taken through default list, but this isolation of optimizer from others in the data configuration, which are not related to the model configuration, is not desirable since it makes the configure files messy.

Is there any way to interpolate partial method through ${} operation not through the default list?

Thank you!!

**Comment by Jasha10** [comment]
Hi @shim94kr,

I think you have a typo in your resolver:
It should be `"${get_method:torch.optim.SGD}"` instead of `"${get_method:get_method:torch.optim.SGD}"`.

**Comment by shim94kr** [comment]
Sorry for the typo.  But the fixed one does not work neither. 
```
opt:
  _target_: functools.partial
  _args_: ["${get_method:torch.optim.SGD}"]


opt2: ${.opt}
```

**Comment by Jasha10** [comment]
You need to register the [custom resolver](https://omegaconf.readthedocs.io/en/2.1_branch/custom_resolvers.html) `get_method`:

```python
# app.py
from omegaconf import DictConfig, OmegaConf

import hydra
from hydra.utils import instantiate

OmegaConf.register_resolver("get_method", hydra.utils.get_method)

@hydra.main(config_path="./config", config_name="base")
def my_app(cfg: DictConfig) -> None:
    opt2 = instantiate(cfg.opt2)
    print(OmegaConf.to_yaml(cfg))
    print(opt2)

if __name__ == "__main__":
    my_app()
```
```
# config/base.yaml
opt:
  _target_: functools.partial
  _args_: ["${get_method:torch.optim.SGD}"]
  
opt2: ${.opt}
```
At the command line:
```text
$ python3 app.py
opt:
  _target_: functools.partial
  _args_:
  - ${get_method:torch.optim.SGD}
opt2: ${.opt}

functools.partial(<class 'torch.optim.sgd.SGD'>)
```

**Comment by shim94kr** [comment]
Ah.. right... I appreciate your effort to resolve the issue.
In fact, I observe in my project the error given with the following snippet.

'omegaconf.errors.UnsupportedValueType: Value 'SGD' is not a supported primitive type'

```
opt:
  _target_: functools.partial
  _args_: ["${get_method:torch.optim.SGD}"]

opt2: 
  opt: ${..opt}
```

```
@hydra.main(config_path="./config", config_name="base")
def my_app(cfg: DictConfig) -> None:
    opt2 = instantiate(cfg.opt2)
    print(OmegaConf.to_yaml(cfg))
    print(opt2)
```

Since it was the first time encountering this error and assumed it was unsupported in hydra, I so haste to check whether it is supported.
But, I found the error also came with my fault (I didn't call cfg.opt2.opt at cfg.opt2).

Anyway, .. thank you so much for your as. I'm closing this issue:)
