### ISSUE TITLE
[Feature Request] Mixing `_global_` / `_here_` / `_package_`

### ISSUE THREAD

**Issue by YannDubs** [facebookresearch/hydra#1913]
# 🚀 Feature Request

Allow the use of packages inise of the `yaml`. E.g.

```
# this is local
is_local: True

_global_: # Special keyword that says that it's global
  outside:
    is_global: True
```

or equivalently 

```
# @package _global_

# this is local
_here_: # Special keyword that says that it's local
  is_local: True

# this is global because it's the default package
outside:
  is_global: True
```

## Motivation

I often reuse a lot of my configs for different parts of the programs to avoid duplicating code, so I often use something like `X@Y:  Z` but currently I don't really know how to deal with cases where `Z` has to make global and local changes.  Because if I use `# @package _global_` then I can't change locally `Y` but if I use the default package I can't change global configs.
