### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Jasha10** [facebookresearch/hydra#1951]
Currently Hydra's defaults list support two special keywords: `optional` and `override`, as described in the [defaults list](https://hydra.cc/docs/next/advanced/defaults_list/) docs.

If a keyword (`optional` or `override`) is misspelled, it is silently ignored.
For example, the following two defaults lists are equivalent:
```yaml
defaults:
  - dataset: imagenet
  - model: alexnet
  - optioal dataset_model: ${dataset}_${model}  # "optional" misspelled

# equivalent:
defaults:
  - dataset: imagenet
  - model: alexnet
  - dataset_model: ${dataset}_${model}  # "optional" omitted
```
(The above is based on [this example](https://github.com/facebookresearch/hydra/blob/e0373f9c801f62c13ae37410e690b3150bc0f6e2/examples/patterns/specializing_config/conf/config.yaml))

# 🐛 Bug
## Description
Hydra silently drops the misspelled keyword(s) and creates a config based on the incorrect defaults list.

## Expected Behavior
Hydra should fail fast with a clear error message saying that an unsupported keyword was used.
