### ISSUE TITLE
[Feature Request] Copying a config field between different branches in one config

### ISSUE THREAD

**Issue by jbaczek** [facebookresearch/hydra#1983]
# 🚀 Feature Request

I need a simple syntax to overwrite/add a config field in an arbitrary branch of the config with field present in the current conifg.

## Motivation

Lets assume the case: I have model that can be trained with 2 different loss functions: MAE and quantile loss. MAE loss takes a one dimensional prediction vector as an input, but quantile loss is parameterized with a vector of floats. Model has to be aware of the number of outputs which it has to produce.
My program uses recursive instantiation (which is great by the way!) so my config has structure that places loss function on a different branch of the config than model. So the config structure looks like this:
```
trainer:
    model:
        _target_: model.lstm
        model_arg1: 1
        ...
    criterion:
        _target_: crit.quantile
        crit_arg1: 1
    ...
```
I use config groups to assemble the final config so my quantile loss config looks like this:
```
_target_: criterion.QuantileLoss
quantiles: [0.1, 0.5, 0.9]
```

I don't want to add additional args like `+trainer.model.quantiles=... +trainer.criterion=quantile` every time I use quantile loss. One of the possible solutions I found was to make overrides config group and import field `quantiles` from it. Which results in config like this
```defaults:                                             
        - overrides@_here_: quantile_overrides        
        - overrides@_global_.trainer.model: quantile_overrides
_target_: criterion.QuantileLoss                      
```
And the `overrides/quantile_overrides.yaml` file contains only `quantiles: [0.1, 0.5, 0.9]`. This is fine if there is a single value in the single class to add, but this approach is not scalable.

## Pitch

I want to have an easy way to copy a config field between different branches of the config. Preferably I want the syntax to look like this:
```defaults:                                             
        - _self_.quantiles@_global_.trainer.model
_target_: criterion.QuantileLoss
quantiles: [0.1, 0.5, 0.9]                      
```

I could not find a hint in the documentation how to do this. I'd like at least a temporary workaround for this issue. Thanks!

**Comment by Jasha10** [comment]
Thanks for the writeup @jbaczek. This (in addition to #1913) is a good datapoint for possible ergonomics improvements to Hydra.

I can offer a slight improvement over your approach using `overrides@_global_: quantile_overrides` in the defaults list: You can get away without an additional level of directory nesting (refer to the [defaults list grammar](https://hydra.cc/docs/advanced/defaults_list/)).

#### Before
```text
$ tree criterion/
criterion/
├── overrides
│   └── quantile_overrides.yaml
└── quantile_loss.yaml
```
```yaml
# criterion/quantile_loss.yaml
defaults:
  - overrides@_here_: quantile_overrides
  - overrides@_global_.trainer.model: quantile_overrides
_target_: criterion.QuantileLoss
```
#### After
```text
$ tree criterion/
criterion/
├── quantile_overrides.yaml
└── quantile_loss.yaml
```
```yaml
# criterion/quantile_loss.yaml
defaults:
  - quantile_overrides@_here_
  - quantile_overrides@_global_.trainer.model
_target_: criterion.QuantileLoss
```

**Comment by jbaczek** [comment]
Thanks for the hint! I already tried this one and came to the conclusion that this is not the best design for my case. In the same config group I have different criterions and I wanted to distinguish between actual criterion classes and fields which they override. I'm looking forward to see ergonomics upgrades in hydra!

**Comment by Jasha10** [comment]
Here's an idea:
In `quantile_loss.yaml`, you want to set the value `[0.1, 0.5, 0.9]` in two places:
  - in `trainer.model.quantiles`, and
  - in `trainer.criterion.quantiles`.
The common ancestor of these two `trainer`. Thus, it makes sense to use an [`@package` directive](https://hydra.cc/docs/advanced/overriding_packages/#overriding-the-package-via-the-package-directive) specifying `trainer` as the package for `quantile_loss.yaml`:
```yaml
# @package trainer
# criterion/quantile_loss.yaml
criterion:
  _target_: criterion.QuantileLoss
  quantiles: [0.1, 0.5, 0.9]
model:
  quantiles: ${..criterion.quantiles}  # relative interpolation
  # quantiles: ${trainer.criterion.quantiles}  # absolute interpolation
```
```yaml
# conf.yaml
defaults:
  - criterion: quantile_loss
trainer:
    model:
        _target_: model.lstm
        model_arg1: 1
```
```text
$ tree config
config
├── conf.yaml
└── criterion
    └── quantile_loss.yaml
```

Running this gives the expected config
```yaml
trainer:
  criterion:
    _target_: criterion.QuantileLoss
    quantiles:
    - 0.1
    - 0.5
    - 0.9
  model:
    quantiles: ${..criterion.quantiles}
    _target_: model.lstm
    model_arg1: 1
```
which resolves nicely
```yaml
trainer:
  criterion:
    _target_: criterion.QuantileLoss
    quantiles:
    - 0.1
    - 0.5
    - 0.9
  model:
    quantiles:
    - 0.1
    - 0.5
    - 0.9
    _target_: model.lstm
    model_arg1: 1
```

**Comment by Jasha10** [comment]
Alternatively, if you know that `trainer.model.quantiles` will always point to `trainer.criterion.quantiles` (regardless of which criterion is selected), you could simply define the interpolation when writing your model:
```yaml
# conf.yaml
defaults:
  - criterion: quantile_loss
trainer:
    model:
        _target_: model.lstm
        model_arg1: 1
        quantiles: ${..criterion.quantiles}
```
