### ISSUE TITLE
Feature Request: allow interpolated config to use "override" keyword

### ISSUE THREAD

**Issue by Jasha10** [facebookresearch/hydra#1989]
This feature request describes a possible enhancement to Hydra's interpolation support in defaults lists, namely enabling limited use of the "`override`" keyword within defaults lists of configs that are loaded via [defaults list interpolation](https://hydra.cc/docs/advanced/defaults_list/#interpolation-in-the-defaults-list).

Hydra supports interpolations in its defaults lists:
```yaml
defaults:
  - model: ModelA
  - dataset: DatasetA
  - model_dataset: ${model}_${dataset}
```
Assuming that the choices `model: ModelA` and `dataset: DatasetA` are not overridden, the above is mostly equivalent to the following:
```yaml
defaults:
  - model: ModelA
  - dataset: DatasetA
  - model_dataset: ModelA_DatasetA
```
One difference between the above two defaults lists is that, in the first case, it would be disallowed for the config `ModelA_DatasetA.yaml` to use the `override` keyword in its defaults list.

The primary reason for this restriction is that, if the config `ModelA_DatasetA.yaml` defines an override, that override may affect the result of the interpolation `${model}_${dataset}`, leading to undefined behavior.

In theory, I think it would be possible to allow an interpolated config (e.g. `ModelA_DatasetA.yaml`) use the "override" keyword in its defaults list (with well-defined behavior) so long as the new override does not affect whether ModelA_DatasetA (or any of it's ancestors) are to be included in the defaults tree.

Context: based on [my comment on #1971](https://github.com/facebookresearch/hydra/issues/1971#issuecomment-1016991362_)
