### ISSUE TITLE
Question: How to implement CLI shortcuts for nested configs?

### ISSUE THREAD

**Issue by jbaczek** [facebookresearch/hydra#2022]
So far I have resolved tons of config management issues with OmegaConf's custom resolvers. It isn't the neatest solution but from the user perspective it gets the job done. But there is one thing that I cannot do: I want to create shortcut(alias) in the top level config that will be resolved to a full path. Example:
```
trainer:
    criterion:
        _target_: [...]
        arg: 1337
    config:
        batch_size: 32
```
Typing `python hydra_app.py trainer.config.batch_size=32 trainer/criterion=L1` is really cumbersome. I'd like to type this interchangeably: `python hydra_app.py batch_size=32 criterion=L1`. Is there any possibility to do this?

**Comment by pixelb** [comment]
I'm not sure that could be achieved from a general point of view.
One might have a search mechanism, but that would be very brittle if the config was changed, thus causing other items to be matched.

**Comment by Jasha10** [comment]
At least for `batch_size`, wouldn't [interpolation](https://omegaconf.readthedocs.io/en/latest/usage.html#variable-interpolation) to a top-level key do the trick?
```yaml
trainer:
    criterion:
        _target_: [...]
        arg: 1337
    config:
        batch_size: ${batch_size}
batch_size: 32
```
This would allow `python hydra_app.py batch_size=64`.

**Comment by jbaczek** [comment]
This solution would leave `batch_size` in the root level config. I want to keep my final config tidy (I use it for recursive instantiation).

**Comment by Jasha10** [comment]
Got it. In that case, the only workaround I can think of are:
- deleting the "aliases" before instantiating, or
- using the root level as a "scratch space", and having the instantiated config be nested one level deeper.

#### deleting the top-level "aliases" before instantiating:
```python
aliases: List[str] = ["batch_size"]

@hydra.main(...)
def app(cfg):
    for alias in aliases:
        if alias in cfg:
            del cfg[alias]
    instantiate(cfg)
```

#### using the root level as a "scratch space":
```yaml
instantiate_me:
  trainer:
      criterion:
          _target_: [...]
          arg: 1337
      config:
          batch_size: ${batch_size}
# scratch:
batch_size: 32
```
```python
@hydra.main(...)
def app(cfg):
    instantiate(cfg.instantiate_me)
```
