### ISSUE TITLE
[Feature Request] Nested interpolation in YAMLs

### ISSUE THREAD

**Issue by NatanBagrov** [facebookresearch/hydra#2043]
# 🚀 Feature Request

Interpolate a key within a key

## Motivation
I have a config with the following dictionary:

```yaml
anchors:
  coco2014:
    224:
        data: [1,2,3]
    512:
        data: [2,3,4]
  coco2017:
    224:
        data: [3,4,5]
    512:
        data: [4,5,6]
```

What I want to do is:
`anchors: ${anchors.${dataset}.${resolution}.data}`

Didn't manage to achieve it :(
Maybe this practice is bad by-design. If so, please suggest a better practice.
Eventually, I want the dataset and resolution to be *coupled*, so that in cases when one changes -- this config still holds and the proper anchors are used.

**Comment by tesfaldet** [comment]
Here's a snippet of how I configure my experiments with different datasets, which might help you with your roadblock. Below is my `./conf/config.yaml` file.

```yaml
defaults:
  - _self_
  - dataset: mnist
  - model: VAE

experiment:
  name: mnist_default
  device: cuda:0
  save_root: /home/mattie.tesfaldet/scratch/results
  num_workers: 6  # for pytorch Dataloader

  opt:
    lr: 1e-3
    type: adam

  iter:
    train:
      start: 1
      total: 100000

  batch_size:
    train: 32
    val: 32

  input_size:
    train: [28, 28]
    val: [28, 28]

  log_frequency: 10
  save_frequency: 1000
  val_frequency: 5000

  random_seed: 1

hydra:
  run:
    dir: ${experiment.save_root}/${experiment.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
```

`./conf/model/vae.yaml`:
```yaml
_target_: src.models.VAE
name: VAE
depth: 1
hidden_chns: 12
```

`./conf/dataset/mnist.yaml`:
```yaml
name: MNIST
dataset_root: /home/mattie.tesfaldet/scratch
```

`./conf/experiment/mnist_small.yaml`:
```yaml
# @package _global_
defaults:
  - override /dataset: mnist

experiment:
  name: mnist_small

  batch_size:
    train: 64
    val: 64

  input_size:
    train: [20, 20]
    val: [20, 20]
```

`./conf/experiment/mnist_large.yaml`:
```yaml
# @package _global_
defaults:
  - override /dataset: mnist

experiment:
  name: mnist_large

  batch_size:
    train: 16
    val: 16

  input_size:
    train: [64, 64]
    val: [64, 64]
```

`./conf/dataset/fashion_mnist.yaml`:
```yaml
name: FashionMNIST
dataset_root: /home/mattie.tesfaldet/scratch
```

`./conf/experiment/fashion_mnist.yaml`:
```yaml
# @package _global_
defaults:
  - override /dataset: fashion_mnist

experiment:
  name: fashion_mnist

  batch_size:
    train: 32
    val: 32

  input_size:
    train: [28, 28]
    val: [28, 28]
```

`./conf/experiment/fashion_mnist_small.yaml`:
```yaml
# @package _global_
defaults:
  - override /dataset: fashion_mnist

experiment:
  name: fashion_mnist_small

  batch_size:
    train: 64
    val: 64

  input_size:
    train: [20, 20]
    val: [20, 20]
```

`./conf/experiment/fashion_mnist_large.yaml`:
```yaml
# @package _global_
defaults:
  - override /dataset: fashion_mnist

experiment:
  name: fashion_mnist_large

  batch_size:
    train: 16
    val: 16

  input_size:
    train: [64, 64]
    val: [64, 64]
```

Here's how I'd run each experiment:
- `mnist_default` --> `python train.py`
- `mnist_small` --> `python train.py +experiment=mnist_small`
- `mnist_large` --> `python train.py +experiment=mnist_large`
- `fashion_mnist` --> `python train.py +experiment=fashion_mnist`
- `fashion_mnist_small` --> `python train.py +experiment=fashion_mnist_small`
- `fashion_mnist_large` --> `python train.py +experiment=fashion_mnist_large`

Multiple experiments in succession:
- `fashion_mnist, fashion_mnist_small, fashion_mnist_large` --> `python train.py +experiment=fashion_mnist,fashion_mnist_small,fashion_mnist_large`

What if I wanted to use the submitit plugin and the nevergrad plugin so that I could launch multiple experiments in parallel (a hyperparam sweep) in a SLURM cluster? Check this out:
`./conf/experiment/slurm_remote.yaml`:
```yaml
# @package _global_
defaults:
  # Hydra's launcher API is synchronous and not async https://github.com/facebookresearch/hydra/issues/1377#issuecomment-773583397 so all jobs in a batch must finish before launching next batch
  - override /hydra/launcher: submitit_slurm

hydra:
  sweep:
    dir: ${experiment.save_root}/${experiment.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}_${hydra.job.id}
  launcher:
    # uses job array for submitting multiple tasks under a single job, each having the below config and not sharing resources between each other
    timeout_min: 60
    partition: long
    cpus_per_task: ${experiment.num_workers}  # task = process, cpus = threads if hyperthreading enabled
    gres: gpu:rtx8000:1
    nodes: 1
    tasks_per_node: 1  # num of tasks to spawn in each node (will repeat each task in a job array in each node)
    mem_gb: 12  # RAM per node (not GPU memory) in GB
    array_parallelism: 256  # max num of tasks to run in parallel (via job array) with above config
    additional_parameters:
      time: 0-12:00:00  # maximum wall time allocated for the job (D-H:MM:SS)

    # Change this only after you confirmed your code can handle re-submission
    # by properly resuming from the latest stored checkpoint.
    # check the following for more info on slurm_max_num_timeout
    # https://github.com/facebookincubator/submitit/blob/master/docs/checkpointing.md
    # checkpointed and requeued at most max_num_timeout times if timed out (and any number of time if preempted)
    max_num_timeout: 3

    # A list of commands to run in sbatch befure running srun
    setup:
      - ulimit -Sn $(ulimit -Hn)  # avoids hitting max num-open-file-descriptors limit since these jobs are accessing the same shared resource aka the dataset located in /home/mattie.tesfaldet/scratch
```
`./conf/experiment/sweep.yaml`:
```yaml
# @package _global_
defaults:
  - override /hydra/sweeper: nevergrad

hydra:
  sweeper:
    optim:
      # name of the Nevergrad optimizer to use. Here is a sample:
      #   - "OnePlusOne" extremely simple and robust, especially at low budget, but
      #     tends to converge early.
      #   - "CMA" very good algorithm, but may require a significant budget (> 120)
      #   - "TwoPointsDE": an algorithm good in a wide range of settings, for significant
      #     budgets (> 120).
      #   - "NGOpt" an algorithm aiming at identifying the best optimizer given your input
      #     definition (updated regularly)
      # find out more within nevergrad's documentation:
      # https://github.com/facebookresearch/nevergrad
      optimizer: NGOpt
      budget: 200  # total number of function evaluations to perform
      num_workers: 25  # number of parallel workers for performing function evaluations
      noisy: false  # noisy setting, typically as in reinforcement learning
      maximize: false  # use if you want to find params that maximize train fn output
      seed: ${experiment.random_seed}
      # max_failure_rate: 0.0  # maximum authorized failure rate for a batch of parameters
    parametrization:
      experiment.batch_size.train:
        - 16
        - 32
        - 64
        - 128
      model.hidden_chns:
        lower: 8
        upper: 128
        integer: true
```
For running the hyperparam search I type --> `python train.py --multirun +experiment=[fashion_mnist,remote,sweep]`
Notice how with `[ ]` brackets wrapped around the different experiments, it merges them together into one experiment and overrides the defaults in `./conf/config.yaml`. This is in contrast with above where if you wanted to run multiple experiments in succession, you wouldn't use the `[ ]` brackets. However, if you'd want to run multiple hyperparam sweeps in succession I believe you could do `python train.py --multirun +experiment=[fashion_mnist,remote,sweep],[fashion_mnist_small,remote,sweep]`.

Anyways, I hope this helps!
