### ISSUE TITLE
Optuna sweeper direction is always minimize

### ISSUE THREAD

**Issue by ai4prod** [facebookresearch/hydra#2047]
# 🐛 Bug
## Description

I followed the example https://hydra.cc/docs/plugins/optuna_sweeper/ and change the direction to maximize instead of minimize. 

## Checklist
- [Yes ] I checked on the latest version of Hydra 1.1.1 
- [ Yes but is not public] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

Let me know if you need access

## To reproduce

** Minimal Code/Config snippet to reproduce **
```yaml
defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

sampler:
  _target_: optuna.samplers.TPESampler
  seed: 123
  consider_prior: true
  prior_weight: 1.0
  consider_magic_clip: true
  consider_endpoints: false
  n_startup_trials: 10
  n_ei_candidates: 24
  multivariate: false
  warn_independent_sampling: true
_target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
direction: maximize
storage: null
study_name: sphere
n_trials: 20
n_jobs: 1
search_space:
  model.weight_decay:
    type: float
    low: 0.00001
    high: 0.0001
    step: 0.00001
  model.lr:
    type: categorical
    choices:
    - 0.01
    - 0.001
    - 0.0001
```

`python train.py --multirun`

** Stack trace/error message **

```
[2022-02-21 14:11:43,162][HYDRA] Study name: no-name-f883182e-6731-4d43-af92-3e784370284f
[2022-02-21 14:11:43,162][HYDRA] Storage: None
[2022-02-21 14:11:43,162][HYDRA] Sampler: TPESampler
[2022-02-21 14:11:43,162][HYDRA] Directions: ['minimize']
[2022-02-21 14:11:43,165][HYDRA] Launching 2 jobs locally
```

## Expected Behavior

I expect the log from hydra to be maximize direction

## System information
- **Hydra Version** :  1.1.1
- **Python version** :  3.8
- **Virtual environment type and version** : virtualenv
- **Operating system** :  Linux

**Comment by Jasha10** [comment]
Thanks for the report @ai4prod, I can reproduce the issue.

**Comment by jieru-hu** [comment]
hi @ai4prod I assume the config you are providing here is your primary config, in which case you are not actually overriding the Hydra sweeper config. 

in order to do a correct override you need to put the configs under `hydra.sweeper`. for example, you config would look like
```
hydra: 
  sweeper:
      sampler:
        _target_: optuna.samplers.TPESampler
```
to verify you've correctly overriden the Hydra config you can check the config with Hydra's [commandline option](https://hydra.cc/docs/advanced/hydra-command-line-flags/)
```
python myapp.py --cfg hydra -p hydra.sweeper
```

I've verified the sweeper is running correctly by overriding the configs in this [examples app](https://github.com/facebookresearch/hydra/blob/main/plugins/hydra_optuna_sweeper/example/conf/config.yaml)
to be 
```
defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    sampler:
      seed: 123
    direction: maximize
    study_name: sphere
    storage: null
    n_trials: 20
    n_jobs: 1
    params:
      x: range(-5.5, 5.5, step=0.5)
      y: choice(-5 ,0 ,5)
```

running the app (direction is correct.)
```
 % python example/sphere.py -m                          
[I 2022-03-30 11:31:10,566] A new study created in memory with name: sphere
[2022-03-30 11:31:10,566][HYDRA] Study name: sphere
[2022-03-30 11:31:10,566][HYDRA] Storage: None
[2022-03-30 11:31:10,566][HYDRA] Sampler: TPESampler
[2022-03-30 11:31:10,566][HYDRA] Directions: ['maximize']
[2022-03-30 11:31:10,567][HYDRA] Launching 1 jobs locally

```
