### ISSUE TITLE
[Feature Request] Dynamic object creation

### ISSUE THREAD

**Issue by moskomule** [facebookresearch/hydra#207]
# 🚀 Feature Request

Thank you for open-sourcing this project. This library is what I've wanted.

I want a feature for dynamic object creation like

```python
@hydra.hydrize
class Foo(object):
    def __init__(self, bar=1, foo_bar=2):
        pass


@hydra.main
def main(cfg):
　foo = Foo(cfg.foo)
　# foo2 = Foo(bar=1, foo_bar=2) should also be valid.


```

I guess Google's [ginconfig](https://github.com/google/gin-config) is related.

## Motivation

Currently, as far as I know, hydra supports object creation in [this way](https://cli.dev/docs/patterns/objects) with a config file

```yaml
model:
db:
  class: tutorial.objects_example.objects.MySQLConnection
  params:
    host: localhost
    user: root
    password: 1234
```

Since structure changes in a developing project step by step, the hardcoding of class (e.g., tutorial.objects_example.objects.MySQLConnection) is not useful in some cases.

## Pitch

**Describe the solution you'd like**

I have no solution yet, but if I am willing to develop this feature and send a PR.

**Comment by omry** [comment]
Hi @moskomule.

This seems like valid Python code:
```
foo2 = Foo(bar=1, foo_bar=2) should also be valid.
```

One thing that should already be possible is:
config:
```
db:
  host: localhost
  user: root
  password: 1234
```

code:
```
from tutorial.objects_example.objects import MySQLConnection
...
db = MySQLConnection(**cfg.db)
```
Is this closer to what you are after?
