### ISSUE TITLE
[Bug] Redundant instantiate if object referenced inside list

### ISSUE THREAD

**Issue by Robinysh** [facebookresearch/hydra#2078]
# 🐛 Bug
## Description
Objects that are already instantiated are being re-instantiated if they're referenced inside a list.  Is this an intended behavior?
 
## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce
main.py
```python
from omegaconf import DictConfig, OmegaConf                                                                                                                                                                       
import hydra                                                                                                                                                                                                      
                                                                                                                                                                                                                  
class Foo():                                                                                                                                                                                                      
    def __init__(self):                                                                                                                                                                                           
        print('hello')                                                                                                                                                                                            
                                                                                                                                                                                                                  
@hydra.main(config_path=".", config_name="config")                                                                                                                                                                
def my_app(cfg):                                                                                                                                                                                                  
    cfg = hydra.utils.instantiate(cfg)                                                                                                                                                                            
    print(cfg)                                                                                                                                                                                                    
                                                                                                                                                                                                                  
if __name__ == '__main__':                                                                                                                                                                                        
    my_app() 
```

config.yaml
```YAML
foo:                                                                                                                                                                                                              
  _target_: main.Foo                                                                                                                                                                                              
                                                                                                                                                                                                                  
bar:                                                                                                                                                                                                              
  - ${foo}   
```

```
hello
hello
{'foo': <main.Foo object at 0x7f5c745e98e0>, 'bar': [<main.Foo object at 0x7f5c74603340>]}
```

## Expected Behavior
I would expect Foo to be instantiated only once, and those two Foo objects would refer to the same object.

## System information
- **Hydra Version** :  https://github.com/facebookresearch/hydra/commit/796fdf1c54eabdcd5121d3a9c8ab6af70ee41763
- **Python version** :  3.9.0
- **Virtual environment type and version** : Conda 4.11.0
- **Operating system** :  Arch Linux 2022-03-09

## Additional context

**Comment by jieru-hu** [comment]
hi @Robinysh thanks for the issue.
instantiate api will first eagerly resolve the configs and then instantiate the object, in your case, this means there will be two Foo objects instantiated. 
it sounds like this issue might help with your use case https://github.com/facebookresearch/hydra/issues/1393, if so, pls feel free to upvote and comment there

**Comment by Robinysh** [comment]
I see. I think #1393 would work. However, IMO shouldn't this be a default behavior instead of requiring a `_singleton_: true` flag? I understand the reasoning behind the current behavior but it seems to be counterintuitive for ${} to give a different object. `_singleton_: true`  would certainly cover most of my use cases.

**Comment by omry** [comment]
There is a separate feature request to support singletons. This is the same request framed as a bug.

**Comment by Ubadub** [comment]
@ValeKnappich  Unfortunately, that fix doesn't seem to work for nested objects, e.g.:

config.yaml:
```yaml
foo:
  _target_: __main__.Foo
  some_kwarg: ${ref:bar}

bar:
   _target_: __main__.Bar
```

main.py:
```py
class Bar:
    def __init__(self):
        pass

class Foo:
    def __init__(self, some_kwarg: Bar = None):
        print("hello")
```

Do you have a workaround for this?
