### ISSUE TITLE
[Bug] submitit_slurm passes unrecognized DDP arguments to _submit.py

### ISSUE THREAD

**Issue by alexsax** [facebookresearch/hydra#2231]
# 🐛 Bug
## Solution
Well this is mostly user error on my part (oops--sorry!).

I've used SLURM for many years, though, and this still caught me off guard! I'll post my solution to hopefully save someone else facing the same error.

Basically, SLURM has some notion of 'tasks' and 'nodes' and resources can be allocated at either level. I was using multiple GPUs per task with only 1 task per node. Submitit, though, likes to use 1 gpu per task and multiple tasks per node. So instead of running 
```bash
# Don't do this
export ngpu=2 && python train.py --multirun trainer=ddp +launcher=slurm hydra.launcher.gpus_per_node=${ngpu}
```
```bash
# Do this instead
export ngpu=2 && python train.py --multirun trainer=ddp +launcher=slurm hydra.launcher.tasks_per_node=${ngpu}
```
Easy peasy.  [PL Issue #2727](https://github.com/PyTorchLightning/pytorch-lightning/issues/2727) was also helpful for me debugging. 

## Description
I'm trying to launch a job that uses hydra/submitit_slurm for config and launching and pytorch-lightning's DDP implementation for training. Everything works locally, even submitit works locally, but SLURM jobs (specifically with submitit_slurm) fail. I realize this is a bit vague since I'm not posting a minimal code example, but the error message is so specific that I'm hoping this description will be enough. If not, please to let me know. 

Specifically, the symptoms are:
1) A 1-GPU DDP job with `submitit_slurm`:  job runs smoothly
2) A multi-gpu DDP job with `submitit_local`: the job runs smoothly
3) A multi-gpu DDP job with `submitit_slurm`: the process dies, leaving a zombie process. SLURM does not register an error and does not cancel the job. The slurm logs (e.g. `.submitit/57770369/57770369_0_log.err`) shows normal configuration in the main process, but the following from each non-main process. E.g. for a 4-gpu process, see the error message below.

## Checklist
- [x] I checked on the latest version of Hydra
- [ ] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **

** Stack trace/error message **
```
usage: _submit.py [-h] folder
_submit.py: error: unrecognized arguments: hydra.run.dir="/checkpoint/ssax/consistentreps/multiruns/lroverfit_4gpu/0" hydra.job.name=train_ddp_process_1
usage: _submit.py [-h] folder
_submit.py: error: unrecognized arguments: hydra.run.dir="/checkpoint/ssax/consistentreps/multiruns/lroverfit_4gpu/0" hydra.job.name=train_ddp_process_1 hydra.run.dir="/checkpoint/ssax/consistentreps/multiruns/lroverfit_4gpu/0" hydra.job.name=train_ddp_process_2
usage: _submit.py [-h] folder
_submit.py: error: unrecognized arguments: hydra.run.dir="/checkpoint/ssax/consistentreps/multiruns/lroverfit_4gpu/0" hydra.job.name=train_ddp_process_1 hydra.run.dir="/checkpoint/ssax/consistentreps/multiruns/lroverfit_4gpu/0" hydra.job.name=train_ddp_process_2 hydra.run.dir="/checkpoint/ssax/consistentreps/multiruns/lroverfit_4gpu/0" hydra.job.name=train_ddp_process_3
```

## Expected Behavior
_submit.py to not raise an argument error

## System information
- **Hydra Version** :  1.2
- **Python version** : Python 3.8.13
- **Virtual environment type and version** :  conda 4.5.8
- **Operating system** :  Ubuntu 20.04.2 LTS

## Additional context
Ping me on workplace if needed!

**Comment by jieru-hu** [comment]
thanks for sharing this @alexsax !

**Comment by casparvl** [comment]
I hit the same issue, but the config that failed/worked for me was different from yours. The one that failed was:

```
python train.py hydra/launcher/node@hydra.launcher=gpu_a100_fail hydra.launcher.timeout_min=59 hydra.launcher.nodes=1 --multirun
```
with
```
#conf/hydra/launcher/node/gpu_a100_fail.yaml
timeout_min: 3600 # 2.5 days
partition: gpu
tasks_per_node: 4
gpus_per_node: 4 # for some reason it needs to be gpus_per_node; gpus_per_task doesn't work.
cpus_per_task: 18
mem_per_gpu: 120000M
additional_parameters:
  gpu-bind: closest
  exclusive: true
```

The one that succeeded was the same command, but now with
```
#conf/hydra/launcher/node/gpu_a100_success.yaml
timeout_min: 3600 # 2.5 days
partition: gpu
tasks_per_node: 4
gpus_per_node: 4 # for some reason it needs to be gpus_per_node; gpus_per_task doesn't work.
cpus_per_gpu: 18
mem_per_gpu: 120000M
additional_parameters:
  gpu-bind: closest
  exclusive: true
```

I.e. I replaced `cpus_per_task` by `cpus_per_gpu`.

The reason this seemed to help is that `PyTorch Lightning` simply takes a different code path in initializing the distributed environment. When it fails, it fails in [this line](https://github.com/PyTorchLightning/pytorch-lightning/blob/a3c0a4738ff5f777241857ecafb88c016af9acc3/pytorch_lightning/strategies/launchers/subprocess_script.py#L145). The issue is that the [line above](https://github.com/PyTorchLightning/pytorch-lightning/blob/a3c0a4738ff5f777241857ecafb88c016af9acc3/pytorch_lightning/strategies/launchers/subprocess_script.py#L144) adds the `hydra.run.dir` and `hydra.job.name` as arguments. Clearly, these are not valid arguments for the `_submit.py` script. 

The reason _why_ changing the `cpus_per_task` to `cpus_per_gpu` helped though is not because something changes in this `_call_children_scripts` routine inside `subprocess_script.py`. The fact is: `_call_children_scripts` only gets called when the `self.cluster_environment.creates_processes_externally` is false (see [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/a3c0a4738ff5f777241857ecafb88c016af9acc3/pytorch_lightning/strategies/launchers/subprocess_script.py#L91)). For SLURM environments (I'm in a SLURM environment), this should be true (see [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/a3c0a4738ff5f777241857ecafb88c016af9acc3/pytorch_lightning/plugins/environments/slurm_environment.py#L38)). The only conclusion remaining is: for some reason, PyTorch Lightning correctly initializes a SLURM environment when using `cpus_per_gpu` in the config, but _not_ when using `cpus_per_task`. You can easily check this in your logs: these should contain "Multiprocessing is handled by SLURM" if PyTorch Lightning is letting the `SLURMEnvironment` handle task creation (see [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/d337374da7dc73cc99b026e39ca78ae3c3196fad/pytorch_lightning/trainer/connectors/accelerator_connector.py#L534)).

So, why doesn't PT Lightning detect that it's in a SLURM environment when `cpus_per_task` is specified? This, I have not fully figured out yet. I've unravelled the following:

[This function](https://github.com/PyTorchLightning/pytorch-lightning/blob/d337374da7dc73cc99b026e39ca78ae3c3196fad/pytorch_lightning/trainer/connectors/accelerator_connector.py#L541) returns false when `cpus_per_task` is used, because on [this line](https://github.com/PyTorchLightning/pytorch-lightning/blob/d337374da7dc73cc99b026e39ca78ae3c3196fad/pytorch_lightning/trainer/connectors/accelerator_connector.py#L548) `num_slurm_tasks=4` (as expected), but `total_requested_devices=2`. `total_requested_devices` is set [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/d337374da7dc73cc99b026e39ca78ae3c3196fad/pytorch_lightning/trainer/connectors/accelerator_connector.py#L546), based on `self._parallel_devices`, which in turn is set [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/d337374da7dc73cc99b026e39ca78ae3c3196fad/pytorch_lightning/trainer/connectors/accelerator_connector.py#L519). This, then, gets it's count from `self.accelerator.get_parallel_devices` being called with `self._devices_flag=[0,1]`. Next question: why does `self._devices_flag` only contain two GPU device indices? I'll still have to figure that out, but that'll be for another day...

**Comment by alexsax** [comment]
Thanks for sharing, @casparvl!

Good idea to include your launcher config. Here's mine, which has many values set to `None` (including `gpus_per_node`):

```yaml
# @package hydra.launcher
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
partition: learnfair
timeout_min: 60
comment: null
constraint: 'volta32gb'
cpus_per_task: null
cpus_per_gpu: null
exclude: null
gpus_per_node: null
gpus_per_task: 1
tasks_per_node: 1
max_num_timeout: 3
mem_gb: null
mem_per_gpu: null
mem_per_cpu: null
nodes: 1
name: ${hydra.job.name}
signal_delay_s: 120
additional_parameters: {}
array_parallelism: 256
setup: null
```
