### ISSUE TITLE
[Bug] Colorlog plugin generates `.log` file in cwd instead of output dir

### ISSUE THREAD

**Issue by ashleve** [facebookresearch/hydra#2241]
# 🐛 Bug
I'm using hydra v1.2 with `chdir` set to false.

When I don't use colorlog plugin, the `.log` file with python logs gets generated in my output directory.

But when I attach colorlog plugin with:
```yaml
defaults:
    - override hydra/hydra_logging: colorlog
    - override hydra/job_logging: colorlog
```
The `.log` file gets generated in current working directory

## Checklist
- [x] I checked on the latest version of Hydra
- [ ] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## Expected Behavior
I would expect the `.log` file to be always saved in output directory by default.

## System information
- **Hydra Version** :  1.2
- **Python version** : 3.10
- **Virtual environment type and version** : 
- **Operating system** : linux
