### ISSUE TITLE
[Bug] Error when running optuna-sweeper

### ISSUE THREAD

**Issue by haritsahm** [facebookresearch/hydra#2253]
# 🐛 Bug
## Description
I create a custom trainer using [ashleve/lightning-hydra-template](https://github.com/ashleve/lightning-hydra-template) and I want to run an optuna sweeper. There was an error when using `hydra-optuna-sweeper==1.2.0`, but it can run with `hydra-optuna-sweeper==1.1.2` even though it stuck after the first iteration.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
```
python train.py -m hparams_search=mnist_optuna experiment=my_model trainer.max_epochs=25
```
** Stack trace/error message **
```
Will assume defaults for version 1.1
  @hydra.main(config_path="configs/", config_name="train.yaml")
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 461, in <lambda>
    lambda: hydra.multirun(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 162, in multirun
    ret = sweeper.sweep(arguments=task_overrides)
  File "/opt/conda/lib/python3.8/site-packages/hydra_plugins/hydra_optuna_sweeper/optuna_sweeper.py", line 52, in sweep
    return self.sweeper.sweep(arguments)
  File "/opt/conda/lib/python3.8/site-packages/hydra_plugins/hydra_optuna_sweeper/_impl.py", line 289, in sweep
    assert self.search_space is None
AssertionError
```

## Expected Behavior
Run the sweeper successfully.

## System information
- **Hydra Version** :  `hydra-core==1.2.0`, `hydra-optuna-sweeper==1.2.0`
- **Python version** : 3.8.12
- **Virtual environment type and version** :  nvcr.io/nvida/pytorch:21.10-py3
- **Operating system** : 

## Additional context
config:
```yaml
# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=mnist_optuna experiment=example

defaults:
  - override /hydra/sweeper: optuna

# choose metric which will be optimized by Optuna
# make sure this is the correct name of some metric logged in lightning module!
optimized_metric: "val/acc_best"

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: null

    # name of the study to persist optimization results
    study_name: null

    # number of parallel workers
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: maximize

    # total number of runs that will be executed
    n_trials: 25

    # choose Optuna hyperparameter sampler
    # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 12345
      n_startup_trials: 10 # number of random sampling runs before optimization starts

    # define range of hyperparameters
    search_space:
      datamodule.batch_size:
        type: categorical
        choices: [32, 64, 128]
      model.lr:
        type: float
        low: 0.0001
        high: 0.2
      model.net.lin1_size:
        type: categorical
        choices: [32, 64, 128, 256, 512]
      model.net.lin2_size:
        type: categorical
        choices: [32, 64, 128, 256, 512]
      model.net.lin3_size:
        type: categorical
        choices: [32, 64, 128, 256, 512]
```

**Comment by Jasha10** [comment]
Hi @haritsahm,
I am able to reproduce the AssertionError.

For the newest version of hydra-optuna-sweeper, you should use `hydra.sweeper.params` instead of `hydra.sweeper.search_space`:
```yaml
# @package _global_
defaults:
  ...

...

hydra:
  sweeper:
    ...
    params:
      datamodule.batch_size: choice(32,64,128)
      model.lr: interval(0.0001, 0.2)
      model.net.lin1_size: choice(32, 64, 128, 256, 512)
      model.net.lin2_size: choice(32, 64, 128, 256, 512)
      model.net.lin3_size: choice(32, 64, 128, 256, 512)
```

Alternatively, you can install an older version of hydra-optuna-sweeper:
```
pip install 'hydra-optuna-sweeper<1.2'
```
