### ISSUE TITLE
SWEEP Through all hyperparameters permutations in parallel. [Feature Request]

### ISSUE THREAD

**Issue by krzysztofMajchrzak-GIT** [facebookresearch/hydra#2255]
# 🚀 Feature Request

I am looking for a solution where there will be a few models learning at the same time and after one completes, the next starts its learning process. I want this to continue untill all permutations are checked. Is it achievable with HYDRA?

## Motivation

I am trying to find the very best configuration of hiperparameters for my LSTM using HYDRA. The problem is that there are several houndreds of possible permutations and I want to test them all. So I am trying to use HYDRA with JobLib Launcher to do this but I just cant get it right.

My config folder contains 15 parameters and every single one has at least 3 values. My default configuration file is made like this:
```
defaults:
  - currency: ???
  - network: ???
  - optimizer: ???
  - lstm_layers: ???
  - lstm_neurons: ???
  - learning_rate: ???
  - momentum: ???
  - dropout: ???
  - activation: ???
  - loss: ???
  - epochs: ???
  - batch_size: ???
  - window: ???
  - time_period: ???
  - exchange: ???
  - _self_
  - override hydra/launcher: joblib

hydra:
  sweeper:
    params:
       currency: glob(*)
       network: glob(*)
       optimizer: glob(*)
       lstm_layers: glob(*)
       lstm_neurons: glob(*)
       learning_rate: glob(*)
       momentum: glob(*)
       dropout: glob(*)
       activation: glob(*)
       loss: glob(*)
       epochs: glob(*)
       batch_size: glob(*)
       window: glob(*)
       time_period: glob(*)
       exchange: glob(*)
```
I would like to test all the hyperparameters permutations but with the possibility to train as many models at once as the CPU can handle. I was trying to do this with the above config and after calling ``` python hydra_framework.py --multirun   ``` it freezes on:
 ``` /home/*****/scpxd/hydra_framework.py:23: UserWarning:
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="./conf", config_name="config")```
