### ISSUE TITLE
[Feature Request] Make method/class meta data (e.g. `__name__`) avaliable when using `_partial_=True`

### ISSUE THREAD

**Issue by BenedictWilkins** [facebookresearch/hydra#2256]
# 🚀 Feature Request

It is nice to be able to access `__name__` (etc) from a "partial instantiation" or partial method/function. `functools` already provides the `update_wrapper` method for this.  

## Motivation

Including this information can make some tasks very clean and there doesn't seem to be a downside since nothing too complicated is happening when `_partial_` is used.

I might want to define some metrics for testing, using `pytorch` my config might look like:
```yaml
metrics :
    - _target_ : torch.nn.functional.l1_loss 
      _partial_ : true
```

Then in python somewhere: 
```python
for metric in self.metrics:
    self.log(f"metric/{metric.__name__}", metric(x,y))
```

The "work around" I would use for the above is something like:

```yaml
metrics: 
    - _target_ : hydra.utils.get_method
      _args_ : [torch.nn.functional.l1_loss]
```
admittedly this is also pretty compact. It is less so when arguments are involved which I guess was the motivation for `_partial_`. One might imagine another scenario where instantiating an object (from partial) e.g. from `torch.optim` might depend on its `__name__` and you dont want to be doing things like `optimizer.func.__name__` + type checking.

## Pitch

I am willing to open a pull request for this, it should be simple. 

after looking through the source (on v1.2) it seems like the addition would be in :
`hydra/_internal/instantiate/_instantiate2.py` 
```python
from functools import partial, update_wrapper
...
partial_func = functools.partial(_target_, *args, **kwargs)`
update_wrapper(partial_func, _target_)
return partial_func
```
