### ISSUE TITLE
Nested configs

### ISSUE THREAD

**Issue by Nintorac** [facebookresearch/hydra#2266]
Hi, I am trying to set up hydra with nested configuration

Here is the tree of my config dir

```
├── config.yaml
├── experiment
│   ├── architecture
│   │   └── basic_ff.yaml
│   ├── dataset
│   │   ├── arrhythmia.yaml
│   │   └── mnist.yaml
│   ├── model
│   │   ├── classifier_test.yaml
│   │   └── classifier.yaml
│   ├── local.yaml
│   └── remote.yaml
```

config.yaml looks like this
```
defaults:
  - experiment: local
```

local.yaml looks like this 
```
defaults:
  - dataset: mnist
  - model: classifier
  - architecture: basic_ff

project: arrhythmia
experiment_name: dev-1
batch_size: 32
n_epochs: 100
lr: 0.001
```

I am trying to run the project with this command `python train.py experiment.dataset=arrhythmia`, instead of getting the `arrhythmia.yaml` defined config the `experiment.dataset` path only contains the string `arrhythmia`.

Is that expected? How should I be going about doing nested configuration like this? Thanks!
