### ISSUE TITLE
Nested object instantiation [Feature Request]

### ISSUE THREAD

**Issue by felixkreuk** [facebookresearch/hydra#229]
# 🚀 Feature Request

A way to instantiate objects in a nested manner. 

## Motivation

I can think of several cases when an object can be instantiated using other objects.
For example: A list of transforms in PyTorch. Usually I would write something like:
```
        img_transforms = torchvision.transforms.Compose([
            torchvision.transforms.ToPILImage(),
            torchvision.transforms.Resize((X, Y)),
        ])
```
It would be nice if Hydra would provide a way of doing that via conf file.
Something along the lines of (not sure about actual YAML syntax):
```
trans:
  class: torchvision.transforms.Compose
  params:    
    - class:  torchvision.transforms.ToPILImage
      params: []
    - class: torchvision.transforms.Resize
      params: [X, Y]
```
and then use this:
```
img_transforms = hydra.utils.instantiate(cfg.trans)
```

Another use case might be creating a DataLoader object and initializing with a Dataset object.

Apologies if I missed such a feature by any chance,
Thanks a lot!
