### ISSUE TITLE
Modify Trial when using a Sweeper

### ISSUE THREAD

**Issue by michelkok** [facebookresearch/hydra#2293]
# 🚀 Feature Request
A way to modify a `Trial` object while using a sweeper.

## Motivation
Using a sweeper the `Trial` object is not accessible from Python code anywhere. 

A potential use case is the setting of User Attributes before or after the Sweeper launched the Trial. For example, when doing hyperparameter optimization I use the Optuna sweeper plugin. The `Study` gives me back the best `Trial` with the optimal configuration. To find my model (that is stored in a separate database), I do not want to retrain my model with the optimal setup. I'd rather just extract the reference ID of this model. [User Attributes](https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/003_attributes.html#adding-user-attributes-to-trials) seems like a logical place to store such information. However, using the sweeper there is no way to set these as the `Trial` object is not accessible.

I have tried asking on StackOverflow but no answer was given. Then I looked through the codebase and it just seems impossible at the moment (unless I am missing something).

## Pitch
**Describe the solution you'd like**
Ideally, I'd like the `Trial` object to be available within the main function. Something along these lines:
```
@hydra.main(version_base=None, config_path="conf", config_name="sweep")
def sphere(cfg: TrainConfig, trial: Trial) -> float:
    model, loss = train_model(cfg)
    model_db_id = save_model(model)
    trial.set_user_attr("model_db_id": model_id)

    return loss, trial
```

**Describe alternatives you've considered**
An alternative could be to provide some callback function that can be used to modify the `Trial` object like [`custom_search_space`](https://hydra.cc/docs/plugins/optuna_sweeper/#experimental--custom-search-space-optimization). I like this less though, as there is no control over when to modify the `Trial` (e.g., the function below is called before actually computing anything - in my example, I'd like to use it after training my model).

I have even tried to implement this for my use case but this is really just a hack and not a solution as the function is clearly not intended to do the stuff I'm doing here.
```
hydra:
  sweeper:
    sampler:
      seed: 123
    direction: minimize
    study_name: train_model
    storage: sqlite:///trials.db
    n_trials: 20
    n_jobs: 1
    params:
      x: range(-5.5, 5.5, step=0.5)
      y: choice(-5 ,0 ,5)
      z: choice([0, 1], [2, 3], [2, 5])
    custom_search_space: package.run.configure
```
```
def configure(_, trial: Trial) -> None:
    trial.set_user_attr("model_db_id", 123456)
```

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Yes, but I am not familiar with most of the codebase. But for relatively simple changes, sure!
