### ISSUE TITLE
[Bug] Dicts not merging

### ISSUE THREAD

**Issue by slerman12** [facebookresearch/hydra#2305]
Let's say I have two **blocks**, where one block depends on the other:

```
block1:
       arg1: 1
       arg2: 2

block2: ${block1}
```

Now I launch my program as `python launch.py +block2.arg3=3`

If I print block2, I get: `{'arg3': 3}`

However, I would like to get: `{'arg1': 1, 'arg2': 2, 'arg3': 3}`
