### ISSUE TITLE
[Feature Request] Composing multiple default packages into a list

### ISSUE THREAD

**Issue by albertfgu** [facebookresearch/hydra#2335]
# 🚀 Feature Request

## Motivation

**Is your feature request related to a problem? Please describe.**
I apologize if this feature exists or has been asked before, but I couldn't find a solution.

I have a Python class that accepts a list of configs. Imagine a number of configs for individual classes that can be instantiated:

`configs/model/linear.yaml`:
```yaml
_target_: torch.nn.Linear
in_features: 10
out_features: 10
```

`configs/model/relu.yaml`:
```yaml
_target_: torch.nn.ReLU
```

Now imagine wanting to create something like `nn.Sequential` flexibly from command line. In particular, I'd like to flexibly be able to create configs such as

`configs/model/model1.yaml`:
```yaml
- _target_: torch.nn.Linear
  in_features: 10
  out_features: 10
- _target_: torch.nn.ReLU
```

`configs/model/model2.yaml`:
```yaml
- _target_: torch.nn.Linear
  in_features: 10
  out_features: 10
- _target_: torch.nn.Linear
  in_features: 10
  out_features: 20
```

However, I don't want to create a config for every possible combination. An ideal interface would be something like
`configs/model/model1.yaml`:
```yaml
defaults:
  - linear
  - relu
```

However, this clearly doesn't work and I'm not sure what other interface could make sense. Maybe an alternative interface could be
`configs/model/model1.yaml`:
```yaml
defaults:
  - linear@0
  - relu@1
```
Any ideas for how to implement something like this?
