### ISSUE TITLE
[Feature Request] Relocate/override package on command line

### ISSUE THREAD

**Issue by albertfgu** [facebookresearch/hydra#2344]
# 🚀 Feature Request

The documentation describes how to override packages or use a config group more than once using the `@` syntax: https://hydra.cc/docs/1.2/advanced/overriding_packages/

Is there a way to do this from the command line? Concretely take the last example:
`config.yaml`
```yaml
defaults:
 - server/db@src: mysql
 - server/db@dst: mysql
```
Suppose I wanted to change the second default to `server/db@dst: sqlite` without creating a new config, is that possible?
