### ISSUE TITLE
Instantiate a class from a library

### ISSUE THREAD

**Issue by Aydin-ab** [facebookresearch/hydra#2353]
Hello,

I am trying to instantiate a class from a library but I get an error locating target

Here is a minimal code
```python
import module as m

class myClass : 
   def __init__(self, moduleClass):
      pass

@hydra.main(config_name='config.yaml')
def main(cfg):
    myclass = hydra.utils.instantiate(cfg.myClass)
    print(myclass)


if __name__ == '__main__':
    main()

```
and here is the config file 

```yaml
myClass:
   _target_: myapp.myClass
   moduleClass:
      _target_: m.otherApp.otherClass
      param: otherParam
```

Is there a current way to accomplish this ?

Thanks a lot
