### ISSUE TITLE
[Feature Request] Add defaults for config groups

### ISSUE THREAD

**Issue by YannDubs** [facebookresearch/hydra#236]
# 🚀 Feature Request

Avoid duplicating code in config groups by adding a default/base for the group

## Motivation

When config groups become large there might be many values that are the same for most of the group. It would be nice to be able to have a `default.yaml` or `base.yaml` for each group where each default values would be taken from.

directory structure:

config.yaml
optimizer
--adam.yaml
--nesterov.yaml
--sgd.yaml
--default.yaml

with:
```
# default.yaml
optimizer:
  lr: 0.01

# sgd.yaml
optimizer:
  ... # lr not redefined so 0.01

# adam.yaml
optimizer:
  ... # lr not redefined so 0.01

# nesterov.yaml
optimizer:
  lr: 0.03
  ...
```

currently this can be done by loading `optimizer/default.yaml` before `optimizer/*.yaml` but it would be cleaner not to have to do that.  Also if I don't load `optimizer/*.yaml` then don't load `optimizer/default.yaml`. Also we don't want to be able to do `python main.py optimizer=default`, so this `default.py` has to be treated specifically

**Comment by omry** [comment]
Thanks for the request Yann.
The current way to reduce this kind of duplication is by using OmegaConf interpolations:
for example:

config.yaml:
```yaml
defaults:
   optimizer: adam
# default learning rate

lr: 0.01
```
adam.yaml
```
optimizer:
   lr: ${lr} # This would take the value from the top level lr at config.yaml unless overridden.
```

What you are actually asking for would be possible if and when this #171 is implemented.
It may not seem obvious from its description, but it will allow you to have a defaults: block on each of the optimizer files and thus allowing you to compose optimizers/default.yaml in before the actual optimizer.

Depending on the complicity of the example, the suggestion I made with interpolation may be a better solution.
By the way:
You can interpolate a node, not just a value. but this is not used a lot and may have some rough edges for this use case.

I am closing this as duplicated because it will be addressed by #171, but feel free to continue discussion here.
