### ISSUE TITLE
[Bug] Cannot do variable interpolation on non-leaf nodes between two configs in default list

### ISSUE THREAD

**Issue by alexcdot** [facebookresearch/hydra#2416]
# 🐛 Bug
## Description
When I try to do variable interpolation in a config on the defaults list, to try to get values from different config on the defaults list, AND the variable is in a structured config, I get an error with finding the variable. This only happens in hydra 1.2.0, not hydra 1.1.0

Config structure:
```
    db:
        driver: postgresql
        user: user
        password: password
        table_cfg:
            rows: 1
            cols: 2
    model:
        rows: ${db.table_cfg}
```
Top level config yaml:
```
defaults:
- server
- db: database
- model: network_failing
```
For the complete example, see https://github.com/alexcdot/hydra-interpolation-repro

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **

Run `python hydra_failing.py` on https://github.com/alexcdot/hydra-interpolation-repro

** Stack trace/error message **
If you run `python hydra_failing.py` (where the interpolated non-leaf node is optional in structured config)
```
In 'model/network_failing': InterpolationKeyError raised while composing config:
Interpolation key 'db.table_cfg' not found
    full_key: 
    object_type=ServerConfig

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

If you run `python hydra_failing_also.py` (where the interpolated non-leaf node is non-optional in structured config), you get a different error:
```
In 'model/network_failing': ValidationError raised while composing config:
Merge error: str is not a subclass of TableConfig. value: ${db.table_cfg}
    full_key: 
    object_type=ServerConfig

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

## Expected Behavior
I expect the interpolation to work and print:
```
db:
  driver: postgresql
  user: user
  password: password
  table_cfg:
    rows: 1
    cols: 2
model:
  rows: ${db.table_cfg.table_cfg.rows}

1
```
I included a version where we do variable interpolation between two configs on the defaults list for a **leaf** node and it works properly. So this error is restricted to non-leaf nodes:
`python hydra_success.py model=network_success`
Also, I included a version where we do not use structured config. this also leads to success. So this error is restricted to structured config `python hydra_success_non_structured.py`.

## System information
- **Hydra Version** :  1.2.0
- **Python version** :  3.9.7
- **Virtual environment type and version** : conda 4.11.0
- **Operating system** : Ubuntu 20.04
