### ISSUE TITLE
[Feature Request] Reuse instantiated object in multiple locations

### ISSUE THREAD

**Issue by nikhilxb** [facebookresearch/hydra#2567]
# 🚀 Feature Request

I would like to reuse a single instantiated object in multiple locations in a config.

## Motivation

**Is your feature request related to a problem? Please describe.**

Here is an example in machine learning: I would like `model.encoder1 == model.encoder2` so that they can share weights. However, the below config would result in 2 different instances (with different weights).
```yaml
model:
  _target_: models.MyModel
  encoder1:
    _target_: models.MyEncoder
  encoder2:
    _target_: models.MyEncoder
```
More generally, there are times when I want to configure a deeply nested object where certain nodes in the tree are shared.

## Pitch

**Describe the solution you'd like**
Maybe something along the lines of:
```yaml
model:
  _target_: models.MyModel
  encoder1:
    _target_: models.MyEncoder
  encoder2: ${object:model.encoder1}
```
It seems that with just the default variable interpolation, the config is interpolated before instantiation, resulting in 2 different instances.

**Describe alternatives you've considered**
- Rewriting `MyModel`: that works in this simple case, but there are complex/more nested cases in which I want to share modules. Rewriting it all would defeat the modularity that is the benefit of using Hydra. Sometimes I will try both cases: shared weights and non-shared weights.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Maybe, but I'm unfamiliar with the codebase and Hydra internals, so I wouldn't trust myself unless it's an easy fix.
