### ISSUE TITLE
How can I use sweeper?

### ISSUE THREAD

**Issue by LukeLIN-web** [facebookresearch/hydra#2569]
https://github.com/facebookresearch/hydra/blob/b6e01f52df79ab15e6984275b47fefbf58518dca/examples/tutorials/basic/running_your_hydra_app/5_basic_sweep/conf/config.yaml#L3

Here is my conf.yaml
```yaml
defaults:
  # - dataset: reddit
  - model: ???
  - _self_
root: '/tmp/datasets'

hydra:
  sweeper:
    params:
      model: sage
      model.num_train_worker: range(2, 7)
```
But it shows 
```
You must specify 'model', e.g, model=<OPTION>
Available options:
        sage

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by omry** [comment]
Try running your app with `model=sage` in the command line.
I also suggest you read the basic tutorial.

**Comment by LukeLIN-web** [comment]
I read the tutorial but still confusing.
I have specified model for the sweeper; why it not work?
How can I sweep multiple model in config file?

**Comment by omry** [comment]
You are running an Hydra app from the command line in multirun mode. That Hydra app indicates that it must be provided the model to construct the config.
Your run is failing before multirun even starts to construct the sub configs.

Try to set an empty model or have a resonable override value as a default option (like sage):

```yaml
defaults:
  # - dataset: reddit
  - model: null # or sage
  - _self_
```
