### ISSUE TITLE
set config attributes

### ISSUE THREAD

**Issue by yuwl798180** [facebookresearch/hydra#258]
have any way to set cfg an attribute

my purpose:

```python
@hydra.main(config_path='conf/config.yaml')
def main(cfg):
    cwd = utils.get_original_cwd()
    setattr(cfg,'cwd', cwd)

    preprocess(cfg)
```

**Comment by yuwl798180** [comment]
not only cwd, in deep learning, vocab_size cant be set before serialize the raw data.
so i have to pass the args that `cfg.vocab_size = xxx`

**Comment by omry** [comment]
Please read OmegaConf documentaton [here](https://omegaconf.readthedocs.io/en/latest/usage.html).

You can manipulate the config object:
``` python
cfg.cwd = cwd
```
But because it's in struct mode you get an error when attempting to add a field.
You can temporarily remove the struct mode:
```
from omegaconf import open_dict

with open_dict(cfg):
  cfg.cwd = cwd
  cfg.vocab_size  = ...
```
However, I recommend just adding all the fields you want to populate at runtime to your config:

config.yaml:
```yaml
# ??? is a mandatory value.
# you should be able to set it without open_dict
# but if you try to read it before it's set an error will get thrown.

# populated at runtime
cwd: ???
# populated at runtime
vocab_size: ???
```
