### ISSUE TITLE
[Feature Request] Is there a way to generate custom log dir name while running?

### ISSUE THREAD

**Issue by zhuoqun-chen** [facebookresearch/hydra#2615]
# 🚀 Feature Request

Hi, `Hydra` is an amzaing tool that helps me a lot to manage my experiments. I'd like to know whether I can name a log directory using a variable automaticly generated from within a running python script?

## Motivation

For example, I like to have some output directory structure like this:
+ `outputs/2023-03-17/Exp-1`
+ `outputs/2023-03-17/Exp-2`
+ `outputs/2023-03-17/Exp-3`
where `1`, `2`, `3` are auto-generated integer variable while my python script are running so that I don't need to manully pass `1`, `2`, `3` from CLI. This will release me from a lot of repeated work.

The reason why I need this because I need to do some post-processing from the log directory locally. So If I know like, for example, today's `Exp-3` and `Exp-17` has some good results then I only process data in those folders, and skip the rest of the folders either aborted because of error or having terrible raw data:
```python
raw_data_3 = process("2023-03-17/Exp-3")
raw_data_17 = process("2023-03-17/Exp-17")
```

## Pitch

I don't have a specific solution because I'm not familiar how hydra works.

## Additional context
I've browsed some posts and docs, and I know top-level `config.yaml` allows missing default key like `name: ???` and then I can set:

```yaml
name: ???

current_time: ${now:%Y-%m-%d}_${now:%H-%M-%S}

hydra:
  # sets output paths for all file logs to `logs/experiment/name'
  run:
    dir: experiments/${name}/${current_time}
```
But I'm not sure if `name` can be read directly from a running script. So perhaps this may help me solve my question but I do need some examples showing me how to do it.

Many thanks to the developers!
