### ISSUE TITLE
[Question] Override numeric key from the command line

### ISSUE THREAD

**Issue by alberto-oliveira** [facebookresearch/hydra#2619]
I`m trying to override the value of a key in the following structure:

```yaml
key:
    sub_key:
        1: value_1
        2: value_2
```

Both keys (1 and 2) of `sub_key` are integers. When overriding from the command line, if I try overriding with `key.sub_key.1=value_3`, it all raise an error saying it couldn`t find the key. That's because it is trying to find key "1" (string) of `sub_key`. I checked that by doing `+key.sub_key.1=value_3` in the command line and checking the resulting config to see it had added the key "1" to `sub_key`.

My question is if there is any way to override numeric keys like that in the command line. Thank you.

**Comment by Jasha10** [comment]
I believe overriding numeric keys in this way is currently unsupported.

**Comment by lzhhh93** [comment]
> I believe overriding numeric keys in this way is currently unsupported.

Would it be possible to override the numeric keys in another config.yaml?

**Comment by albertfgu** [comment]
:+1: to this issue, I think it would be useful.

**Comment by odelalleau** [comment]
Keys that are not strings of the form `foo_123` are not supported by Hydra's command line overrides, and this is unlikely to change in the short term.

If you absolutely need this you can use a resolver trick like this:

```yaml
key:
    sub_key: ${to_int_keys:${._sub_key}}
    _sub_key:
        k1: value_1
        k2: value_2
```

```python
def to_int_keys(cfg):
    return {int(k[1:]): v for k, v in cfg.items()}

OmegaConf.register_new_resolver("to_int_keys", to_int_keys)
```

and then
```bash
python my_app.py key._sub_key.k1=new_value
```
