### ISSUE TITLE
[Feature Request] Deactivate the logger and out directory from hydra API

### ISSUE THREAD

**Issue by guigautier** [facebookresearch/hydra#2620]
Hello, 

I don't know if it is possible to implement a feature for the Hydra API that would allow users to easily deactivate the logger and output directory during their experiments. Specifically, I would like to deactivate the output directly from hydra python library instead of override yaml file.  

instead of : 
```yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .
```

Thanks
