### ISSUE TITLE
Use resolvers in defaults list

### ISSUE THREAD

**Issue by gianmarcoaversanoenx** [facebookresearch/hydra#2630]
My main script:
```python
OmegaConf.register_new_resolver(
    "resolveme", myfun_which_takes_no_inputs_and_returns_yo_dot_yaml, replace=True, use_cache=True
)

@hydra.main(**_HYDRA_PARAMS)
def main(cfg: DictConfig = None) -> ty.Optional[float]:
    """Load configuration and run a training."""
    print(cfg)
```

My config file:
```yaml
defaults:
  - inputs: test.yaml
  - paths: default.yaml
  - hydra: default.yaml
  - yo: ${resolveme:} # should resolve to "yo.yaml"
``` 

This raises an error... why?

Error:
```
hydra.errors.ConfigCompositionException: Error resolving interpolation '${resolveme:}', possible interpolation keys: hydra, paths, inputs
```

Why can't I use a resolver in the defaults list that is registered to OmegaConf before I call Hydra? Does anyone know? Would it be possible to add this as feature?
