### ISSUE TITLE
Announcing the Release of hydra-callbacks Package

### ISSUE THREAD

**Issue by paquiteau** [facebookresearch/hydra#2634]
Hi there,

I am excited to announce the release of [hydra-callbacks](https://github.com/paquiteau/hydra-callbacks), a new package based on the Hydra callback mechanism. 

Hydra-callbacks is a collection of useful callback functions that can be used to enhance the functionality of Hydra-based applications. With the release of hydra-callbacks, users can now further customize their applications by integrating a set of callback functions that can be used to extend the functionality of Hydra (Collecting results from multiple jobs, Monitoring resource usage, and more ...)

Hydra-callbacks is available under an MIT license. The package is currently hosted on GitHub at https://github.com/paquiteau/hydra-callbacks, and is also on [PyPA](https://pypi.org/project/hydra-callbacks/).

To get your started simply:

1. `pip install hydra-callbacks`
2. extend your hydra config with the callback(s) of your choice, eg:
```yaml
# [your config above] 

hydra:
  callbacks:
    latest_callback:
      _target_: hydra_callbacks.LatestRunLink
      run_base_dir: "outputs"
      multirun_base_dir: "multirun"
    git_infos:
      _target_: hydra_callbacks.GitInfo
      clean: true
```

Bug report, comments and suggestion  are all welcome. Don't hesitate to star the repo or share it with colleagues if you like it :slightly_smiling_face: 

_[As this not a bug report nor a feature request, if there is a more appropriate place to share this I would gladly do it]_
