### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by idning** [facebookresearch/hydra#2655]
# 🐛 Bug: Silently convert data type with Tuple of mixed datatype.

## To reproduce

```python
$ cat my_app.py

    #!/usr/bin/env python3

    import hydra
    from omegaconf import DictConfig, OmegaConf
    from dataclasses import dataclass, MISSING
    from hydra.core.config_store import ConfigStore

    from dataclasses import dataclass

    import hydra
    from hydra.core.config_store import ConfigStore

    from typing import Callable, Dict, List, Optional, Tuple, Union

    @dataclass(kw_only=True)
    class Config:
        foo: Optional[Tuple[bool, int]] = (True, 3)
        bar: Optional[Tuple[int, bool]] = (3, 3)
        # bad: Optional[Tuple[int, int]] = (True, 3)


    cs = ConfigStore.instance()
    cs.store(name="base_config", node=Config)

    @hydra.main(version_base=None, config_path="conf", config_name="config")
    def my_app(cfg: Config) -> None:
        print(OmegaConf.to_yaml(cfg))

    if __name__ == "__main__":
        my_app()
```

```yaml
$ cat conf/config.yaml

    defaults:
      - base_config
```
```yaml
$ ./my_app.py

    foo:
    - true
    - true  # This should be 3, or raise an "unsupport" error.
    bar:
    - 3
    - 3  # This better to raise a error of type mismatch, e.g. "expected bool but got int"
```
