### ISSUE TITLE
[Feature Request] Keep comments in files during (support update config files)

### ISSUE THREAD

**Issue by JonathanLoscalzo** [facebookresearch/hydra#2698]
# 🚀 Feature Request

If we are using hydra to edit some files (with OmegaConf), it could be interesting to support keeping comments on files. Some of them could be interesting to continue being in the same place:
For example, at `.pre-commit-config.yaml` 
```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: check-case-conflict
      # - id: debug-statements at the moment this is not necesarry
      - id: check-yaml
        args: [--allow-multiple-documents]
```

## Motivation

It could be useful that hydra could a tool not just for reading configs, also for editing config files at running time. Other libs are not good maintaining comments.

**Comment by Jasha10** [comment]
Hydra/OmegaConf use `pyyaml` for yaml parsing, and `pyaaml` does not support yaml comments.
Note that [the yaml spec](https://yaml.org/spec/1.2.2/#3233-comments) says "Comments are a presentation detail and must not have any effect on the serialization tree or representation graph."
Sorry to give a hard no on this, but I don't want to give you false hope. We're unlikely to ever support comments in yaml.

You could create a "pseudo-comment":
```yaml
data:
  - foo
  - bar
comment: my commentary
```
