### ISSUE TITLE
Possible Composition feature for launcher configurations

### ISSUE THREAD

**Issue by alirezakazemipour** [facebookresearch/hydra#2701]
### Discussed in https://github.com/facebookresearch/hydra/discussions/2700

<div type='discussions-op-text'>

<sup>Originally posted by **alirezakazemipour** July  4, 2023</sup>
Hi lovely Hydra developers,
I'm desperately trying to find a way to alternate between different Launcher settings without directly changing them via command line or in the main config.yaml file.
I mean I'd like to have a group configs for the launcher to just specify the desired one at the runtime. How is it possible in your opinion? </div>

**Comment by odelalleau** [comment]
I'm not sure I fully understand: how do you want to be able to switch between different launcher settings exactly?

**Comment by alirezakazemipour** [comment]
Thank you very much for your answer @odelalleau!
Sorry for the ambiguity!

What I mean is that, suppose I have my launcher to be `joblib`. One way to change `n_jobs` is to enter on the command line
`hydra.launcher.n_jobs=10` or in my main config file I write:
```yaml
hydra:
  launcher:
      n_jobs: 10
```
My question is how can I define `n_jobs: 10` in another _yaml_ file and redirect my launcher configuration to be set by that file instead of setting it directly. like:
```yaml
defaults:
 - override hydra/launcher: joblib 
 - l_config
 
 hydra:
  launcher:
      n_jobs: l_config.n_jobs
```
I was just a toy example to demonstrate what I'm looking for, the file containing configurations of the launcher would be more complex.
