### ISSUE TITLE
[Feature Request/Help] Interpolate AX sweeper params from group/subconfig

### ISSUE THREAD

**Issue by mcherep** [facebookresearch/hydra#2706]
# 🚀 Feature Request/Help

I'm using the AX plugin and I want to be able to define the `ax_config` in a different subconfig and interpolate. I have different algorithms with their corresponding configuration and it makes sense to define the parameters for the sweeping there. Is there a way to do this? I can't find anything in the documentation.

## Motivation

The following primary configuration works as expected:

```yaml
defaults:
    - algorithm: DES
    - override hydra/sweeper: ax

hydra:
  sweeper:
    ax_config:
      max_trials: 10
      params:
        algorithm.popsize:
          type: range
          bounds: [10, 100]
        algorithm.mean_decay:
          type: range
          bounds: [0.0, 1.0]
```

However, in this case, it makes more sense to define `params` for each algorithm, but I can't find a way to make it work.

## Pitch

I want to reference the parameters for the `ax_config` using the definition in the subconfig (i.e. algorithm).

```yaml
defaults:
    - algorithm: DES
    - override hydra/sweeper: ax

hydra.sweeper.ax_config.params: ${algorithm.sweeper_params}
```

Then the algorithm/DES.yaml could look like this:

```yaml
sweeper_params:
  algorithm.popsize:
    type: range
    bounds: [10, 100]
  algorithm.mean_decay:
    type: range
    bounds: [0.0, 1.0]
```

**Comment by Jasha10** [comment]
@mcherep you might find the discussion here interesting: https://github.com/facebookresearch/hydra/issues/1258

**Comment by odelalleau** [comment]
In addition to what @Jasha10 said, I think you should be able to do something somewhat similar to what you want. The easiest way (I believe) would be to do something like:

File `algorithm/DES.yaml`:
```yaml
# @package _global_
hydra:
  sweeper:
    ax_config:
      sweeper_params:
        algorithm.popsize:
          type: range
          bounds: [10, 100]
        algorithm.mean_decay:
          type: range
          bounds: [0.0, 1.0]
```
and the config would be
```yaml
defaults:
    - override hydra/sweeper: ax
    - algorithm: DES
```
(I haven't actually tried it so it may not actually work exactly like this, but hopefully you get the idea).

Once you get it working this way, you can look into using interpolations to avoid having to repeat the `hydra / sweeper / ax_config / sweeper_params` hierarchy in all files.

**Comment by mcherep** [comment]
@Jasha10 @odelalleau thank you so much for your help! I had tried to do something similar, but failed because it was missing the header `# @package _global_`. For future reference, this works:

This allows me to define the algorithm and AX config in one place.

For `strategy/DES.yaml`
```yaml
# @package _global_
hydra:
  sweeper:
    ax_config:
      max_trials: 10
      params:
        strategy.algorithm.popsize:
          type: range
          bounds: [10, 100]

strategy:
  algorithm:
    popsize: 50
```

For `config.yaml``

```yaml
defaults:
    - strategy: DES
    - override hydra/sweeper: ax
```
