### ISSUE TITLE
[Bug] Cannot launch jobs to remote Ray - Kubernetes cluster 

### ISSUE THREAD

**Issue by stwerner97** [facebookresearch/hydra#2708]
# 🐛 Bug
## Description

I want to launch the [Simple Ray Launcher Example of Hydra](https://hydra.cc/docs/plugins/ray_launcher/) on a remote Kubernetes cluster that runs Ray using Hydra. I have configured the Ray launcher plugin to point towards the address of the (port-forwarded) Ray dashboard. When running ``python my_app.py hydra/launcher=ray hydra.launcher.ray.init.address=http://localhost:8265``, the job is executed locally and not on the remote Ray cluster. Taking a look at the config with the ``--cfg hydra`` flag, I get

```yaml
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra_plugins.hydra_ray_launcher.ray_launcher.RayLauncher
    ray:
      init:
        address: http://localhost:8265
      remote: {}
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: null
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra/launcher=ray
    - hydra.launcher.ray.init.address=http://localhost:8265
    task: []
  job:
    name: my_app
    chdir: null
    override_dirname: ''
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: <my-path>/hydra-ray-demo/simple
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: <my-path>/hydra-ray-demo/simple/config
      schema: file
      provider: main
    - path: ''
      schema: structured
```

I verified that I can successfully submit jobs using Ray, i.e., ``ray job submit --address http://localhost:8265 -- python script.py`` is successful.

Do I need to modify ``hydra.launcher.ray.remote``? I cannot figure out what values I should set here.

## Checklist
- [x] I checked on the latest version of Hydra
- [ ] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).
