### ISSUE TITLE
[Bug] config composition with command from bash file

### ISSUE THREAD

**Issue by Aplieox** [facebookresearch/hydra#2734]
# 🐛 Bug
## Description
When running a hydra composition script from a bash file, the config will not be compositioned correctly.
The below code can be used to replicate it. The following problems arise:
1. Running the bash file:
- works as expected with output:
```
config:
  object:
    field1: value
  list:
  - path1: /some/other/path
    field: 12
  - path2: /some/other/path
    field: 123
```
- adding the cfg and job arguments to the bash file works as expected:
```
config:
  object:
    field1: value
  list:
  - path1: /some/other/path
    field: 12
  - path2: /some/other/path
    field: 123
```
2. Echoing the command from the bash file and executing it by copying it:
- fails with the output:
```
config:
  object:
    field1: value
  list:
  - field:12
  - field:123
```
- adding cfg and job arguments fails with output:
```
config:
  object:
    field1: value
  list:
  - field:12
  - field:123
```
3. echo command from file and escaping each special character:
- works as expected with output:
```
config:
  object:
    field1: value
  list:
  - path1: /some/other/path
    field: 12
  - path2: /some/other/path
    field: 123
```

So I guess that the bash file somehow escapes these characters when executing the commands, although I have not seen any literature online to back that up.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **

python script
```python
import hydra

from omegaconf import OmegaConf, DictConfig

@hydra.main(version_base=None, config_path=".", config_name="config")
def my_app(cfg: DictConfig) -> None:
    print(OmegaConf.to_yaml(cfg))

if __name__ == "__main__":
    my_app()
```

```yaml
config:
  object:
    field1: value
  list:
    - path1: /some/path
      field: 10
    - path2: /some/other
      field: 4
    - path3: /some/less
      field: 119
```

```bash
#!/bin/bash

python \
main.py \
config.list="[{path1:\"/some/other/path\",field:12},{path2:\"/some/other/path\",field:123}]"
```

** Stack trace/error message **
```
no stack trace, executes every time
```

## Expected Behavior
I expect to be able to use the fields in the composed config and see the aditional fields when I run the command with the cfg and job arguments from the echoed command

## System information
- **Hydra Version** :  hydra-core==1.3.2
- **Python version** : 3.8.10
- **Operating system** : Ubuntu20.04
