### ISSUE TITLE
[Bug] Plugin hydra_submitit missing specifying custom python call

### ISSUE THREAD

**Issue by EternalGoldenBraid** [facebookresearch/hydra#2761]
# 🐛 Bug
## Description

Submitit offers to pass a custom python call in: https://github.com/facebookincubator/submitit/blob/e8600a2b9e9cbe05751ab433bbaba2ae960d8ac2/submitit/slurm/slurm.py#L244 with `SlurmExecutor`.

This seems to be missing at `hydra_submitit`: https://github.com/facebookresearch/hydra/blob/809718cdcd64f9cd930d26dea69f2660a6ffa833/plugins/hydra_submitit_launcher/hydra_plugins/hydra_submitit_launcher/config.py#L29

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

Following a minimal repo similar to https://github.com/facebookresearch/hydra/issues/1565.

at `/config/launcher/submitit_slurm_apptainer.yaml`
```
# @package _global_

hydra:
  launcher:
    python: "apptainer exec --no-home ${custom_launcher.image_path} /bin/bash -c 'source ${custom_launcher.conda_activate_path} ${custom_launcher.conda_env_name} && python'"
      
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    name: ${hydra.job.name}
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
```

And /config/config.yaml:
```
defaults:
  - launcher: submitit_slurm_apptainer
  - override hydra/launcher: submitit_slurm
  
  # - launcher: submitit_local_apptainer
  # - override hydra/launcher: submitit_local

  - _self_
 ```

** Stack trace/error message **
```
Key 'python' not in 'SlurmQueueConf'
    full_key: hydra.launcher.python
    object_type=SlurmQueueConf
```

## Expected Behavior

Expected hydra_submitit to accept and pass `python` value to submitit.

Simply adding:
```
python: Optional[str]=None
```
to https://github.com/facebookresearch/hydra/blob/809718cdcd64f9cd930d26dea69f2660a6ffa833/plugins/hydra_submitit_launcher/hydra_plugins/hydra_submitit_launcher/config.py#L29 seems to do the trick:
```
>> python test.py  --cfg hydra -p hydra.launcher

# @package hydra.launcher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 60
...
srun_args: null
python: apptainer exec --no-home ${custom_launcher.image_path} /bin/bash -c 'source
  ${custom_launcher.conda_activate_path} ${custom_launcher.conda_env_name} && python'
```

## System information
- **Hydra Version** :  1.3.2
- **Python version** :  3.8
- **Virtual environment type and version** : 
- **Operating system** :  Ubuntu 20.2

## Additional context
I'm using it to run `apptainer exec ...` on slurm jobs. Haven't tested on slurm itself yet.
