### ISSUE TITLE
[Feature Request] Problem with Overwriting dict config of existing configuration

### ISSUE THREAD

**Issue by athn-nik** [facebookresearch/hydra#2775]
I am sorry for asking this here, but I am not sure where I should do. I am trying to overwrite a value of a config with a different value.
However, the name I want to override comes from the same group different name. Here is my config tree structure:
![image](https://github.com/facebookresearch/hydra/assets/24339666/41196d66-5a1d-445c-89c0-f472800b6289)
here is the curent `demo.yaml`
```
hydra:
  run:
    dir: .
  job:
    chdir: true
  output_subdir: null

folder: ???
savedir: null
mean: false
fact: 1
number_of_samples: 1
ckpt_name: 999
last_ckpt_path: ${get_last_checkpoint:${folder},${ckpt_name}}
logger_level: INFO

defaults:
  # - model: basic
  - /model/infer_scheduler: ddpm 
  - /path@path
  - override hydra/job_logging: rich # custom
  - override hydra/hydra_logging: rich # custom
  - _self_

```
I am trying to overwrite the model.infer_scheduler group with ddpm and ddim which alternative names for it. I have tried defining it in the defaults and overwrite it above our below but it seems not to work. Interpolation does not work as well (i.e. add another field in this config and get it from there). Basically my application is that I run script say `train.py` and the I run 'demo.py` which config I merge with train but I want to overwrite one group config of the train config from the demo config.

This is not a bug, but I didn't know where to rely for help. I try reading the docs and understood that I must do this via defaults but now sure how.

Thanks a lot !

**Comment by odelalleau** [comment]
I think it'd be easier to understand if you were able to provide a minimal example illustrating what you're trying to achieve.

**Comment by athn-nik** [comment]
Thanks for the speedy response. I have a file that I run `train.yaml` which uses this minimal config:
```
hydra:
  run:
    dir: ${expdir}/${project}/
  job:
    chdir: true

project: motion-editing

defaults:
  - data: bodilex
  - model: basic
  - machine: server
  - trainer: base
  - /path@path
  - override hydra/job_logging: rich
  - override hydra/hydra_logging: rich
  - _self_
```
and in this config I have the model which takes `basic.yaml` as a config. Now this `basic.yaml` has a parameter inside called infer scheduler, `basic.yaml` looks like this :
```
....
defaults:
  # diffusion stuff
  - train_scheduler: ddpm
  - infer_scheduler: ddpm
...
```
Now, after I run and finish this script. I give the hydra created folder to another script. I grab the config I described above and I want to override `infer_scheduler` parameter inside my `demo.yaml` somehow.
now ddim.yaml and ddpm.yaml look like this:

```
_target_: diffusers.DDPMScheduler
num_train_timesteps: 1000
beta_start: 0.00085
...
```
The question is how do I access this group and override this config properly via my new script `demo.py`.

At a high level, make the new script see my config structure and properly overwrite `model.infer_scheduler` parameters to be `ddim` or `ddpm`. I have tried giving it by it gets interpreted as a string and when I give it in the defaults I can overwrite it in any way.

Thanks a lot for your help! I am kind of new in hydra and trying to learn and understand!

**Comment by odelalleau** [comment]
Hmm... so if I understand correctly you have a previous config that you dumped and you want to modify some node of the config.

Would this work?

```yaml
defaults:
  - _self_
  - model/infer_scheduler: ddim

... # this is the config that you dumped
```

(NB: I haven't tested this, I may have got the syntax wrong)
