### ISSUE TITLE
[Feature Request] defaults-list inside configuration

### ISSUE THREAD

**Issue by fdschmidt93** [facebookresearch/hydra#2785]
# 🚀 Feature Request

Any key in a config yaml ideally supports defining a defaults list.

## Motivation

Horizontal or top-down inheritance in yaml configuration can quickly become unwieldy with defaults list, if many children _almost_ entirely "default" to the same configuration.

For instance, say we want to instantiate datasets for all languages of a multi-lingual benchmark dataset like [XNLI](https://huggingface.co/datasets/xnli).

We would have some sort of `default.yaml` all language-split specific datasets of our XNLI benchmark default to.

```yaml
# ./configs/dataset/default.yaml
dataset:
  _target_: datasets.load_dataset
  path: xnli
  name: ???
  split: ???
dataloader:
  _target_: torch.utils.data.dataloader.DataLoader
  # ...
evaluation:
  _target_: torch.utils.data.dataloader.DataLoader
  # ...
```

As of right now, we would have to use the `defaults`-list with packages to place the shared configuration correctly, assuming `datasets.yaml` and `default.yaml` are in the same folder.
(Don't mind that I am testing when validating, I always report test performance under various and transparent assumptions :)

```yaml
# ./config/datasets.yaml
defaults:
  - default@validation_xnli_en
  - default@test_xnli_en
  # XNLI has val and test splits for 15 languages
  # We would have in total 30 default entries similar to the above two

validation_xnli_en:
  name: en
  split: validation
test_xnli_en:
  name: en
  split: test
  # for all other languages ...
```
## Pitch

**Describe the solution you'd like**

The `defaults`-list would be a clean solution, if the restriction was lifted that it can only be specified at the top of a configuration yaml. This would be more robust and maintainable, as each dataset declaration becomes self-contained. 

The above I believe should become

```yaml
# datasets.yaml
validation_xnli_en:
  defaults:
      - /dataset/default@_here_
  name: en
  split: validation
test_xnli_en:
  defaults:
      - /dataset/default@_here_
  name: en
  split: validation
# for all other languages ...
```

which appears to be a natural extension of the `defaults`-list interface and would fully encapsulate a YAML-anchor-like functionality in `hydra`.

The above example relies on absolute paths to clearly refer the the `./configs/dataset/default.yaml`. Of ocurse, `defaults`-lists inside a config would raise questions whether defaults can also come from parent nodes.

**Describe alternatives you've considered**

1. Simply the above. Upon further consideration, one can make the argument there is too little gained for what most likely would require deep changes. Please just close this FR if that's the case. However, `defaults-`list inside a key can meaningfully reduce having to define multiple files for cleaner defaults.
2. Generating yaml files per dataset, which I think becomes very verbose (dataset of datasets yaml & yaml per dataset)
3. Structured configs: I generally prefer YAML configuration where possible, as the majority of my configuration is better defined in yaml. A clever StructuredConfig should be able to solve my problem though I suppose

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

Happy to take a crack at it, if the feature is desirable!

# Closing remarks

Many thanks for a cool project. Apologies if I missed something to do this more naturally or my feature request is a bad idea! I also was looking for a (close to) identical issue but, while some are somewhat similar, they have different end goals.
