### ISSUE TITLE
Sequentially sweep multiple parameters with multi-run

### ISSUE THREAD

**Issue by nuomizai** [facebookresearch/hydra#2790]
I appreciate the multirun functions in hydra. However, I found with this function, the parameters are simultaneously configured with multiple parallel process. However, with the resource constraint, I want to configure the parameters sequentially. To be specific, my command is as follows 
```
python train.py --multirun seed=0,1,2
```
I want to run the code with seed=1 after the code with seed=0 finished. Does anyone can help?

my config.yaml
```
hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${hydra.job.override_dirname}/${seed}
  sweep:
    dir: ./exp_local
    subdir: ${now:%Y.%m.%d}/${hydra.job.override_dirname}/${seed}
  job:
    config:
      override_dirname:
        exclude_keys:
          - seed
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 8
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
```
