### ISSUE TITLE
[Bug] Interpolation not possible in lists / tuples in config file

### ISSUE THREAD

**Issue by MouradInan-betclic** [facebookresearch/hydra#2845]
# 🐛 Bug
Interpolation not possible in lists / tuples in config file.

## Description

I'm having a list of columns and I would like to write them into my config file.
This list of columns contains some columns with the same suffix which is set before in the same config file.
And with trying to interpolate the suffix in the columns name in the list, the interpolation doesn't detect the variable.
Exemple:

```yaml
data_conf:
  rate_at: 7
  cols:
    - A
    - B
    - C_${.rate_at}
    - D_${.rate_at}

```

provide when printing cfg.cols:
[A,B,C_${.rate_at}, D_${.rate_at}]

Expected: 
[A,B,C_7,D_7] 

## Checklist
- [x ] I checked on the latest version of Hydra
- [ x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

```yaml
data_conf:
  rate_at: 7
  cols:
    - A
    - B
    - C_${.rate_at}
    - D_${.rate_at}

```

```python
@hydra.main(version_base=None, config_path="./", config_name=config)
def main(cfg: DictConfig):
    print(cfg.cols)
```

```
[A,B,C_${.rate_at}, D_${.rate_at}]
```

## Expected Behavior
[A,B,C_7,D_7] 

## System information
- **Hydra Version** :  1.3.2
- **Python version** : 3.11.6
- **Virtual environment type and version** : Poetry Env
- **Operating system** : MacOS

It might be OmegaConf issue.
My workaround at this moment is to write them in one-line and split after using python. It's just a little messy solution.

Hope there is better workaround / solution to fix that :)
