### ISSUE TITLE
[Feature Request] Add a _scope_ keyword for instantiation to specify a root module

### ISSUE THREAD

**Issue by ryan-minato** [facebookresearch/hydra#2883]
# 🚀 Feature Request

Perhaps a scope keyword could be added to specify a common root module for a dictionary and its sub-dictionaries, similar to what is [done in mmengine](https://mmengine.readthedocs.io/en/latest/advanced_tutorials/cross_library.html#use-detector-across-libraries:~:text=To%20prevent%20adding%20prefix%20to%20all%20of%20the%20submodules%20manually%2C%20the%20_scope_%20keyword%20is%20introduced.%20When%20the%20_scope_%20keyword%20is%20added%20to%20the%20config%20of%20a%20module%2C%20all%20submodules%E2%80%99%20scope%20will%20be%20changed%20by%20the%20_scope_%20keyword.%20Here%20is%20an%20example%20config%3A).

## e.g.
the following two configurations would be equivalent:

**conf1:**
``` yaml
model:
_target_: pkg.model.llama.LlamaModel
attn_module:
    _target_: pkg.model.llama.MyAttention
    hidden_size: 32
position_embeddings:
    _target_: pkg.model.llama.MyRotaryEmbedding
    max_position_embeddings: 2048
num_hidden_layers: 32
...
```

**conf2:**
``` yaml
model:
_scope_: pkg.model.llama
_target_: .LlamaModel
attn_module:
    _target_: .MyAttention
    hidden_size: 32
position_embeddings:
    _target_: .MyRotaryEmbedding
    max_position_embeddings: 2048
num_hidden_layers: 32
...
```

## Motivation

This feature can reduce repetition in the configuration files and codes. On the other hand, it could also isolate users and developers by treating `_target_` as a configuration item.

Currently, I have to write a data class configuration for every class I use. If this feature is added, I could implement a similar function simply through a decorator that checks input types based on the `_init_` function signature.

## Pitch

**Describe the solution you'd like**

One quick (but maybe ugly) implementation I can think of is to search for all `_scope_ `when reading the configuration and then prepend it to the target of the same level and sub-level.

**Describe alternatives you've considered**

**Are you willing to open a pull request?** 

I am willing to submit a PR to implement this feature if it is deemed acceptable in this discussion.

### Discussed in https://github.com/facebookresearch/hydra/discussions/2882

<div type='discussions-op-text'>

<sup>Originally posted by **minato-ellie** April  4, 2024</sup>

**Comment by minato-ellie** [comment]
I did create a small, simple demo that runs correctly, as this
 
 https://github.com/minato-ellie/hydra/commit/b7977e5ed549bd9d8afabc820c3ea94bf0e04f99
 
 main.py
``` python
import hydra
from omegaconf import DictConfig, OmegaConf
from hydra.utils import instantiate


class A:
    def __init__(self, a1=1, a2="a2"):
        self.a1 = a1
        self.a2 = a2

    def __str__(self):
        return f"A: {self.a1}, {self.a2}"


class B:
    def __init__(self, b1=1, b2="b2"):
        self.b1 = b1
        self.b2 = b2

    def __str__(self):
        return f"B: {self.b1}, {self.b2}"
    
class C:
    def __init__(self, a: A, b: B):
        self.a = a
        self.b = b

    def __str__(self):
        return f"C: {self.a}, {self.b}"
    

@hydra.main(config_path="conf", config_name="config")
def main(cfg):
    c = instantiate(cfg.c)
    print(c)
    print(OmegaConf.to_yaml(cfg))


if __name__ == "__main__":
    main()
```

config.yaml
``` yaml
c:
  _scope_: "__main__"
  _target_: "C"
  a:
    _target_: "A"
    a1: 10
  b:
    _target_: "B"
    b1: 100
```

Output
```
C: A: 10, a2, B: 100, b2
c:
  _scope_: __main__
  _target_: C
  a:
    _target_: A
    a1: 10
  b:
    _target_: B
    b1: 100
```
