### ISSUE TITLE
Disable all logging

### ISSUE THREAD

**Issue by skanti** [facebookresearch/hydra#2902]
Hi,
How can I silence/disable all kinds of logging. I don't want hydra to dump anything. I can't be that it requires 4 (!) lines to mute hydra. Is there a `-q` flag or something similar to disable it all?

<img width="466" alt="image" src="https://github.com/facebookresearch/hydra/assets/11197940/e9a1c5f3-1190-4641-8a64-3dd80ce3133d">

**Comment by omry** [comment]
You can override those things in your primary config.

```yaml
defaults:
  - override hydra/hydra_logging=disabled
  - override hydra/job_logging=disabled
hydra:
  run:
    dir: .
  output_subdir: null
```

Haven't tested it but it should have the same effect of appending those arguments.
