### ISSUE TITLE
compose defaults list dynamically before hydra.main

### ISSUE THREAD

**Issue by blackwint3r** [facebookresearch/hydra#2905]
Not very familiar with hydra yet, not sure if this is a silly questions. Is it possible to compose a defaults list dynamically, before the @hydra.main function is invoked?
In my scenario, I aim to generate a defaults list dynamically based on a specific keyword _schema_. The objective is to utilize the value associated with _schema_ as a structured configuration schema.

For instance, consider the following `config.yaml`:
``` yaml
name: John
highschool:
    _schema_: SchoolSchema
    name: CityHigh
```

And a corresponding schema file named `schema/SchoolSchema.yaml`:
```yaml
schoolname: ???
location: RiverCity
```

The desired outcome would be a configuration that reflects the following structure:
```yaml
defaults:
    - schema@highschool: SchoolSchema

name: John
highschool:
    name: CityHigh
```

I want to automatically handle the package path for nested dictionaries, so that I don't have to write a complicated defaults list. But I can't find a suitable place to do this, for the defaults list of DictConfig has already been parsed after hydra.main is called.
