### ISSUE TITLE
[Feature Request] Looking for overriding the group parameter in config

### ISSUE THREAD

**Issue by foreverYoungGitHub** [facebookresearch/hydra#2956]
# 🚀 Feature Request

Looking for overriding the group parameter in config.

## Motivation

**Is your feature request related to a problem? Please describe.**

Yes, this feature request is related to a problem I am encountering with configuration management. When I have a main config file and an experiment config file, I want to override the group parameter defined in the main file. For example:

In the main file:
```yaml
model:
  loss:
    _target_: a
    param_1: 0
```

In the experiment file:
```yaml
model:
  loss:
    _target_: b
    param_2: 0
```

Currently, it seems that the parameters from the main file are not fully overridden by the experiment file, resulting in a merged configuration that includes both `param_1` and `param_2`. This is problematic because `param_1` is not supported by `_target_: b`.

## Pitch

**Describe the solution you'd like**

I would like a feature that allows the full override of a group parameter in the configuration. Specifically, when running with the experiment config file, the `loss` parameter should only contain `param_2` and not `param_1`, as `param_1` is not supported by `_target_: b`.

**Describe alternatives you've considered**

An alternative solution could be to add a special parameter like `_override_` that explicitly indicates that the group parameter should be fully overridden. For example:
```yaml
model:
  loss:
    _override_: true
    _target_: b
    param_2: 0
```

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Yes, I am willing to open a pull request to implement this feature.

## Additional context

This feature would greatly simplify configuration management in scenarios where different experiment configurations need to fully override parameters defined in a main config file. It would help avoid conflicts and ensure that only the relevant parameters for the specified target are included.

Thank you for considering this feature request!

**Comment by qsh-zh** [comment]
the feature will be very useful!

**Comment by omry** [comment]
Use config composition.
Do not include use-case specific defaults in your base config, but compose them in.
e.g.:
config.yaml:
```yaml
defaults:
  - model: a
```

model/a.yaml:
```yaml
loss:
  _target_: a
  param_1: 0
```

model/b.yaml:
```yaml
loss:
  _target_: b
  param_2: 0
```


experiment/b_with_99.yaml:
```yaml
# @package _global_
defaults:
  - override /model: b

loss:
  param_2: 99
```
