### ISSUE TITLE
[Bug] Misleading overriding behavior for "empty" (null) keys

### ISSUE THREAD

**Issue by YodaEmbedding** [facebookresearch/hydra#2958]
# 🐛 Bug
## Description

Input:
```yaml
# dataset/imagenet.yaml

type: "ImageNetDataset"
path: "/datasets/imagenet"
```

```yaml
# example.yaml

defaults:
  - dataset/imagenet
  - _self_

dataset:
  type: "Overriden"
```

Output (as expected):
```yaml
dataset:
  type: 'Overriden'
  path: '/datasets/imagenet'
```

---

However, if we change `example.yaml` to:

```yaml
# example.yaml

defaults:
  - dataset/imagenet
  - _self_

dataset:
```

Output (unexpected, but correct):
```yaml
dataset: null
```

The intuitive expected output would have been:
```yaml
dataset:
  type: 'ImageNetDataset'
  path: '/datasets/imagenet'
```

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

See above.

## Expected Behavior

When overriding existing dicts with a single null value, hydra could perhaps produce a warning.

## System information
- **Hydra Version** :  1.3.2
- **Python version** : 3.11.9
- **Virtual environment type and version** : user
- **Operating system** : MacOS
