### ISSUE TITLE
[Bug] Deleting a key via CLI doesn't affect `_self_`

### ISSUE THREAD

**Issue by YodaEmbedding** [facebookresearch/hydra#2959]
# 🐛 Bug
## Description

Input:
```yaml
# dataset/imagenet.yaml

type: "ImageNetDataset"
path: "/datasets/imagenet"
```

```yaml
# example.yaml

defaults:
  - dataset/imagenet
  - _self_

dataset:
  type: "Overriden"
```

```python
# main.py

import hydra
import yaml
from omegaconf import DictConfig, OmegaConf

@hydra.main(version_base=None, config_path="conf")
def main(conf: DictConfig):
    print(yaml.dump(OmegaConf.to_container(conf, resolve=True)))

if __name__ == "__main__":
    main()
```

Run:

```bash
python main.py --config-path=conf --config-name=example '~dataset'
```

Output:
```yaml
dataset:
  type: Overridden
```

It seems that `_self_` is not processed in the same way as the defaults list is.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

See above.

## Expected Behavior

Output:
```yaml
dataset: {}
```

## System information
- **Hydra Version** :  1.3.2
- **Python version** : 3.11.9
- **Virtual environment type and version** : user
- **Operating system** : MacOS

**Comment by omry** [comment]
I cannot reproduce the issue as written on Hydra 1.3.2 or on current main. The defaults list entry in the repro is:

```yaml
- dataset/imagenet
```

With that form, `~dataset` fails with:

```text
Could not delete 'dataset'. No match in the defaults list
```

If you still think there is a Hydra bug here, please provide a working minimal example that reproduces the behavior you are seeing.

Reading between the lines, I suspect you may be trying to delete the defaults list entry and expecting that to also delete the preexisting `dataset` node from `_self_`. Those are separate things: deleting the defaults list entry removes the config selected from the `dataset` config group, but it does not delete config values contributed by the primary config body.

If the intent is to require the defaults list to provide `dataset`, a better pattern is to mark the primary config node as missing instead of giving it a concrete value:

```yaml
defaults:
  - dataset: imagenet
  - _self_

dataset: ???
```

That makes the contract explicit and gives clearer behavior when the defaults list entry is removed.
