### ISSUE TITLE
Overriding values of non-default config groups (without overriding the group itself)

### ISSUE THREAD

**Issue by brfi3983** [facebookresearch/hydra#2982]
I am wondering if it is possible to override a certain config value in a config group that by default is not part of the defaults list.

For instance, imagine we have the following defaults list:
```
defaults:
  modules:
     - thk
     - iceflow
 ```
where each of the following groups have many parameters within (e.g. below)

```
grid_size: 100
units: meters
shape: [2,100,10]
etc...
```

Then, if I have an `experiment` called `custom.yaml` and I want to override just the units, I would like to specify it like this

```
@package __global__
modules:
  thk:
    units: centimeters
```

However, this only works if `thk` is part of the original defaults list. If I do not specify it as part of the list, then it will replace the entire `thk` module with just the `units` variable, where `grid_size`, 'shape' and the others will be lost. This makes sense to me and does not seem to be an issue. However, I am wondering what the best to go about this as this does pose an inconvenience for me.

Ideally, I would like to start with an *empty* defaults list, and if I specify a parameter within some config group (like `thk: units: centimeters`), it would then load the `thk` group so that the other parameters are also loaded. I could simply include all of these modules as part of the `defaults: modules` but then if I only use one of those modules like `thk` I do not want to have 100 other modules like `iceflow` that I never used. This way if I share my configuration with another person, they do not have a list of a bunch of random config groups they will not use.

So here is the question: is there a best way to go about this or does not not exist anything yet? I would appreciate any suggestions on how to make this possible. If it was not clear, let me know and I can clarify what I meant.

**Comment by brfi3983** [comment]
This is to follow up on this issue as I have now solved it.

Essentially, in the main config, we start with an empty list of modules like so

```yaml
defaults:
  - _self_
  - modules: null
```

Then, in our experiment file (where we are in the `global` package), we have to specifically override it in the defaults list and not just in the file. For instance, if we want to choose 2 modules (`time` and `iceflow`), we can do it like so:

```yaml
# @package _global_
defaults:
  - override /modules: [time, iceflow]

modules:
  time:
    start: -30000.0
    end: -25000.0
    save: 100.0
```

In this situation, the default configuration from `iceflow` is loaded, while the default configuration of time is loaded **and updated** since we changed `start`, `end`, and `save`. This allows us to start with an empty `config.yaml` base file and essentially do a builder strategy.

My main issue, as explained above, was that if you did not include (even inside the global package)

```yaml
defaults:
  - override /modules: [time, iceflow]
```

before specifying

```yaml
modules:
  time:
    start: -30000.0
    end: -25000.0
    save: 100.0
```
hydra would simply replace all the values in `time` and you would only end up with `start`, `end`, and `save`.

Hopefully this helps anyone else trying to create an application similar to the one I am building.
