### ISSUE TITLE
How do I use the SearchPathPlugin?

### ISSUE THREAD

**Issue by XiaoXiao-Woo** [facebookresearch/hydra#3010]
I've reviewed the [SearchPathPlugin](https://github.com/facebookresearch/hydra/tree/main/examples/plugins/example_searchpath_plugin) and its documentation. It appears that the last step is missing. Could you provide more information on how to call searchpath_plugin from the default list after running setup.py? Specifically, in program A, I would like to know how to modify the example below:
```yaml
# config.yaml
defaults:
- hydra_plugins.example_searchpath_plugin

# Add other configs as needed
some_other_config:
value: 0
```
