### ISSUE TITLE
[Feature Request] How to specify parameter sweep from group config rather than global config?

### ISSUE THREAD

**Issue by leethologica** [facebookresearch/hydra#3047]
I am trying to use the multirun feature of Hydra. I have the following example layout:
```
├── conf
│   ├── config.yaml
│   └── test
│       ├── imagenet.yaml
│       └── mnist.yaml
└── main.py
```

I have a hyperparameter called `lambda` that is tuned for each test and I want to test multiple values of this parameter. For example, I want to run the imagenet test with `lambda=0` and `lambda=100` but I want to run the MNIST test with `lambda=0` and `lambda=1`. 

My `conf/config.yaml`:
```yaml
defaults:
  - test: ???
  - _self_

hydra:
  mode: MULTIRUN
```

My `conf/test/imagenet.yaml`:
```yaml
hydra:
  sweeper:
    params:
      lambda: 0,100

foo: bar
beep: boop
```

My `conf/test/mnist.yaml`:
```yaml
hydra:
  sweeper:
    params:
      lambda: 0,1

baz: baq
meep: moop
```

I would like to then run `python main.py test=glob(*)`, and for Hydra to run 4 tests: imagenet with lambda equal to 0 and 100, and MNIST with lambda equal to 0 and 1. However, Hydra does not appear to recognize parameter sweeps if they are not specified in the global config file.

How can I accomplish parameter sweeps unique to group config files?

**Edit**: I understand I can accomplish this with CLI arguments, namely have two separate commands `python main.py -m test=mnist test.lambda=0,1` and `python main.py -m test=imagenet test.lambda=0,100`, however the reason I want to specify them in the group config file and not the command line is for readability and maintainability purposes. I would prefer all the test parameters to be found in `conf/test/mnist.yaml`, for example, rather than the `lambda` parameter being hidden away in my runner script.
