### ISSUE TITLE
[Feature Request] _once_ behavior for instantiate

### ISSUE THREAD

**Issue by swamidass** [facebookresearch/hydra#3062]
# 🚀 Feature Request

I'd like a way to specify in a config that a tree should be instantiated **_once and only once_**, so that multiple identical objects aren't created when instantiate is called multiple times on the same config, or on a config with interpolations that copy a target to multiple parts of the tree.

## Motivation

**Is your feature request related to a problem? Please describe.**

Sometimes we want to ensure a subtree of the config is instantiated only ONCE. Making unnecessary copies, in these cases, can hammer resources or even break code.

Take this example:

```yaml
dataset:
  _target_: lightly.data.LightlyDataset
  root: data_dir
loader:
  _target_: torch.utils.data.DataLoader
  dataset: ${..dataset}  
  sampler:
    _target_: torch.utils.data.RandomSampler
    data_source: ${..dataset}.
```

Instantiating this config will, in fact, instantiate three separate instances of 'dataset', which is undesirable, because each one takes up memory. Even worse, calling instantiate a second time will create 3 more instances!

## Pitch

**Describe the solution you'd like**

I'd like this to be a built in feature of hydra (requiring just a minor version bump), using this syntax instead:

```yaml
dataset:
  _target_: lightly.data.LightlyDataset
  _once_: true                     # instantiate will only create this tree once, reusing it when needed.
  _once_key_: unique_key # OPTIONAL: use this key, instead of the default hash of the yaml
  root: data_dir
loader:
  _target_: torch.utils.data.DataLoader
  dataset: ${..dataset}  
  sampler:
    _target_: torch.utils.data.RandomSampler
    data_source: ${..dataset}
```

**Describe alternatives you've considered**

There are two inferior a work arounds. 

***factory code***

You could do boilerplate everywhere it was important.

```python

_made_dataset = None
def make_dataset(*args, **kwargs):
  global _made_dataset
  if _made_dataset is None:
    _made_dataset = ...
  return _made_dataset

```

It works. and it might be possible to turn into a decorator to reuse. 

But there are major downslides. This requires a lot of non-obvious boiler plate wrapping, and obfuscates the actual object from the conf file where we might want it to be clear.

***hackish plugin***

Currently there isn't a plugin hook for instantiation. You can, however, make a hackish plugin that will do this.

```python

_storage = {}

def once(
    _arg_: DictConfig
):
    arg = _arg_
    assert isinstance(arg, DictConfig), f"Arg must be a DictConfig, got {arg=}"

    # this isn't ideal if resolved interpolations change, so may need to resolve before hashing!
    key = hashlib.md5(OmegaConf.to_yaml(arg).encode()).hexdigest()

    if key not in _storage:
      _storage[key] = instantiate(arg)
        
    return _storage[key]
    
OmegaConf.register_new_resolver("once", lambda: once, replace=True)
```

Some improvements to this can make it take a custom key too. Now we wrap what we want to be a once instantiated part of the tree  in this function.  

```yaml
dataset:
  _target_: ${once:} # or we could just reference once directly.
  _recursive_: false
  _args_:
    - _target_: lightly.data.LightlyDataset
       root: data_dir
loader:
  _target_: torch.utils.data.DataLoader
  dataset: ${..dataset}  
  sampler:
    _target_: torch.utils.data.RandomSampler
    data_source: ${..dataset}
```

This solves the problem. Now, dataset is instantiated once, and recalled every place it is referred too.  There are some downside though. This is non  obvious and easy to screw up syntax. 

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

Yes.
