### ISSUE TITLE
[Bug] Unexpected string conversion when overriding an interpolated sibling config group

### ISSUE THREAD

**Issue by Kumoi-S** [facebookresearch/hydra#3068]
### Description

When a config group (`component_a` in the repro) interpolates a sibling config group (`component_b`) that is defined in the same `defaults` list, overriding the interpolated group (`component_b`) via the command line causes it to incorrectly resolve to a string, instead of the expected config object.

This happens both in the node where the interpolation occurs (`component_a.interpolated_b`) and at the top-level node for the overridden group (`component_b`).

### Checklist

  - [x] I checked on the latest version of Hydra
  - [x] I created a minimal repro (See [this](https://www.google.com/search?q=https://stackoverflow.com/help/minimal-reproduceable-example) for tips).

### To reproduce

**Minimal Code/Config snippet to reproduce**

The minimal reproducible example is attached as `mre_bug_test.zip`. 

[mre_bug_test.zip](https://github.com/user-attachments/files/20829855/mre_bug_test.zip)

1.  Unzip the attached file.
2.  From the root of the unzipped folder, run the following command:
```bash
uv sync
uv run python run.py 
uv run python run.py app.component_b=b2
```
3.  Observe and Compare the output printed to the console.

**Stack trace/error message**

```yaml
# This is the actual output from the MRE
app:
  component_a:
    name: Component A
    interpolated_b: b2
  component_b: b2
message: This is the top level config.
```

### Expected Behavior

The interpolation `${app.component_b}` should resolve to the full config object loaded from `b2.yaml`. Both `app.component_b` and `app.component_a.interpolated_b` should be identical objects, not strings.

The expected output is:

```yaml
app:
  component_a:
    name: Component A
    interpolated_b:
      source: b2.yaml
      value: 200
      is_override: true
  component_b:
    source: b2.yaml
    value: 200
    is_override: true
message: This is the top level config.
```

### System information

  - **Hydra Version** : hydra-core==1.3.2; omegaconf==2.3.0
  - **Python version** : CPython 3.10.11
  - **Virtual environment type and version** : uv (venv)
  - **Operating system** : Windows 11
