### ISSUE TITLE
Better format for overrides.yaml

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#322]
overrides.yaml looks like:
```yaml
- foo=bar
- zoo=fur
```
Using this require parsing of the key=value pairs. It would be better to utilize yaml like:
```yaml
- foo: bar
- zoo: fur
```
or:
```yaml
- key: foo
  value: bar
- key: zoo
  value: fur
```

**Comment by omry** [comment]
since this is essentially a list of key=value pairs, I actually think the current format is preferred to both alternative ideas:
```yaml
- foo: bar
- zoo: fur
```
This would would allow passing pairs : 
```yaml
- foo1: bar1
  foo2: bar2
- zoo: fur
```

which is not really supposed to happen.

This one is just too verbose:
```
- key: foo
  value: bar
- key: zoo
  value: fur
```
