### ISSUE TITLE
Ability to specify composition order of primary config file

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#326]
There are multiple use cases for having configuration in the users config:

Use it as scaffolding and use defaults to populate it:
```yaml
defalts:
  - foo: bar

foo:
   a: ???
   b: ???
```

In the above case foo/bar.yaml can be used to populate a and b.

An alternative approach is to allow the user to override things populated by the defaults from the config file:
```yaml
defalts:
  - foo: bar

foo:
   a: 10
   b: 20
```

In this scenario, the user wants to force foo.a and foo.b to specific values.

Those two approaches are conflicting, each one requires a different composition order.
Currently, the supported mode is the first one and the second is not possible.
Composition order is roughly:

- hydra related configs
- user config file
- user provided defaults

The idea is to support explicit specification of when to merge in the users config via a special keyword in the defaults, like `_self_`.
for example:

```yaml
defalts:
  - _self_
  - foo: bar
```
or:
```yaml
defalts:
  - foo: bar
  - _self_
```
In the first case, the config file would be composed before foo/bar, in the second one after.
