### ISSUE TITLE
[Bug] Overriding default config respects default config order

### ISSUE THREAD

**Issue by Noezor** [facebookresearch/hydra#346]
# 🐛 Bug

Hi, let me illustrate with an example.

train.py
```
@hydra.main(config_path="../conf/config.yaml")
def main(cfg):
    print(cfg.pretty())
```

../conf/config.yaml
```
defaults:
    - dataset: seven_stairs
    - model: default
```

Outputs default config as expected

```
python3 train.py
dataset: Seven_Scenes_Stairs(Path("/home/pionn/research/bla/data/7scenes/stairs"))
model:
  distance_scoring_layer: false
  top_k_scores: 20
```

Now let's say I want to have a dataset which also needs to have a specific model. In ../conf/dataset/ I create synthetic.yaml
```
dataset: Synthetic_Dataset_Triangle()
model:
    distance_scoring_layer: True
```

And now specify this config when running train
```
python3 train.py dataset=synthetic
dataset: **Synthetic_Dataset_Triangle()** as expected
model:
  distance_scoring_layer: **false** not as expected
  top_k_scores: 20
```

On the other hand, if I change ../conf/config.yaml to 
```
defaults:
    - model: default
    - dataset: seven_stairs
```

Then I obtain 
```
python3 train.py dataset=synthetic
dataset: **Synthetic_Dataset_Triangle()** as expected
model:
  distance_scoring_layer: **true**  as expected
  top_k_scores: 20
```

It seems that hydra runs each file in its default in an order, and after running each file tries to replace the default by what was given from the CLI. I expected it to run each config in the default in the specified order, and then overrule each of those by the configs given in the CLI.

I'm not sure it is a feature or a bug. If it is a feature, maybe it should be explained in https://hydra.cc/docs/tutorial/composition ?

## System information
- 0.11.3
- 3.7.2
- Ubuntu
