### ISSUE TITLE
Deprecated class keyword from class definition in configs

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#389]
Th class keyword here:
```
db:
  class: tutorial.objects_example.objects.MySQLConnection
  params:
    ...
```

Is causing issues when porting to dataclasses backed configs because it's not a legal field name.
Deprecate it, maintaining backward compatibility for one major version.

new alternative names:
- clazz
- classname
- cls
