### ISSUE TITLE
Can I overwrite an element of a list config?

### ISSUE THREAD

**Issue by reactivetype** [facebookresearch/hydra#403]
How can I overwrite the `database.tables.name` from `students` to `people`?
```
schema:
  database: school
  tables:
    - name: students
      fields:
        - name: string
        - class: int
    - name: exams
```

**Comment by omry** [comment]
```yaml
$ python examples/tutorial/5_composition/my_app.py schema=school schema.tables.0.name=people
db:
  driver: mysql
  pass: secret
  user: omry
schema:
  database: school
  tables:
  - fields:
    - name: string
    - class: int
    name: people
  - fields:
    - profession: string
    - time: data
    - class: int
    name: exams
ui:
  windows:
    create_db: true
    view: true
```

**Comment by reactivetype** [comment]
Thank you @omry

**Comment by Jasha10** [comment]
Hi @timruhkopf,
The following should work:
```python
$ python my_app.py fields.0=300
```

**Comment by timruhkopf** [comment]
Thank You very much!

I thought as much, but the plugin I used does not yet support the array unpacking properly.

**Comment by veriff-javiervgd** [comment]
Hey, is it possible to do the same but overriding from the conf file itself? like:

`schema.yml`
```yaml
schema:
  database: school
  tables:
    - name: students
      fields:
        - name: string
        - class: int
    - name: exams
```

`top_level_conf.yml`
```yaml
defaults:
  - schema: schema
  - _self_

# Wanted override
schema:
  tables:
    0: 
      name: other_name
```
