### ISSUE TITLE
[Feature Request] Auto Resolve

### ISSUE THREAD

**Issue by tchaton** [facebookresearch/hydra#405]
# 🚀 Feature Request

Dear @omry ,

It would be great to have an automatic resolver within Hydra.

It should be able to do a least two things:

```
type: mytype
define_constants:
    L1_OUT: 20
    MODULE: RSConv
down_conv:
    module_name: MODULE
    aggr: max
    number: 5
    expression: 5 + 5
    variable: FEAT
    variable_expression: FEAT + 5
    number_nn: [8, 16]
    nn: [FEAT, FEAT * 2, 16 + 16, L1_OUT * 2, L1_OUT]
    nested_nn: [[16*2, 8], [FEAT, FEAT*2]]
    nested_nested_nn: [[[8+8, 16], [16, 16//2]], [[8, 4], [4, FEAT]]]
    nested_dict:
        number: 3
        nn: [FEAT, 16 + 8]
```

Will give 

```
type: mytype
define_constants:
    L1_OUT: 20
    MODULE: RSConv
down_conv:
    module_name: RSConv
    aggr: max
    number: 5
    expression: 10
    variable: 6
    variable_expression: 11
    number_nn: [8, 16]
    nn: [6, 12, 32, 40, 20]
    nested_nn: [[32, 8], [6, 12]]
    nested_nested_nn: [[[16, 16], [16, 8]], [[8, 4], [4, 6]]]
    nested_dict:
        number: 3
        nn: [6, 24]
```

The second one will be the following:
```
        - transform: GridSphereSampling
          params:
              radius: 50 * ${data.first_subsampling}
```
It is going to resolve ${data.first_subsampling}, but not apply 50 * ${data.first_subsampling}. So I get a string and I need to eval it in the code, which isn't safe.

## Motivation

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../CONTRIBUTING.md))
