### ISSUE TITLE
[Feature Request] How to give cfg to class __init__ by using hydra.utils.instantiate ?

### ISSUE THREAD

**Issue by shaolinkhoa** [facebookresearch/hydra#507]
# 🚀 Feature Request

## Motivation
From this [tutorial](https://hydra.cc/docs/patterns/objects), I can give defined params (host, user, password, database)  to my class. But what if I want to give `cfg` to my class ?

## Pitch

**Describe the solution you'd like**

**config.yaml:**
```yaml
defaults:
  - dataset: mnist_dataset
  - model: mnist_model
```
  
**mnist_model.yaml:**
```yaml
model:
  name: mnist
  class: BaseModel  # The path may wrong. But in general, I will load class BaseModel 
  params:
    # I don't know how to define cfg in this params
```

```python
class BaseModel:
    def __init__(self, cfg):
        self.cfg= cfg
        self.logger = cfg.log

   def shape():
        print(self.cfg.cur_dir) 
        print(self.cfg.prj_dir ) 

@hydra.main(config_path="configs/train.yaml", strict=False)
def main(cfg: DictConfig) -> None:

    # A logger for this file
    cfg.log = logging.getLogger(__name__)

    cfg.cur_dir = os.getcwd()
    cfg.prj_dir = hydra.utils.get_original_cwd()

    log.info(f"\n{cfg.pretty()}")

    if cfg.model.name=="mnist":
        mnist = hydra.utils.instantiate(cfg.model) # Loading BaseModel but how to give cfg to BaseModel ?
        mnist.shape()
```
  
p/s: I know that we can add `${dataset}` to `BaseModel`  
```yaml
model:
  name: mnist
  class: BaseModel  # The path may wrong. But in general, I will load class BaseModel 
  params:
    cfg: ${dataset}
```
or 
```python
mnist = BaseModel(cfg)
```
But I just wonder if we can give `cfg` to class `BaseModel` by using hydra.utils.instantiate ?

Sorry for my silly question. You can close if it's not correct.

**Comment by omry** [comment]
Does this work?

```yaml
model:
  name: mnist
  class: BaseModel
  params:
    cfg:
      foo: 10
      bar: 20
```

**Comment by omry** [comment]
You added this to your question:
```yaml
defaults:
  - dataset: mnist_dataset
  - model: mnist_model
```

The key dataset here is irrelevant. this is just used for composition.
assuming the mnist_dataset adds a node like:
```yaml
data:
  name: mnist
  path: /foo/bar
```

You can link to it like:

```yaml
model:
  name: mnist
  class: BaseModel
  params:
    cfg: ${data}
```

**Comment by omry** [comment]
closing, but feel free to continue the discussion here or in the chat.

**Comment by shaolinkhoa** [comment]
I'm sorry for misleading you in this part. 

> **mnist_model.yaml:**
> ```yaml
> model:
>   name: mnist
>   class: BaseModel  # The path may wrong. But in general, I will load class BaseModel 
>   params:
>     # I don't know how to define cfg in this params
> ```

The `cfg` here is the `cfg: DictConfig` in `main()`
```python
@hydra.main(config_path="configs/train.yaml", strict=False)
def main(cfg: DictConfig) -> None:
```

**Comment by omry** [comment]
> The cfg here is the cfg: DictConfig in main()

No. it's not and can't be.
Why do you think the cfg in the model params should be the top level config? this would create a circular reference in the config and makes no sense at all.

If your BaseModel needs access to the whole config, you can pass pass it directly when you instantiate:

```python
instantiate(cfg.model, cfg)
```
Keep in mind that this is an indication of problematic design. you are breaking encapsulation here.
You want to allow the minimal access to BaseModel to what it needs. I am sure it doesn't really need the whole config.

**Comment by shaolinkhoa** [comment]
I tried 
```yaml
model:
  name: mnist
  class: BaseModel 
  params:
    cfg: ???
```
```python
mnist = hydra.utils.instantiate(cfg.model, cfg)
```
But it returns 
`omegaconf.errors.MissingMandatoryValue: model.params.cfg`

Yes, this is unnecessary but sometimes we may lazy and just want to pass all the `cfg: DictConfig` to a class for a quick test.

**Comment by shaolinkhoa** [comment]
Because my training process is in a `BaseModel` class.
I use the main to call it. So I need to give `cfg: DictConfig in main()` to `BaseModel`.
I tried 
```yaml
model:
  name: mnist
  class: BaseModel  # The path may wrong. But in general, I will load class BaseModel 
  params:
    cfg: ???
```
`instantiate(cfg.model, cfg)`
But it doesn't work

**Comment by omry** [comment]
```python
import hydra
from omegaconf import OmegaConf


class BaseModel:
    def __init__(self, cfg):
        self.cfg = cfg

    def shape(self):
        print("cfg.name:", self.cfg.name)


if __name__ == "__main__":
    cfg = OmegaConf.create(
        {"name": "mnist", "model": {"class": "__main__.BaseModel", "params": {}}}
    )

    model = hydra.utils.instantiate(cfg.model, cfg)
    model.shape()

```

**Comment by shaolinkhoa** [comment]
Thank you.
I can do it now by setting `params: {}` 
What I did:
Given `BaseModel` in `conf/test_py_class_object/model.py`
```python
class BaseModel:
    def __init__(self, cfg):
        self.cfg = cfg

    def shape(self):
        print(f"cfg: {self.cfg.pretty()}")
```

conf/**config.yaml:**
```yaml
defaults:
  - dataset: mnist
  - model: mnist
```
  
conf/model/**mnist.yaml:**
```yaml
model:
  name: mnist
  class: configs.test_py_class_object.model.BaseModel 
  params: {}
```

```python
@hydra.main(config_path="configs/train.yaml")
def main(cfg: DictConfig) -> None:
    model= hydra.utils.instantiate(cfg.model, cfg) 
    model.shape()
```

**Comment by omry** [comment]
Params should actually be optional, but there have been some improvements around instantiate since 0.11.3 so it may only work in master.

**Comment by shaolinkhoa** [comment]
ah, thank you.
```yaml
model:
  name: mnist
  class: configs.test_py_class_object.model.BaseModel 
  params: ???
```
also works. 
My hydra version is `0.11.3`.
Looking forward to the improvements from the master.
