### ISSUE TITLE
References is not working as expected when instantiating

### ISSUE THREAD

**Issue by igormq** [facebookresearch/hydra#511]
Example:

```yaml
variable: 
  cls: myClass
my_class: ${variable}
```
```python
hydra.utils.instantiate(cfg.my_class)
>> ValueError: Input config does not have a cls field
```
