### ISSUE TITLE
try colorlog

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#53]
﻿https://pypi.org/project/colorlog/

**Comment by malarinv** [comment]
@omry how do i keep the formatter settings? I tried the following but it doesn't use the specified format anymore :(
```
defaults:
  - hydra/job_logging: colorlog
hydra:
  job_logging:
    formatters:
      simple:
        format: '%(asctime)s - %(name)s:%(lineno)d} - %(levelname)s - %(message)s'
    root:
      handlers: [console]```

**Comment by omry** [comment]
@malarinv, Please create a new issue and describe what you have done, and what the problem is in more detail.

**Comment by omry** [comment]
Did you follow the instructions at the colorlog hydra plugin [page](https://hydra.cc/docs/plugins/colorlog)?

**Comment by malarinv** [comment]
@omry I mean, I'm able to get logs in color, but I want to be able to [customize the logs](https://hydra.cc/docs/configure_hydra/logging/) as well. right now if the default *hydra/job_logging* is set to *colorlog* and not *custom*,  can the custom logging formatters still be enabled somehow?
```
hydra:
  job_logging:
    formatters:
      simple:
        format: '[%(levelname)s] - %(message)s'
    root:
      handlers: [console]
```

**Comment by omry** [comment]
This is not different than anything else in Hydra, you can still compose configuration by overriding from your own code.

first of all, take a look at the colorlog [plugin configuration](https://github.com/facebookresearch/hydra/tree/master/plugins/hydra_colorlog/hydra_plugins/hydra_colorlog/conf), all it really does it to add another log config you can use.

If you run your app with verbose.hydra=true, you will see the composition order.
You can customize the logging in many ways.

1. Have your own copy of the colorlog log config and compose it instead of one that comes with the colorlog hydra plugin.
This is somewhat of a big hammer.

2. Just override specific fields in the log config from your own config.

your_config.yaml
```yaml
# compose the colorlog job_logging config
defaults:
  - hydra/job_logging: colorlog

# override the formatting.
hydra:
  job_logging:
    formatters:
      colorlog:
        format: '[%(blue)s%(name)s%(reset)s][%(log_color)s%(levelname)s%(reset)s] - %(message)s'
```

I didn't test it but it should work.
