### ISSUE TITLE
Recursive instantiation

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#566]
this would go well with a change to the config definition of an instantiated object:
### Current
```yaml
model:
  cls: foo.bar.ResNet
  params:
    num_layers: 50
```
### New
```yaml
model:
  _target_: model.ResNet
  num_layers: 50
```

Once this is implemented, we can describe recursive instantiation like:
```yaml
trainer:
  _target_: trainer.Trainer
  batch_size: 32
  model:
    _target_: model.ResNet
    num_layers: 50
```
An remaining open question is how to support passthrough for nested objects.

Currently, passthrough can override individual values:

```python
trainer = instantiate(cfg.trainer, batch_size=64)
```

a possible approach is for nested objects is to use a dictionary:

```python
trainer = instantiate(cfg.trainer, batch_size=64, overrides={"trainer.model.num_layers": 50})
```

**Comment by shagunsodhani** [comment]
Is the New style intended to replace the current one?

**Comment by omry** [comment]
Not entirely. If you don't own the the dataclass you will not be able to add the _type_ field to it.

**Comment by shagunsodhani** [comment]
Okay my original concern was if we could keep around the `params` namespace but if both the styles can be used, that request is moot.

**Comment by omry** [comment]
we may want to deprecate it in favor of 
```
args:
 - positional_1
 - positional_1
kwargs:
  named_1 : 1
  named_2 : 2
```

**Comment by shagunsodhani** [comment]
> we may want to deprecate it in favor of
> 
> ```
> args:
>  - positional_1
>  - positional_1
> kwargs:
>   named_1 : 1
>   named_2 : 2
> ```

Looks good!

**Comment by Hulk89** [comment]
I'm currently use recursive instantiating like this.

## config.yaml
```yaml
string: hello hydra
parent_module:
  _target_: modules.a.A
  __args:
    - ${child_module}
child_module:
  _target_: modules.b.B
  value: ${string}
```

## main.py
```python
import hydra
from omegaconf import DictConfig, OmegaConf

def instantiate(conf, *args, **kwargs):
    if hasattr(conf, "_target_"):
        if '__args' in conf:
            args = list(args) + [instantiate(i) for i in conf.__args]
            primitive_conf = OmegaConf.to_container(conf, resolve=True)
            del primitive_conf['__args']
            conf = DictConfig(primitive_conf)
    return hydra.utils.instantiate(conf, *args, **kwargs)


@hydra.main(config_path='conf', config_name='config')
def my_app(cfg : DictConfig) -> None:
    print(OmegaConf.to_yaml(cfg))
    obj = instantiate(cfg.parent_module)
    print(obj)

if __name__ == "__main__":
    my_app()
```

`__args` is for non-primitive objects.
1. check if conf has `_target_` attribute and `__args`
2. then instantiate conf in `__args` and append it to `args`
3. delete `__args` in conf
4. instantiate conf with `args`

By seperating parent and child module, I can change all parameters. :)
