### ISSUE TITLE
Recursive Object Creation [Feature Request]

### ISSUE THREAD

**Issue by sebascuri** [facebookresearch/hydra#622]
# 🚀 Feature Request

It is useful to have a recursive object initialization. 

## Motivation
Suppose I have the following structure
```
├ ── conf
|   └── config.yaml
│   └── agent
|        └── agent.yaml
|        └── complex_property
|               └── complex_property_1.yaml
|               └── complex_property_2.yaml
|          
└── my_app.py
```

The class Agent is defined as follows
```python

class Agent(object):
    def __init__(self, name: str, complex_property: ComplexProperty) -> None:
         self.name = name
         self.complex_property = complex_property
```

The class ComplexProperty is defined as follows
```python

class ComplexProperty(object):
    def __init__(self, code_number: int) -> None:
         self.code_number = code_number
```

The agent.yaml looks like:
```yaml
agent:
   class: path_to_agent.Agent
   params:
       name: great_agent
       complex_property:
              class: path_to_complex_property.ComplexProperty
              params: 
                   code_number: 1
```

## Pitch
**Describe the solution you'd like**
I'd like to be able to call hydra.utils.instantiate(cfg.agent) and this should recursively initialize the parameters. 

I'd also like to be able to default one of the complex_property and be able to override them from the CLI. 

I'd also like to be able to default a complex_property that is not necessarily in a sub-directory  (by giving a relative path to the .yaml file for instance). 

**Describe alternatives you've considered**
I just initialized the complex_property with hydra.utils.instantiate and then within python initialize the agent.
