### ISSUE TITLE
Allow setting environment variable automatically for jobs

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#7]
This is low priority at the moment, please vote up if you will find it useful.

Control of env variables for launched jobs.
This could be based on a special node in the job config:
```
env:
  OMP_NUM_THREADS: 1 
  # copy env from running machine
  USER: ${env:USER} 
```

TO BE CLEAR:
You can already use environment variables in configs:
See the [OmegaConf documentation](https://omegaconf.readthedocs.io/en/1.4_branch/usage.html#environment-variable-interpolation).

This issue is about allowing easier control of the environment variable of Hydra apps for other purposes (for example, setting OMP_NUM_THREADS automatically to 1).
