### ISSUE TITLE
Conditional config

### ISSUE THREAD

**Issue by pvnieo** [facebookresearch/hydra#735]
Hi!

I'm using Hydra 1.0.0rc1.
You can find attached my config layout.

Basically, I'm working on a DL project. I have many models, datasets and data transforms. Each model support only one data transform, which is indicated in it's config file.

Each data transform has parameters that depends on the chosen dataset, and that get interpolated later.

What I want to do, is when I ran my program, I only have to chose the model, then the data transform get chosen automatically, and get passed automatically to the dataset.

But when I ran the config I provided above, using:
```
python3 test_config.py dataset@trainset=in_memory_faust_remeshed model=geomfmaps_pointnet2
```
I got AssertionError.

What I'm doing wrong?

[conf.zip](https://github.com/facebookresearch/hydra/files/4853831/conf.zip)

**Comment by pvnieo** [comment]
The error is coming from:
```
pre_transforms: ${model.transforms.pre_transforms}
```

but when I do:
```
pre_transforms: ${model.transforms}.pre_transforms
```
it returns a string!

**Comment by omry** [comment]
Looks like a bug in OmegaConf.
You are doing something I never tested for here.
I narrowed it down to this minimal example:
```yaml
transform:
  standard_transforms:
    pre_transforms:
    - transform: NormalizeScale
model:
  transforms: ${transform.standard_transforms}
dataset:
  pre_transforms: ${model.transforms.pre_transforms}
```
