### ISSUE TITLE
[Bug] MISSING for Object Conf cls argument

### ISSUE THREAD

**Issue by anthonytec2** [facebookresearch/hydra#791]
# 🐛 Bug

OmegaConf cls argument should not be a mandatory value if target is defined. Can we change this to be an optional value with None being the default?
 
** Stack trace/error message **
```
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: scheduler.cls
        full_key: scheduler.cls
        reference_type=ObjectConf
        object_type=ObjectConf
```

## System information
- **Hydra Version** :  1.0.0rc2
- **Python version** : 3.7.7

**Comment by omry** [comment]
Please create a minimal repro.

**Comment by omry** [comment]
cc @shagunsodhani

**Comment by anthonytec2** [comment]
[struct.zip](https://github.com/facebookresearch/hydra/files/4940924/struct.zip)
Run: `python my_app.py +fn=NR +db=mysql`

**Comment by shagunsodhani** [comment]
Added the example as a gist: https://gist.github.com/shagunsodhani/cafab41a2ce43d3cb4604c652725aa02

In the current form, the bug is not happening because of `cls`/`target`. It is happening because `dict(cfg.fn)` is trying to resolve `cfg.fn` (which contains a key with missing value). Adding the config below for reference:

```
db:
  driver: mysql
  host: localhost
  port: 3306
fn:
  target: my_app.name_print
  params:
    name: ''
  cls: ???
```

I modified the script to use `hydra.utils.instantiate` (which I think was the intent of the user). In that case, the script works fine. The reference script (with one change): https://gist.github.com/shagunsodhani/f5bad29584e7cddee47526257237970e  and command to run it: `python my_app.py +fn=NR +db=mysql fn.params.name=hydra`. Output: 

```
hydra
db:
  driver: mysql
  host: localhost
  port: 3306
fn:
  target: my_app.name_print
  params:
    name: hydra
  cls: ???
```

On a side note, running the script does not throw any warning (despite `cls` key being present) because of the [additional check that `cls=???`](https://github.com/facebookresearch/hydra/blob/master/hydra/_internal/utils.py#L598). Had some value been set for `cls`, the script will throw a warning, but still work. For example, if the command is:  `python my_app.py +fn=NR +db=mysql fn.params.name=hydra fn.cls=any_random_cls`, output will be:

```
UserWarning: Config key 'fn.cls' is deprecated since Hydra 1.0 and will be removed in Hydra 1.1.
Use 'target' instead of 'cls'.
  warnings.warn(
hydra
db:
  driver: mysql
  host: localhost
  port: 3306
fn:
  target: my_app.name_print
  params:
    name: hydra
  cls: any_random_cls
```

In the above example, note that if both `cls` and `target` are present, `target` will be used.
