### ISSUE TITLE
Relative variable interpolation

### ISSUE THREAD

**Issue by rohitgirdhar** [facebookresearch/hydra#826]
# 🚀 Feature Request

(This might actually be a feature request for OmegaConf, but perhaps easier to describe here.) 

It would be great to support relative variable interpolations like so:

In dataset/ucf/train.yaml
```
# @package _group_

target: torchvision.datasets.UCF101
params:
  fold: 1
  metadata_file: /path/to/${.fold}.pth
```

#### Why not just use something like `${dataset.params.fold}` instead?
That would work in simple cases. However, when overriding this package into multiple config groups, eg:

in config.yaml
```
defaults:
  - dataset@dataset_1: ucf/train
  - dataset@dataset_2: ucf/val
```

`${dataset.params.fold}` won't exist, and will have to choose between `${dataset_1.params.fold}` or `${dataset_2.params.fold}` etc., each of which might independently override the `fold` parameter, making it tricky to decide which one to use for interpolation.

Not sure how easy or feasible something like this is, but thought might be worth asking
