### ISSUE TITLE
[Doc] Ax plugin should use underscores

### ISSUE THREAD

**Issue by YannDubs** [facebookresearch/hydra#866]
I was playing around with Ax plugin: works like a charm 💯 

The docs are slightly misleading though:

```
banana.x:
 type: range
 bounds: [-5, 5]

banana.y:
 type: range
 bounds: [-5, 10.1]
```

Will not work and should be `banana_x` as in the [example](https://github.com/facebookresearch/hydra/blob/master/plugins/hydra_ax_sweeper/example/conf/config.yaml). It would also be good to document the use of having to escape underscores `\\_`. I had to dive in the code to understand how to properly use the plugin from a config file.
