### ISSUE TITLE
Allow overriding of defaults list and hydra node regardless of node schema

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#877]
Given this primary config node:

```python
@dataclass
class Config(DictConfig):
  name: str = MISSING
  age: int = MISSING

cs = ConfigStore.instance()
cs.store(name="config", node=Config)
```

It does not mention the hydra node or the defaults list.
This means that overriding either from the corresponding `config.yaml` file will be rejected per the schema.

Those two fields should be whitelisted to allow the following config.yaml to be validated against this schema without issues.

```yaml
# defaults list
defaults:
  - hydra/job_logging: disabled

# hydra node
hydra:
  job:
    name: test

# and some user config
name: foo
age: 12
```
