### ISSUE TITLE
[Bug] hydra breaks relative paths in config file

### ISSUE THREAD

**Issue by rvorias** [facebookresearch/hydra#922]
# 🐛 Bug
## Description
In my config file, `test_config.yaml` I have:
```yaml
DATA:
  BGR: true
  COCO_ANNOTATIONS: null
  CROP_HEIGHT: 64
  CROP_WIDTH: 256
  DATA_DIR: ../datasets/train
```

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro

## To reproduce

** Minimal Code/Config snippet to reproduce **
```python
import hydra

@hydra.main(config_name="test_config.yaml")
def run(cfg):
    print(os.getcwd())
```
** Stack trace/error message **
```
normal_work_dir/outputs/2020-08-26/12-40-31
```

## Expected Behavior
The normal working directory should not change.

## System information
- **Hydra Version** :  hydra-core==1.0.0rc4
- **Python version** :  Python 3.6.9
- **Virtual environment type and version** : Custom TF2.3 docker version
- **Operating system** : Linux

## Additional context
/
