### ISSUE TITLE
[Feature Request] Support merging dictionaries from command line

### ISSUE THREAD

**Issue by divchenko** [facebookresearch/hydra#939]
```
@dataclass
class Stage:
    value: int = 1

@dataclass
class Config:
  stages: List[Stage] = field(default_factory=list)
```

The following doesn't work when using structured Config from command line as it complains about mismatched types dict vs Stage:
```
stages=[{value:10}]
```

Error:
```
Error merging override stages=[{value: 10}]
Invalid type assigned : dict is not a subclass of Stage. value: {'value': 10}
        full_key: stages[0]
        reference_type=List[Stage]
        object_type=list
```

**Comment by omry** [comment]
Thanks for reporting. This is indeed a functional gap with Hydra 1.0.
As a temporary workaround, you can do something like this:

```yaml
$ python my_app.py '+foo={a:10,b:20}' '+bar={c:30,d:40}' '+list=[${foo}, ${bar}]'
foo:
  a: 10
  b: 20
bar:
  c: 30
  d: 40
list:
- ${foo}
- ${bar}
```

(the interpolations are printed as is and are resolved on access. You can also print them with OmegaConf.to_yaml(cfg, resolve=True) to see them resolved in the output):
```yaml
foo:
  a: 10
  b: 20
bar:
  c: 30
  d: 40
list:
- a: 10
  b: 20
- c: 30
  d: 40
```
