### ISSUE TITLE
Ability to exclude keys from file name; such as "random_seed"

### ISSUE THREAD

**Issue by natolambert** [facebookresearch/hydra#95]
In the hydra config, it would be useful for arranging directories if we can filter key names from the `job:override_dirname`

Consider this structure:
```
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: /checkpoint/${env:USER}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${job:num}_${job:id}/${job:override_dirname\random_seed}/${random_seed}
```

**Comment by omry** [comment]
```yaml
  # job runtime information will be populated here
  job:
    # Job name, can be specified by the user (in config or cli) or populated automatically
    name: ???

    # Concatenation of job overrides that can be used as a part
    # of the directory name.
    # This can be configured in hydra.job.config.override_dirname
    override_dirname: ???

    # Job ID in underlying scheduling system
    id: ???

    # Job number if job is a part of a sweep
    num: ???

    config:
      # configuration for the ${hydra.job.override_dirname} runtime variable
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []

```
