### ISSUE TITLE
Failed to merge configurations

### ISSUE THREAD

**Issue by vfdev-5** [facebookresearch/hydra#968]
# 🐛 Bug
## Description

I'm migrating the code and configs from hydra-core < 1.0 to 1.X following : 
https://hydra.cc/docs/upgrades/0.11_to_1.0/config_path_changes and other sections 

But I encounter an issue with merging configs, which is related to the following warning:
```
/opt/conda/lib/python3.7/site-packages/omegaconf/omegaconf.py:579: UserWarning: update() merge flag is is not specified, defaulting to False.
For more details, see https://github.com/omry/omegaconf/issues/367                                               
  stacklevel=1,                                                                                                                                      
```

The config I have is the that:
1) global file : `config/train_gan.yaml`  where `data` object is defined by a group and some other global fields are added after:
```yaml
# @package _global_
...
defaults:
  - dataset: simple
...
data:
  root: /path/to/data
  extensions:
    - png
  loader:
    # batch size per each device
    batch_size: 32
    workers: 2
...
```
And the group is defined here `config/dataset/simple.yaml` as 
```yaml
# @package _group_
data:
  type: simple
  transforms:
    to_tensor:
      _target_: torchvision.transforms.ToTensor
    normalize:
      _target_: torchvision.transforms.Normalize
      params:
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]
```

However, in the code final configuration does not contain fields from `simple.yaml`.

## Checklist
- [x] I checked on the latest version of Hydra
- [ ] I created a minimal repro

## To reproduce

** Minimal Code/Config snippet to reproduce **

** Stack trace/error message **
```
// Paste the bad output here!
```

## System information
- **Hydra Version** :  1.0.0
- **Python version** : 3.7
- **Virtual environment type and version** : 
- **Operating system** :
