### ISSUE TITLE
[Bug] Custom Resolver Only Works Somtimes

### ISSUE THREAD

**Issue by Queuecumber** [facebookresearch/hydra#988]
# 🐛 Bug
## Description
This may be an OmegaConf issue, I'm not sure where is the more appropriate place to put it.

I have a custom OmegaConf resolver registered that uses eval because sometimes I need to pass real python objects in a generic way (e.g. I can't assume what the type will be in code but the writer of the config file knows):

```
OmegaConf.register_resolver("eval", lambda x: eval(x))
```

This resolver only seems to work sometimes, and I'm not sure exactly what the rule is. I have a bunch of examples, some work and some don't work. One notable example that doesnt work is a tuple: 

```
test_fails_tuple: ${eval:(1,2,3)}
```

will be a string containing "${eval:(1,2,3)}" when I read the value from the DictConfig.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro

## To reproduce

** Minimal Code/Config snippet to reproduce **

Config:
```
test_fails_tuple: ${eval:(1,2,3)}
test_fails_tuple_2: ${eval:tuple([1,2,3])}
test_fails_list: ${eval:[1,2,3]}
test_works_function: ${eval:time.time}
test_works_int: ${eval:42}
```

Code:
```
import hydra
from omegaconf import OmegaConf
import time


@hydra.main(config_name="minimal_test.yaml")
def main(cfg):
    OmegaConf.register_resolver("eval", lambda x: eval(x))

    print(cfg.test_fails_tuple)
    print(cfg.test_fails_tuple_2)
    print(cfg.test_fails_list)
    print(cfg.test_works_function())
    print(cfg.test_works_int)

if __name__ == "__main__":
    main()
```

** Stack trace/error message **
Results of above print messages:
```
${eval:(1,2,3)}
${eval:tuple([1,2,3])}
${eval:[1,2,3]}
1600444490.9921494
42
```

## Expected Behavior
No matter what python expression I put in the eval handler, it gets passed to eval and returned. 

## System information
- **Hydra Version** :  Git master
- **Python version** : 3.7.7
- **Virtual environment type and version** : Conda 4.5.8
- **Operating system** : Ubuntu 18.04

**Comment by omry** [comment]
First of all, this is a pretty terrible abuse. can you share some details about what objects you are actually passing and why?

Read the [docs for custom resolvers](https://omegaconf.readthedocs.io/en/2.0_branch/usage.html#custom-interpolations), they outline the supported format (which, by the way - is likely to change in the next major version of OmegaConf).
I can imagine many cases when trying to embeded an arbitrary string as an interpolation would not be parsed correctly, the most commend thing is that commas and spaces are treated specially. but you could also break the formatting of the interpolation itself.

Closing as this is not a bug, but I want to hear more about your use case.

**Comment by Queuecumber** [comment]
> First of all, this is a pretty terrible abuse. can you share some details about what objects you are actually passing and why?

Yeah I think that some would consider this an anti-pattern

> Read the [docs for custom resolvers](https://omegaconf.readthedocs.io/en/2.0_branch/usage.html#custom-interpolations), they outline the supported format (which, by the way - is likely to change in the next major version of OmegaConf).
> I can imagine many cases when trying to embeded an arbitrary string as an interpolation would not be parsed correctly, the most commend thing is that commas and spaces are treated specially. but you could also break the formatting of the interpolation itself.

I see the issue with commas but not with parenthesis 

> Closing as this is not a bug, but I want to hear more about your use case.

I have a generic pipeline that I'm writing, it can take different datasets and different models and wraps them in a consistent process. This becomes a problem for when, for example, I need to support normal pytorch stuff and detectron, the latter doesnt work with the default collate function in pytorch. So here's a concrete example:

For coco using detectron the snippet of the config is
```
data:
  collate_fn: "${eval:lambda x: x}"
  root_path: /datasets01/COCO/022719
  normalization: null
  train:
    loader:
      batch_size: 8
    set:
      _target_: dataset.DetectronCOCO
      name: coco_trn
    transform: []
  val:
    loader:
      batch_size: 16
    set:
      _target_: dataset.DetectronCOCO
      name: coco_val
    transform: []
```

which works fine, note the `collate_fn`. 

Here's another example, this time the dataset is random pixels with a size:

```
data:
  normalization:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  train:
    loader:
      batch_size: 32
    set_to_tensor: no
    set:
      _target_: dataset.RandomPixelsDataset
      shape: ${eval:(3, 256, 256)}
      length: 1000000
    transform:
      - _target_: torchvision.transforms.RandomResizedCrop
        size: 224
      - _target_: torchvision.transforms.RandomHorizontalFlip
```

The shape argument doesnt work here and is what prompted the issue.

**Comment by omry** [comment]
One thing you can do for the first problem is to pass in a function name as a regular string and just get a the function object with hydra.utils.get_method().
at that point you can call it directly instead of through config access.

for 
```
shape: ${eval:(3, 256, 256)}
```
What is the advantage over a simple list?
```
shape: [3, 256, 256]
```
or
```
shape:
 - 3
 - 256
 - 256
```

**Comment by omry** [comment]
About brackets, There is an open issue with them, they are not a supported character in interpolations at the moment.

**Comment by Queuecumber** [comment]
> One thing you can do for the first problem is to pass in a function name as a regular string and just get a the function object with hydra.utils.get_method().
> at that point you can call it directly instead of through config access.

This works for what I posted and I had something similar before where that was just a string and I manually called `eval` on it before passing it as the dataloader `collate_fn` argument, but what I was hoping to do (and hadn't gotten around to changing over to yet) was:

```
data:
  root_path: /datasets01/COCO/022719
  normalization: null
  train:
    loader:
      _target_: torch.utils.data.DataLoader
      batch_size: 8
      collate_fn: "${eval:lambda x: x}"
```
And I realize my last example was incomplete (the snippet I linked is merged into a larger config with an override) because it didnt show that the `loader` field is actually instantiating a pytorch dataloader. In this case the `collate_fn` argument needs to be a callable and I can't intercept it and manually get the function (some tooling around that might help like an argument transformer).

> for
> 
> ```
> shape: ${eval:(3, 256, 256)}
> ```
> 
> What is the advantage over a simple list?
> 
> ```
> shape: [3, 256, 256]
> ```
> 
> or
> 
> ```
> shape:
>  - 3
>  - 256
>  - 256
> ```

Because the class I'm instantiating throws an exception if the argument isn't exactly a "tuple of int". Now it happens that in this case I have control over a wrapper that I can use as a workaround but that may not always be the case. 

Either way I think a more "correct" way (although I personally don't have an aversion to `eval`) is to add a `tuple` resolver and a `func` resolver that do this job in a more declarative way, although I'm not entirely sure how I can make the tuple resolver get correctly typed arguments.

**Comment by omry** [comment]
```
data:
  root_path: /datasets01/COCO/022719
  normalization: null
  train:
    loader:
      _target_: torch.utils.data.DataLoader
      batch_size: 8
      collate_fn: "${eval:lambda x: x}"
```

I think the best way to deal with this is to instantiate another class that would wrap the underlying dataloader.
It can create the collate_function with the API I described above and instantiate the underlying one, passing the actual function as a passthrough.

> Because the class I'm instantiating throws an exception if the argument isn't exactly a "tuple of int"
What is that object?
In general,transparent usage of OmegaConf will require libraries to relax their runtime type checking.

```python
In [8]: from omegaconf import OmegaConf
In [9]: from typing import Sequence, MutableSequence
In [10]: seq = OmegaConf.create([1,2,3])
In [11]: isinstance(seq, list)
Out[11]: False
In [12]: isinstance(seq, tuple)
Out[12]: False
In [13]: isinstance(seq, Sequence)
Out[13]: True
In [14]: isinstance(seq, MutableSequence)
Out[14]: True
```

**Comment by Queuecumber** [comment]
> ```
> data:
>   root_path: /datasets01/COCO/022719
>   normalization: null
>   train:
>     loader:
>       _target_: torch.utils.data.DataLoader
>       batch_size: 8
>       collate_fn: "${eval:lambda x: x}"
> ```
> 
> I think the best way to deal with this is to instantiate another class that would wrap the underlying dataloader.
> It can create the collate_function with the API I described above and instantiate the underlying one, passing the actual function as a passthrough.

Thats partially why I want to support using `instantiate` here, so that the loader is pluggable, but it would still need to work with the standard of-the-shelf dataloader class that 99% of people are going to use

> 
> > Because the class I'm instantiating throws an exception if the argument isn't exactly a "tuple of int"
> 
> What is that object?
> In general,transparent usage of OmegaConf will require libraries to relax their runtime type checking.
> 
> ```python
> In [8]: from omegaconf import OmegaConf
> In [9]: from typing import Sequence, MutableSequence
> In [10]: seq = OmegaConf.create([1,2,3])
> In [11]: isinstance(seq, list)
> Out[11]: False
> In [12]: isinstance(seq, tuple)
> Out[12]: False
> In [13]: isinstance(seq, Sequence)
> Out[13]: True
> In [14]: isinstance(seq, MutableSequence)
> Out[14]: True
> ```

I agree and usually that would work but the function is [torch.randint](https://pytorch.org/docs/stable/generated/torch.randint.html?highlight=randint#torch.randint) the size argument, which seems to take only a tuple of int. Since I wrote teh dataset that calls it I can just make a tuple out of the sequence that its given so its fine for now.

**Comment by omry** [comment]
> Thats partially why I want to support using instantiate here, so that the loader is pluggable, but it would still need to work with the standard of-the-shelf dataloader class that 99% of people are going to use

You can support instantiate as I pointed out.
for people instantiating it manually, you can just show them how to do it with an example that includes obtaining the collate function using get_method().

> I agree and usually that would work but the function is torch.randint the size argument, which seems to take only a tuple of int. Since I wrote the dataset that calls it I can just make a tuple out of the sequence that its given so its fine for now.

I think it will be good to request an API change in torch.randint to support accepting any numeric sequence.
Generally PyTorch needs to up it's game with respect to typing.

**Comment by Queuecumber** [comment]
> > Thats partially why I want to support using instantiate here, so that the loader is pluggable, but it would still need to work with the standard of-the-shelf dataloader class that 99% of people are going to use
> 
> You can support instantiate as I pointed out.
> for people instantiating it manually, you can just show them how to do it with an example that includes obtaining the collate function using get_method().

I still don't get how to use it with the standard dataloader, could you show me a small example?

> > I agree and usually that would work but the function is torch.randint the size argument, which seems to take only a tuple of int. Since I wrote the dataset that calls it I can just make a tuple out of the sequence that its given so its fine for now.
> 
> I think it will be good to request an API change in torch.randint to support accepting any numeric sequence.
> Generally PyTorch needs to up it's game with respect to typing.

I agree they should take a sequence I was surprised it didnt work

**Comment by omry** [comment]
not a small example.
```python
class DataloaderWithCollate(DataLoader):
  def __init__(self, collate_fn_name : str, loader : DictConfig):
      collate_fn = get_method(collate_fn_name)
      self.delegate = instantiate(loader, collate_fn=collate_fn) # passthrough

  def item(self, idx):
      return self.delegate.item(idx)
  ...
```

config:
```yaml
dataloader:
   _target_ : DataloaderWithCollate
   collate_fn_name : fooo.baar
   loader:
      _target_: torch.utils.data.DataLoader
      batch_size: 8
```

**Comment by Queuecumber** [comment]
This isn't too bad but I don't think adding a `function` or similar interpolation is that crazy, which would make it 

```
loader:
  _target_: torch.utils.data.DataLoader
   batch_size: 8
  collate_fn: ${function:detectron2.data.build.trivial_batch_collator}
```

```
Omegaconf.register_resolver("function", lambda x: hydra.utils.get_method(x))
```

one advantage to your way is that the collate_fn is a string without needing to worry about any interpolation syntax

**Comment by omry** [comment]
sure, that works too.

**Comment by Queuecumber** [comment]
When I try to do it that way I'm actually hitting another error. In one of my scripts I need to override that collate_fn no matter what the user picks for it (their choice is moved to a later stage of the process). When I try to do the override in code I  get an error that "function is not a supported primitive type". Heres a minimal reproduction:

config:
```
func: ${function:torch.utils.data.dataloader.default_collate}
func_print:
    _target_: simple_test.write
    f: ${function:torch.utils.data.dataloader.default_collate}
```

code:
```
import hydra
from omegaconf import OmegaConf
import time

def write(f):
    print(f)

@hydra.main(config_name="test.yaml")
def main(cfg) -> None:
    OmegaConf.register_resolver("function", lambda x: hydra.utils.get_method(x))

    cfg.func = time.time

    print(cfg.func)

    hydra.utils.instantiate(cfg.func_print)

if __name__ == "__main__":
    main()
```

Error is 
```
Traceback (most recent call last):
  File "simple_test.py", line 19, in <module>
    main()
  File "/private/home/mehrlich/.conda/envs/qgac/lib/python3.7/site-packages/hydra/main.py", line 37, in decorated_main
    strict=strict,
  File "/private/home/mehrlich/.conda/envs/qgac/lib/python3.7/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    lambda: hydra.run(
  File "/private/home/mehrlich/.conda/envs/qgac/lib/python3.7/site-packages/hydra/_internal/utils.py", line 200, in run_and_report
    raise ex
  File "/private/home/mehrlich/.conda/envs/qgac/lib/python3.7/site-packages/hydra/_internal/utils.py", line 197, in run_and_report
    return func()
  File "/private/home/mehrlich/.conda/envs/qgac/lib/python3.7/site-packages/hydra/_internal/utils.py", line 349, in <lambda>
    overrides=args.overrides,
  File "/private/home/mehrlich/.conda/envs/qgac/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 112, in run
    configure_logging=with_log_configuration,
  File "/private/home/mehrlich/.conda/envs/qgac/lib/python3.7/site-packages/hydra/core/utils.py", line 125, in run_job
    ret.return_value = task_function(task_cfg)
  File "simple_test.py", line 12, in main
    cfg.func = time.time
  File "/private/home/mehrlich/.conda/envs/qgac/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 278, in __setattr__
    self._format_and_raise(key=key, value=value, cause=e)
  File "/private/home/mehrlich/.conda/envs/qgac/lib/python3.7/site-packages/omegaconf/base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "/private/home/mehrlich/.conda/envs/qgac/lib/python3.7/site-packages/omegaconf/_utils.py", line 675, in format_and_raise
    _raise(ex, cause)
  File "/private/home/mehrlich/.conda/envs/qgac/lib/python3.7/site-packages/omegaconf/_utils.py", line 591, in _raise                                                                                                                                                                   "devfair0236" 08:14 21-Sep-20
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.UnsupportedValueType: Value 'builtin_function_or_method' is not a supported primitive type
        full_key: func
        reference_type=Optional[Dict[Union[str, Enum], Any]]
        object_type=dict
```
